/**
 * Provider icons are bundled, not fetched.
 *
 * Until this, every card render asked `cdn.simpleicons.org` for `/stripe`,
 * `/github`, `/aws`, `/openai` — so a third party, and anyone on the network
 * path, learned the exact set of services the user holds credentials for, the
 * entry count per service, their IP, and when they opened their vault. For a
 * product whose README opens with "runs on your machine and talks to nothing
 * else … no telemetry", that was the most sensitive metadata it holds, leaving
 * by default (review-01 §3.3).
 *
 * The paths now come from `src/ts/icon-paths.ts`, generated by
 * `npm run icons`. These tests are what keeps the generated file honest — a
 * stale one would fail silently, as letter avatars, which is exactly how 55 dead
 * CDN slugs went unnoticed for several phases.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { iconHTML, getIconSlug } from '../src/ts/icons';
import { ICON_PATHS } from '../src/ts/icon-paths';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconsSrc = readFileSync(join(ROOT, 'src', 'ts', 'icons.ts'), 'utf8');

/** The slugs the picker offers, read from the registry the same way the generator does. */
function registrySlugs(): string[] {
  const block = /const SI_REGISTRY[^=]*=\s*\[([\s\S]*?)\n\];/.exec(iconsSrc);
  if (!block) throw new Error('SI_REGISTRY not found — the generator parses this shape too');
  return [...block[1].matchAll(/\[\s*'([^']+)'\s*,/g)].map((m) => m[1]);
}

describe('nothing reaches the network', () => {
  it('renders a known provider as a self-contained data: URI', () => {
    const html = iconHTML('GitHub');
    expect(html).toContain('src="data:image/svg+xml,');
    // The SVG's own xmlns is an http URL, but it is inside the data: URI and
    // percent-encoded, so it is markup rather than a request. What must not
    // appear is a src that fetches anything.
    expect(html).not.toMatch(/src="https?:/);
    expect(html).not.toContain('cdn.simpleicons.org');
  });

  it('no source file builds a remote icon URL', () => {
    // The CSP no longer allows it, so a regression here is an invisible broken
    // image rather than a leak — but an invisible broken image is how this was
    // missed the first time.
    expect(iconsSrc).not.toMatch(/https:\/\/cdn\.simpleicons\.org\/\$\{/);
  });

  it('the CSP does not allow the icon CDN', () => {
    const conf = readFileSync(join(ROOT, 'src-tauri', 'tauri.conf.json'), 'utf8');
    expect(conf).not.toContain('cdn.simpleicons.org');
    expect(conf).toContain("img-src 'self' data: blob: tauri:");
  });
});

describe('the generated bundle tracks the registry', () => {
  it('covers the overwhelming majority of registry slugs', () => {
    const slugs = registrySlugs();
    const have = slugs.filter((s) => Object.prototype.hasOwnProperty.call(ICON_PATHS, s));
    // Not 100%: simple-icons removes icons on trademark request (microsoft,
    // slack, twitter, openai, java, oracle …) and those have been 404ing from
    // the CDN for a long time already. They render as letter avatars now, which
    // is exactly what they rendered as before. The floor catches a *stale
    // generated file*, which is the failure worth catching.
    expect(have.length / slugs.length).toBeGreaterThan(0.8);
    expect(have.length).toBeGreaterThan(350);
  });

  it('has no bundled icon that the registry does not offer', () => {
    // Dead weight in the bundle means the generator ran against a different
    // registry than the one shipping.
    const slugs = new Set(registrySlugs());
    const orphans = Object.keys(ICON_PATHS).filter((s) => !slugs.has(s));
    expect(orphans).toEqual([]);
  });

  it('lists no slug twice', () => {
    // A duplicate row is a second chance to be wrong: the Fly.io entry appeared
    // once as `flydotio` and once as the long-dead `fly`, so the picker offered
    // the same provider twice and one of them was always a letter.
    const slugs = registrySlugs();
    expect(slugs.length).toBe(new Set(slugs).size);
  });

  it('every bundled path is a plausible SVG path, not markup', () => {
    // The value is interpolated into a `d="…"` attribute inside an SVG document
    // that is then URI-encoded. A `"` or `<` in it would break out.
    for (const [slug, d] of Object.entries(ICON_PATHS)) {
      expect(d, slug).toMatch(/^[Mm]/);
      expect(d, slug).not.toContain('"');
      expect(d, slug).not.toContain('<');
    }
  });
});

describe('unknown slugs degrade to a letter, not a broken image', () => {
  it('falls back for a registry slug with no bundled path', () => {
    // `slack` is in the registry and was removed from simple-icons upstream.
    expect(getIconSlug('Slack')).toBe('slack');
    const html = iconHTML('Slack');
    expect(html).toContain('si-fallback');
    expect(html).not.toContain('<img');
  });

  it('never emits an <img> with an empty src', () => {
    const html = iconHTML('Slack');
    expect(html).not.toContain('src=""');
  });

  it('still falls back for a provider that matches no slug at all', () => {
    expect(iconHTML('Zzzzz Not A Real Provider')).toContain('si-fallback');
  });
});

describe('the data URI is well formed', () => {
  it('escapes the fill colour so the URI is not truncated at a fragment', () => {
    // An unencoded `#e4e4e4` would end the URI at the `#`, leaving an SVG with
    // no closing tag — which renders as nothing, silently.
    const html = iconHTML('GitHub');
    expect(html).toContain('%23e4e4e4');
    expect(html).not.toContain('#e4e4e4');
  });

  it('round-trips back to valid SVG containing the bundled path', () => {
    const html = iconHTML('GitHub');
    const src = /src="([^"]+)"/.exec(html)![1];
    const svg = decodeURIComponent(src.replace('data:image/svg+xml,', ''));
    expect(svg.startsWith('<svg')).toBe(true);
    expect(svg.endsWith('</svg>')).toBe(true);
    expect(svg).toContain(ICON_PATHS.github);
  });
});
