/**
 * Stack integrations (Phase 38): the TypeScript interpreter of
 * `vault-core/data/stack-adapters.json`, pinned against the same golden files as
 * the Rust one (`envv-cli/tests/stack_parity.rs`). Regenerate deliberately with
 * `PARITY_UPDATE=1 npx vitest run tests/stack.test.ts`, then run the Rust test.
 */
import { describe, it, expect, beforeEach } from 'vitest';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { st } from '../src/ts/state';
import { resolveFieldRef } from '../src/ts/chunk-ops';
import {
  renderStack,
  stackAdapter,
  stackAdapters,
  stackChunkTypes,
  stackStarterChunks,
  newStackChunk,
  stackChunkSpec,
} from '../src/ts/stack';
import { loadRealIndexHtml, resetState } from './helpers';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'parity');
const fixture = JSON.parse(readFileSync(join(FIXTURES, 'stack-vault.json'), 'utf8'));

const real = (raw: string): string => resolveFieldRef(raw, true).resolved ?? raw;

function project(id: string) {
  const p = st.vault.projects.find((x: any) => x.id === id);
  if (!p) throw new Error(`fixture has no project ${id}`);
  return p;
}

function golden(name: string, actual: string) {
  const path = join(FIXTURES, name);
  if (process.env.PARITY_UPDATE || !existsSync(path)) {
    writeFileSync(path, actual);
    return;
  }
  expect(actual).toBe(readFileSync(path, 'utf8'));
}

beforeEach(() => {
  loadRealIndexHtml();
  resetState(st);
  st.vault = JSON.parse(JSON.stringify(fixture));
});

describe('stack adapters, golden files shared with the Rust interpreter', () => {
  it('prometheus', () => {
    golden('stack-prometheus.yml', renderStack(stackAdapter('prometheus')!, project('prom'), real));
  });
  it('grafana', () => {
    golden('stack-grafana.yml', renderStack(stackAdapter('grafana')!, project('graf'), real));
  });
  it('homepage', () => {
    golden('stack-homepage.yaml', renderStack(stackAdapter('homepage')!, project('home'), real));
  });
});

describe('the TypeScript interpreter', () => {
  it('reads the same adapters, in the same order, as the Rust one', () => {
    expect(stackAdapters().map((a) => a.id)).toEqual(['prometheus', 'grafana', 'homepage']);
    expect(stackChunkTypes()).toEqual([
      'prom_global',
      'prom_scrape',
      'prom_remote_write',
      'grafana_datasource',
      'homepage_service',
    ]);
  });

  it('puts no secret reference in a file and no unresolved placeholder either', () => {
    for (const [id, p] of [
      ['prometheus', 'prom'],
      ['grafana', 'graf'],
      ['homepage', 'home'],
    ] as const) {
      const out = renderStack(stackAdapter(id)!, project(p), real);
      expect(out, id).not.toMatch(/\$\{/);
    }
  });

  it('quotes a password that is only digits, so YAML cannot read it as a number', () => {
    const out = renderStack(stackAdapter('prometheus')!, project('prom'), real);
    expect(out).toContain('password: "424242"');
  });

  it('leaves a disabled chunk out', () => {
    const out = renderStack(stackAdapter('prometheus')!, project('prom'), real);
    expect(out).not.toContain('old:9100');
    expect(out).not.toContain('paused');
  });

  it('hands the resolver the descriptors secret flag, and only for secret fields', () => {
    const seen: [string, boolean][] = [];
    renderStack(stackAdapter('prometheus')!, project('prom'), (raw, secret) => {
      seen.push([raw, secret]);
      return real(raw);
    });
    expect(seen).toContainEqual(['${PromScrape}', true]);
    expect(seen).toContainEqual(['scraper', false]);
  });

  it('starter chunks and new chunks carry the descriptors defaults', () => {
    const a = stackAdapter('prometheus')!;
    const starters = stackStarterChunks(a);
    expect(starters.map((c) => c.chunk_type)).toEqual(['prom_global', 'prom_scrape']);
    const targets = starters[1].fields.find((f) => f.key === 'targets')!;
    expect(targets.value).toBe('localhost:9090');
    expect(targets.field_type).toBe('list');
    const fresh = newStackChunk(stackChunkSpec(a, 'prom_scrape')!, 'x');
    expect(fresh.fields.find((f) => f.key === 'password')!.field_type).toBe('secret');
  });

  it('writes an empty scrape list instead of dropping it, and nothing else', () => {
    const empty = { id: 'e', name: 'e', project_type: 'prometheus', chunks: [] } as any;
    expect(renderStack(stackAdapter('prometheus')!, empty, real)).toBe(
      '# Generated by UnENVerse\nscrape_configs: []\n',
    );
  });

  it.each([
    ['plain', 'plain'],
    ['', '""'],
    ['null', '"null"'],
    ['No', '"No"'],
    ['0x1F', '"0x1F"'],
    ['a: b', '"a: b"'],
    ['line\nbreak', '"line\\nbreak"'],
  ])('writes %j the way the Rust interpreter does', (value, written) => {
    const p = {
      id: 'q',
      name: 'q',
      project_type: 'prometheus',
      chunks: [
        {
          id: '1',
          name: 'j',
          chunk_type: 'prom_scrape',
          fields: [
            { key: 'targets', value: 'h:1' },
            { key: 'username', value: value || ' ' },
            { key: 'password', value },
          ],
        },
      ],
    } as any;
    // The password is secret and goes through the resolver untouched; an empty
    // one is dropped, which is also the Rust behaviour.
    const out = renderStack(stackAdapter('prometheus')!, p, (raw) => raw);
    if (value === '') expect(out).not.toContain('password');
    else expect(out).toContain(`password: ${written}`);
  });
});
