//! Golden tests for the on-disk formats (roadmap R01, project phase 43).
//!
//! The fixture in `fixtures/vault-0.42.x/` was written by the 0.42.4 build
//! (rusqlite =0.31.0, SQLCipher 4.5) and is never regenerated by CI. Every
//! dependency move that touches SQLCipher or Argon2 must keep these green; if
//! one fails, the format changed and a migration is owed, not a new fixture.
//!
//! Regenerate only on purpose, from the build you want to pin:
//! `cargo test -p vault-core --test golden_vault -- --ignored generate`

use serde_json::{json, Value};
use std::path::{Path, PathBuf};
use vault_core::{derive_key, open_db, SaveCtx};

/// Test-only password; not a credential for anything.
const PW: &str = "golden-fixture-password";
/// Fixed so the Argon2 vector below is reproducible.
const SALT: [u8; 16] = *b"unv-golden-salt!";
/// Argon2id m=65536 t=3 p=1 over PW and SALT, produced by 0.42.4.
const KEY_HEX: &str = "5b214207fcc8bf995f4eaa4876536cf2089823fc52c1b0050a89203ad4a6ca47";

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/vault-0.42.x")
}

fn copy_to_temp(name: &str) -> (PathBuf, PathBuf, PathBuf) {
    let tmp = std::env::temp_dir().join(format!("unv-golden-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    let db = tmp.join("vault.db");
    let salt = tmp.join("vault.salt");
    std::fs::copy(fixture_dir().join("vault.db"), &db).unwrap();
    std::fs::copy(fixture_dir().join("vault.salt"), &salt).unwrap();
    (tmp, db, salt)
}

fn save(conn: &rusqlite::Connection, doc: Value, base: Option<&str>) -> String {
    vault_core::save_vault(
        conn,
        doc,
        SaveCtx {
            actor: None,
            expect_version: base,
        },
    )
    .unwrap()
}

#[test]
fn argon2_vector_is_unchanged() {
    let key = derive_key(PW, &SALT).unwrap();
    assert_eq!(hex::encode(key), KEY_HEX);
}

#[test]
fn old_vault_opens_and_verifies() {
    let (tmp, db, salt) = copy_to_temp("open");
    assert_eq!(std::fs::read(&salt).unwrap(), SALT);
    let key = derive_key(PW, &SALT).unwrap();
    let conn = open_db(&db, &key).expect("0.42.x vault must open");

    let ok: String = conn
        .query_row("PRAGMA integrity_check", [], |r| r.get(0))
        .unwrap();
    assert_eq!(ok, "ok");
    // cipher_integrity_check returns one row per bad page and none when sound.
    let mut stmt = conn.prepare("PRAGMA cipher_integrity_check").unwrap();
    let bad: Vec<String> = stmt
        .query_map([], |r| r.get(0))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    assert!(bad.is_empty(), "cipher_integrity_check: {bad:?}");
    drop(stmt);

    assert!(vault_core::verify_vault_integrity(&conn).unwrap());

    // No `cipher_migrate`, no schema bump: the fixture opens as it is.
    vault_core::init_schema(&conn).unwrap();
    let v = vault_core::load_vault(&conn).unwrap().unwrap();
    assert_eq!(v["api_keys"].as_array().unwrap().len(), 3);
    let proj = &v["projects"][0];
    assert_eq!(proj["name"], "homelab");
    assert_eq!(proj["chunks"].as_array().unwrap().len(), 2);

    // History kept the old value of the edited key.
    let stripe = v["api_keys"]
        .as_array()
        .unwrap()
        .iter()
        .find(|e| e["id"] == "g-1")
        .unwrap();
    assert_eq!(stripe["api_key"], "sk_test_golden_two");
    assert!(stripe["version_history"]
        .to_string()
        .contains("sk_test_golden_one"));

    // Audit chain: oldest row anchors to genesis, each row links to its predecessor.
    let rows = vault_core::load_audit(&conn).unwrap();
    assert!(rows.len() >= 3, "audit rows: {}", rows.len());
    let oldest = rows.last().unwrap();
    assert_eq!(oldest.prev_hash, None, "first row anchors to genesis");
    for pair in rows.windows(2) {
        assert_eq!(pair[0].prev_hash, pair[1].entry_hash, "chain broken");
    }
    let _ = std::fs::remove_dir_all(tmp);
}

#[test]
fn old_vault_accepts_a_new_save() {
    let (tmp, db, _) = copy_to_temp("save");
    let key = derive_key(PW, &SALT).unwrap();
    let conn = open_db(&db, &key).unwrap();
    vault_core::init_schema(&conn).unwrap();
    let mut doc = vault_core::load_vault(&conn).unwrap().unwrap();
    let base = vault_core::vault_version(&conn).unwrap();
    doc["api_keys"]
        .as_array_mut()
        .unwrap()
        .push(json!({ "id": "g-4", "provider": "Added", "api_key": "sk_test_golden_new" }));
    save(&conn, doc, base.as_deref());
    assert!(vault_core::verify_vault_integrity(&conn).unwrap());
    let again = vault_core::load_vault(&conn).unwrap().unwrap();
    assert_eq!(again["api_keys"].as_array().unwrap().len(), 4);
    let _ = std::fs::remove_dir_all(tmp);
}

/// The bundled engine is what releases ship (SQLite >= 3.51.3 carries the WAL-reset
/// corruption fix). A dev build on Unix links the system SQLCipher instead, so the
/// floor is only enforced where the bundled one is compiled in
/// (`--features bundled`, and every Windows build). The version is recorded either way.
#[test]
fn sqlite_is_new_enough_where_bundled() {
    let (tmp, db, _) = copy_to_temp("version");
    let key = derive_key(PW, &SALT).unwrap();
    let conn = open_db(&db, &key).unwrap();
    let sqlite: String = conn
        .query_row("SELECT sqlite_version()", [], |r| r.get(0))
        .unwrap();
    let cipher: String = conn
        .query_row("PRAGMA cipher_version", [], |r| r.get(0))
        .unwrap();
    println!("sqlite {sqlite}, sqlcipher {cipher}");
    assert!(!cipher.is_empty(), "this must be a SQLCipher build");
    if cfg!(any(feature = "bundled", windows)) {
        let v: Vec<u32> = sqlite.split('.').map(|p| p.parse().unwrap()).collect();
        assert!(v >= vec![3, 51, 3], "bundled SQLite {sqlite} < 3.51.3");
    }
    let _ = std::fs::remove_dir_all(tmp);
}

/// `open_db` sets its own busy timeout and WAL size cap instead of inheriting them.
#[test]
fn open_db_sets_busy_timeout_and_journal_limit() {
    let (tmp, db, _) = copy_to_temp("pragmas");
    let key = derive_key(PW, &SALT).unwrap();
    let conn = open_db(&db, &key).unwrap();
    let busy: i64 = conn
        .query_row("PRAGMA busy_timeout", [], |r| r.get(0))
        .unwrap();
    assert_eq!(busy, 5000);
    let limit: i64 = conn
        .query_row("PRAGMA journal_size_limit", [], |r| r.get(0))
        .unwrap();
    assert_eq!(limit, 64 * 1024 * 1024);
    let _ = std::fs::remove_dir_all(tmp);
}

// Controls: the checks above must be able to fail.

#[test]
fn wrong_password_fails_cleanly() {
    let (tmp, db, _) = copy_to_temp("wrongpw");
    let key = derive_key("not-the-password", &SALT).unwrap();
    let err = open_db(&db, &key).unwrap_err();
    assert_eq!(err, "Wrong master password");
    let _ = std::fs::remove_dir_all(tmp);
}

#[test]
fn damaged_fixture_fails_the_integrity_check() {
    let (tmp, db, _) = copy_to_temp("corrupt");
    let mut bytes = std::fs::read(&db).unwrap();
    // Flip bytes in the middle of a later page; the header stays readable.
    let at = bytes.len() * 3 / 4;
    for b in &mut bytes[at..at + 64] {
        *b ^= 0xA5;
    }
    std::fs::write(&db, bytes).unwrap();
    let key = derive_key(PW, &SALT).unwrap();
    let broken = match open_db(&db, &key) {
        Err(_) => true,
        Ok(conn) => {
            let mut stmt = conn.prepare("PRAGMA cipher_integrity_check").unwrap();
            let n = stmt
                .query_map([], |r| r.get::<_, String>(0))
                .unwrap()
                .count();
            n > 0
                || conn
                    .query_row("PRAGMA integrity_check", [], |r| r.get::<_, String>(0))
                    .map(|s| s != "ok")
                    .unwrap_or(true)
        }
    };
    assert!(broken, "a damaged page must be noticed");
    let _ = std::fs::remove_dir_all(tmp);
}

/// Writes the fixture. Ignored: run by hand on the build being pinned.
#[test]
#[ignore]
fn generate() {
    let out = fixture_dir();
    let tmp = std::env::temp_dir().join(format!("unv-golden-gen-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    let db = tmp.join("vault.db");
    std::fs::write(tmp.join("vault.salt"), SALT).unwrap();

    let key = derive_key(PW, &SALT).unwrap();
    println!("KEY_HEX={}", hex::encode(key));
    let conn = open_db(&db, &key).unwrap();
    vault_core::init_schema(&conn).unwrap();

    let v1 = save(
        &conn,
        json!({
            "api_keys": [
                { "id": "g-1", "provider": "Stripe", "api_key": "sk_test_golden_one", "project_ids": ["p-1"] },
                { "id": "g-2", "provider": "GitHub", "api_key": "ghp_golden_two" },
                { "id": "g-3", "provider": "Résumé ключ", "api_key": "unicode-golden-three" }
            ],
            "projects": [{
                "id": "p-1", "name": "homelab",
                "chunks": [
                    { "id": "c-1", "type": "env", "name": ".env", "content": "A=1\nB=2\n" },
                    { "id": "c-2", "type": "env", "name": "other.env", "content": "C=3\n" }
                ]
            }],
            "user_categories": []
        }),
        None,
    );
    let mut doc = vault_core::load_vault(&conn).unwrap().unwrap();
    doc["api_keys"][0]["api_key"] = json!("sk_test_golden_two");
    save(&conn, doc, Some(&v1));
    vault_core::record_event(&conn, "golden", "fixture", Some("manual row"), None).unwrap();

    conn.execute_batch("PRAGMA wal_checkpoint(TRUNCATE);")
        .unwrap();
    drop(conn);
    std::fs::create_dir_all(&out).unwrap();
    std::fs::copy(&db, out.join("vault.db")).unwrap();
    std::fs::copy(tmp.join("vault.salt"), out.join("vault.salt")).unwrap();
    let _ = std::fs::remove_dir_all(tmp);
}
