//! Config-file generation, ported from `src/ts/chunk-ops.ts` and
//! `src/ts/import-export.ts` for the four stable project types.
//!
//! Every value goes through [`crate::refs`] first: a `${…}` placeholder that
//! reaches a wg0.conf, a compose file or a `.env` is a broken deploy, not a
//! cosmetic bug.

use crate::refs::Resolver;
use serde_json::Value;

fn fields_of(chunk: &Value) -> Vec<Value> {
    chunk
        .get("fields")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default()
}

fn s<'a>(v: &'a Value, key: &str) -> &'a str {
    v.get(key).and_then(|x| x.as_str()).unwrap_or("")
}

fn chunks_of(project: &Value) -> Vec<Value> {
    project
        .get("chunks")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default()
        .into_iter()
        // A disabled chunk is greyed out in the UI and excluded from exports.
        .filter(|c| !c.get("disabled").and_then(|d| d.as_bool()).unwrap_or(false))
        .collect()
}

/// YAML scalar quoting, matching `yamlStr()` in chunk-ops.ts.
fn yaml_str(v: &str) -> String {
    if v.is_empty() {
        return "\"\"".into();
    }
    if v.chars()
        .any(|c| c.is_whitespace() || "':#[]{},|>&*!\"@`".contains(c))
    {
        return serde_json::to_string(v).unwrap_or_else(|_| format!("\"{v}\""));
    }
    v.to_string()
}

fn quote_item(v: &str) -> String {
    if v.chars().any(char::is_whitespace) {
        serde_json::to_string(v).unwrap_or_else(|_| format!("\"{v}\""))
    } else {
        v.to_string()
    }
}

fn split_items(raw: &str, newline_only: bool) -> Vec<String> {
    let parts: Vec<&str> = if newline_only {
        raw.split('\n').collect()
    } else {
        raw.split(['\n', ',']).collect()
    };
    parts
        .iter()
        .map(|p| p.trim().to_string())
        .filter(|p| !p.is_empty())
        .collect()
}

// ── WireGuard ─────────────────────────────────────────────────────────────────

pub fn export_wireguard(project: &Value, r: &Resolver) -> String {
    let mut sections: Vec<String> = Vec::new();
    for chunk in chunks_of(project) {
        let header = match s(&chunk, "chunk_type") {
            "wg_interface" => "[Interface]".to_string(),
            "wg_peer" => "[Peer]".to_string(),
            _ => format!("# {}", s(&chunk, "name")),
        };
        let mut lines = vec![header];
        for field in fields_of(&chunk) {
            let raw = s(&field, "value");
            if raw.is_empty() {
                continue;
            }
            let val = r.or_literal_secret(raw, crate::out::chunk_field_is_secret(&field));
            lines.push(format!("{} = {}", s(&field, "key"), val));
        }
        sections.push(lines.join("\n"));
    }
    sections.join("\n\n")
}

// ── Docker Compose ────────────────────────────────────────────────────────────

pub struct Compose {
    pub yaml: String,
    pub env_file: String,
}

pub fn export_docker_compose(project: &Value, r: &Resolver) -> Compose {
    let chunks = chunks_of(project);
    let by_type = |t: &str| -> Vec<Value> {
        chunks
            .iter()
            .filter(|c| s(c, "chunk_type") == t)
            .cloned()
            .collect()
    };
    let service_chunks = by_type("docker_service");
    let network_chunks = by_type("docker_network");
    let volume_chunks = by_type("docker_volume");

    let mut out: Vec<String> = vec!["# Generated by EnvVault".into(), String::new()];
    let mut env_lines: Vec<String> = Vec::new();

    if !network_chunks.is_empty() {
        out.push("networks:".into());
        for nc in &network_chunks {
            let fields = fields_of(nc);
            for f in &fields {
                let key = s(f, "key");
                if key.is_empty() {
                    continue;
                }
                out.push(format!("  {key}:"));
                let val = s(f, "value");
                if !val.is_empty() {
                    out.push(format!("    driver: {val}"));
                }
            }
            if fields.is_empty() {
                out.push(format!("  {}:", s(nc, "name")));
            }
        }
        out.push(String::new());
    }

    if !volume_chunks.is_empty() {
        out.push("volumes:".into());
        for vc in &volume_chunks {
            let fields = fields_of(vc);
            for f in &fields {
                let key = s(f, "key");
                if !key.is_empty() {
                    out.push(format!("  {key}:"));
                }
            }
            if fields.is_empty() {
                out.push(format!("  {}:", s(vc, "name")));
            }
        }
        out.push(String::new());
    }

    if !service_chunks.is_empty() {
        out.push("services:".into());
        for sc in &service_chunks {
            let svc_name = s(sc, "name")
                .split_whitespace()
                .collect::<Vec<_>>()
                .join("_")
                .to_lowercase();
            out.push(format!("  {svc_name}:"));

            let mut env_fields: Vec<Value> = Vec::new();
            let mut port_items: Vec<String> = Vec::new();
            let mut volume_items: Vec<String> = Vec::new();
            let mut list_map: Vec<(String, Vec<String>)> = Vec::new();
            let mut scalars: Vec<(String, String)> = Vec::new();

            for f in fields_of(sc) {
                let key = s(&f, "key").to_string();
                let ftype = s(&f, "field_type").to_string();
                let desc = s(&f, "description").to_string();
                let value = s(&f, "value").to_string();
                if key.is_empty() || key == "restart" {
                    continue;
                }
                if desc == "env" || ftype == "env_var" {
                    env_fields.push(f.clone());
                } else if key == "ports" || ftype == "port" {
                    port_items.extend(split_items(&value, false));
                } else if key == "volumes" || ftype == "volume_mount" {
                    volume_items.extend(split_items(&value, true));
                } else if key == "networks" || key == "depends_on" || ftype == "list" {
                    let items = split_items(&value, false);
                    match list_map.iter_mut().find(|(k, _)| *k == key) {
                        Some((_, v)) => v.extend(items),
                        None => list_map.push((key.clone(), items)),
                    }
                } else if !value.is_empty() {
                    scalars.push((key, value));
                }
            }

            const PRIO: [&str; 8] = [
                "image",
                "container_name",
                "user",
                "hostname",
                "network_mode",
                "pid",
                "entrypoint",
                "command",
            ];
            let mut remaining = scalars.clone();
            for k in PRIO {
                if let Some(pos) = remaining.iter().position(|(key, _)| key == k) {
                    let (key, val) = remaining.remove(pos);
                    out.push(format!("    {key}: {}", yaml_str(&val)));
                }
            }
            for (k, v) in &remaining {
                out.push(format!("    {k}: {}", yaml_str(v)));
            }

            if !port_items.is_empty() {
                out.push("    ports:".into());
                for p in &port_items {
                    out.push(format!(
                        "      - {}",
                        serde_json::to_string(p).unwrap_or_default()
                    ));
                }
            }

            if !env_fields.is_empty() {
                out.push("    environment:".into());
                for f in &env_fields {
                    let key = s(f, "key");
                    let raw = s(f, "value");
                    let has_ref = !s(f, "ref_name").is_empty()
                        || (raw.starts_with("${") && raw.ends_with('}') && raw.len() > 3);
                    if has_ref {
                        // Compose substitutes ${NAME} from the .env beside it, and
                        // NAME must be a valid shell identifier — `Provider/field`
                        // is not one, so derive the variable name from the key.
                        let var_name: String = key
                            .to_uppercase()
                            .chars()
                            .map(|c| {
                                if c.is_ascii_alphanumeric() || c == '_' {
                                    c
                                } else {
                                    '_'
                                }
                            })
                            .collect();
                        out.push(format!("      - {key}=${{{var_name}}}"));
                        // The .env beside a compose file is pure secret
                        // material, so it is masked like any other value that
                        // came out of the vault.
                        let resolved = r.or_literal_secret(raw, true);
                        env_lines.push(format!("{var_name}={resolved}"));
                    } else {
                        out.push(format!("      - {key}={raw}"));
                    }
                }
            }

            if !volume_items.is_empty() {
                out.push("    volumes:".into());
                for v in &volume_items {
                    out.push(format!("      - {}", quote_item(v)));
                }
            }

            for (k, items) in &list_map {
                out.push(format!("    {k}:"));
                for item in items {
                    out.push(format!("      - {}", yaml_str(item)));
                }
            }

            let restart = fields_of(sc)
                .iter()
                .find(|f| s(f, "key") == "restart")
                .map(|f| s(f, "value").to_string())
                .filter(|v| !v.is_empty())
                .unwrap_or_else(|| "unless-stopped".into());
            out.push(format!("    restart: {restart}"));
            out.push(String::new());
        }
    }

    Compose {
        yaml: out.join("\n"),
        env_file: env_lines.join("\n"),
    }
}

// ── nginx ─────────────────────────────────────────────────────────────────────

pub fn export_nginx(project: &Value, r: &Resolver) -> String {
    let chunks = chunks_of(project);
    let of_type = |t: &str| -> Vec<Value> {
        chunks
            .iter()
            .filter(|c| s(c, "chunk_type") == t)
            .cloned()
            .collect()
    };
    let upstreams = of_type("nginx_upstream");
    let servers = of_type("nginx_server");
    let locations = of_type("nginx_location");

    let mut lines: Vec<String> = vec!["# Generated by EnvVault".into(), String::new()];

    for u in &upstreams {
        lines.push(format!("upstream {} {{", s(u, "name")));
        for f in fields_of(u) {
            let raw = s(&f, "value");
            if raw.is_empty() {
                continue;
            }
            let val = r.or_literal(raw);
            if s(&f, "key") == "server" {
                for v in split_items(&val, false) {
                    lines.push(format!("    server {v};"));
                }
            } else {
                lines.push(format!("    {} {val};", s(&f, "key")));
            }
        }
        lines.push("}".into());
        lines.push(String::new());
    }

    for sv in &servers {
        lines.push("server {".into());
        for f in fields_of(sv) {
            let raw = s(&f, "value");
            if raw.is_empty() {
                continue;
            }
            let val = r.or_literal_secret(raw, crate::out::chunk_field_is_secret(&f));
            lines.push(format!("    {} {val};", s(&f, "key")));
        }
        if !locations.is_empty() {
            lines.push(String::new());
            for loc in &locations {
                let path = fields_of(loc)
                    .iter()
                    .find(|f| s(f, "key") == "path")
                    .map(|f| s(f, "value").to_string())
                    .filter(|p| !p.is_empty())
                    .unwrap_or_else(|| "/".into());
                lines.push(format!("    location {path} {{"));
                for f in fields_of(loc) {
                    if s(&f, "key") == "path" {
                        continue;
                    }
                    let raw = s(&f, "value");
                    if raw.is_empty() {
                        continue;
                    }
                    let val = r.or_literal_secret(raw, crate::out::chunk_field_is_secret(&f));
                    lines.push(format!("        {} {val};", s(&f, "key")));
                }
                lines.push("    }".into());
            }
        }
        lines.push("}".into());
        lines.push(String::new());
    }
    lines.join("\n")
}

// ── .env from a project's env_file chunks ─────────────────────────────────────

pub struct EnvOut {
    pub text: String,
    pub unresolved: Vec<String>,
    pub had_chunks: bool,
}

pub fn export_project_env(project: &Value, r: &Resolver) -> EnvOut {
    let mut out: Vec<String> = Vec::new();
    let mut unresolved: Vec<String> = Vec::new();
    let mut had_chunks = false;

    for chunk in chunks_of(project) {
        if s(&chunk, "chunk_type") != "env_file" {
            continue;
        }
        had_chunks = true;
        let name = match s(&chunk, "name") {
            "" => "env",
            n => n,
        };
        out.push(format!("# {name}"));
        for f in fields_of(&chunk) {
            let key = s(&f, "key");
            if key.is_empty() {
                continue;
            }
            let raw = s(&f, "value");
            // Every line of a .env is secret material by construction, so the
            // literal values are masked too, not only the resolved references.
            let val = if r.resolve(raw).unresolved {
                unresolved.push(raw.to_string());
                raw.to_string()
            } else {
                r.or_literal_secret(raw, true)
            };
            out.push(format!("{key}={val}"));
        }
        out.push(String::new());
    }
    EnvOut {
        text: out.join("\n"),
        unresolved,
        had_chunks,
    }
}

// ── The seven types that used to export from the desktop app only ─────────────
//
// These were TypeScript-only until now, and `chunks::export` quietly fell back
// to `.env` for every one of them: `envv project export my-lb` on an haproxy
// project wrote a file that was not `haproxy.cfg`, or failed with "has no
// env_file chunks" — a diagnosis naming neither the cause nor the fix.
//
// They are ported here rather than fenced off because the golden fixtures for
// all seven already existed and were asserted from TypeScript alone, so the
// "two implementations, one golden file" guarantee — the thing that found two
// live export bugs the first time it ran — covered 4 of 11 formats. It now
// covers 11 of 11.
//
// Where the TypeScript looks inconsistent, this matches it rather than
// improving it. `export_k8s` resolving references only inside `k8s_secret` is
// the clearest case: the fixture is the contract, both halves must agree, and a
// unilateral fix here would break parity in the direction that is hardest to
// notice. Fix it in `chunk-ops.ts`, regenerate, and both sides move together.

/// `xv()` from chunk-ops.ts: resolve a `${…}`, fall back to the literal.
///
/// Six of the seven exporters interpolated the raw field value, so a
/// `${Provider/field}` reached the generated config as literal text — a
/// `.pgpass` line whose password is the string `${DB/password}`. That is
/// invariant 5, and it is the same bug a fixture caught in `export_nginx` in
/// Phase 13.
fn xv(r: &Resolver, raw: &str) -> String {
    if raw.is_empty() {
        return String::new();
    }
    r.or_literal(raw)
}

/// Field lookup by key, resolved. Empty when absent — matching
/// `chunk.fields.find(f => f.key === k)?.value` followed by `xv`.
fn xfield(r: &Resolver, chunk: &Value, key: &str) -> String {
    fields_of(chunk)
        .iter()
        .find(|f| s(f, "key") == key)
        .map(|f| xv(r, s(f, "value")))
        .unwrap_or_default()
}

/// Raw field lookup, no reference resolution. Only for the places the
/// TypeScript also reads `f.value` directly — see the note above.
fn rawfield(chunk: &Value, key: &str) -> String {
    fields_of(chunk)
        .iter()
        .find(|f| s(f, "key") == key)
        .map(|f| s(f, "value").to_string())
        .unwrap_or_default()
}

/// `JSON.stringify` of a string, which is what the YAML emitters use for any
/// value that must survive round-tripping.
fn json_str(v: &str) -> String {
    serde_json::to_string(v).unwrap_or_else(|_| format!("\"{v}\""))
}

fn of_type(chunks: &[Value], t: &str) -> Vec<Value> {
    chunks
        .iter()
        .filter(|c| s(c, "chunk_type") == t)
        .cloned()
        .collect()
}

// ── Apache ────────────────────────────────────────────────────────────────────

pub fn export_apache(project: &Value, r: &Resolver) -> String {
    let mut lines: Vec<String> = vec!["# Generated by EnvVault".into(), String::new()];
    for chunk in chunks_of(project) {
        match s(&chunk, "chunk_type") {
            "apache_vhost" => {
                // A vhost carrying SSLEngine is the :443 one. Cheap heuristic,
                // and it is what the app does.
                let port = if fields_of(&chunk).iter().any(|f| s(f, "key") == "SSLEngine") {
                    "443"
                } else {
                    "80"
                };
                lines.push(format!("<VirtualHost *:{port}>"));
                for f in fields_of(&chunk) {
                    let raw = s(&f, "value");
                    if raw.is_empty() {
                        continue;
                    }
                    lines.push(format!("    {} {}", s(&f, "key"), xv(r, raw)));
                }
                lines.push("</VirtualHost>".into());
                lines.push(String::new());
            }
            "apache_directory" => {
                let path = match xfield(r, &chunk, "path") {
                    p if p.is_empty() => "/".to_string(),
                    p => p,
                };
                lines.push(format!("<Directory {path}>"));
                for f in fields_of(&chunk) {
                    let raw = s(&f, "value");
                    if s(&f, "key") == "path" || raw.is_empty() {
                        continue;
                    }
                    lines.push(format!("    {} {}", s(&f, "key"), xv(r, raw)));
                }
                lines.push("</Directory>".into());
                lines.push(String::new());
            }
            _ => {}
        }
    }
    lines.join("\n")
}

// ── HAProxy ───────────────────────────────────────────────────────────────────

pub fn export_haproxy(project: &Value, r: &Resolver) -> String {
    let mut lines: Vec<String> = vec!["# Generated by EnvVault".into(), String::new()];
    for chunk in chunks_of(project) {
        let header = match s(&chunk, "chunk_type") {
            "haproxy_global" => "global".to_string(),
            "haproxy_frontend" => format!("frontend {}", s(&chunk, "name")),
            "haproxy_backend" => format!("backend {}", s(&chunk, "name")),
            _ => continue,
        };
        lines.push(header);
        for f in fields_of(&chunk) {
            let raw = s(&f, "value");
            if raw.is_empty() {
                continue;
            }
            lines.push(format!("    {} {}", s(&f, "key"), xv(r, raw)));
        }
        lines.push(String::new());
    }
    lines.join("\n")
}

// ── Ansible ───────────────────────────────────────────────────────────────────

pub fn export_ansible(project: &Value, r: &Resolver) -> String {
    let chunks = chunks_of(project);
    let var_chunks = of_type(&chunks, "ansible_vars");
    let task_chunks = of_type(&chunks, "ansible_task");

    let var_lines = |indent: &str| -> Vec<String> {
        let mut out = Vec::new();
        for chunk in &var_chunks {
            out.push(format!("{indent}# {}", s(chunk, "name")));
            for f in fields_of(chunk) {
                let key = s(&f, "key");
                if key.is_empty() {
                    continue;
                }
                out.push(format!(
                    "{indent}{key}: {}",
                    json_str(&xv(r, s(&f, "value")))
                ));
            }
        }
        out
    };

    let task_lines = |indent: &str| -> Vec<String> {
        let mut out = Vec::new();
        for chunk in &task_chunks {
            let name = match xfield(r, chunk, "name") {
                n if n.is_empty() => s(chunk, "name").to_string(),
                n => n,
            };
            let module = match xfield(r, chunk, "module") {
                m if m.is_empty() => "debug".to_string(),
                m => m,
            };
            out.push(format!("{indent}- name: {name}"));
            out.push(format!("{indent}  {module}:"));
            for f in fields_of(chunk) {
                let key = s(&f, "key");
                if key == "name" || key == "module" || key.is_empty() {
                    continue;
                }
                out.push(format!(
                    "{indent}    {key}: {}",
                    json_str(&xv(r, s(&f, "value")))
                ));
            }
        }
        out
    };

    // Vars and tasks in one document produced a mapping immediately followed by
    // a sequence, which no YAML parser accepts — so the output was unusable by
    // the tool it targets. The shape follows how Ansible actually consumes these
    // files: tasks present → a playbook with vars folded into the play; vars
    // only → a bare mapping, which is what group_vars/host_vars want.
    if !task_chunks.is_empty() {
        let mut lines: Vec<String> = vec!["# Generated by EnvVault".into(), "- hosts: all".into()];
        if !var_chunks.is_empty() {
            lines.push("  vars:".into());
            lines.extend(var_lines("    "));
        }
        lines.push("  tasks:".into());
        lines.extend(task_lines("    "));
        return lines.join("\n");
    }

    let mut lines: Vec<String> = vec!["# Generated by EnvVault".into()];
    if !var_chunks.is_empty() {
        lines.extend(var_lines(""));
    }
    lines.join("\n")
}

// ── PostgreSQL (.pgpass) ──────────────────────────────────────────────────────

pub fn export_postgres(project: &Value, r: &Resolver) -> String {
    let mut lines: Vec<String> =
        vec!["# Generated by EnvVault — .pgpass format: host:port:dbname:user:password".into()];
    for chunk in chunks_of(project) {
        if s(&chunk, "chunk_type") != "pg_connection" {
            continue;
        }
        let g = |k: &str| xfield(r, &chunk, k);
        let port = match g("port") {
            p if p.is_empty() => "5432".to_string(),
            p => p,
        };
        lines.push(format!(
            "{}:{}:{}:{}:{}",
            g("host"),
            port,
            g("dbname"),
            g("user"),
            g("password")
        ));
    }
    lines.join("\n")
}

// ── Kubernetes ────────────────────────────────────────────────────────────────

/// UTF-8 → standard base64, for `Secret.data`.
///
/// The TypeScript twin has to go the long way round (`TextEncoder`, then chunked
/// `String.fromCharCode`, then `btoa`) because `btoa` is Latin-1 and blows the
/// stack past ~100 KB. Here it is one call — but the *output* must be identical,
/// which is what the k8s golden pins.
fn b64_utf8(v: &str) -> String {
    use base64::Engine;
    base64::engine::general_purpose::STANDARD.encode(v.as_bytes())
}

pub fn export_k8s(project: &Value, r: &Resolver) -> String {
    let mut manifests: Vec<String> = Vec::new();
    for chunk in chunks_of(project) {
        let name = match rawfield(&chunk, "name") {
            n if n.is_empty() => s(&chunk, "name").to_string(),
            n => n,
        };
        let ns = match rawfield(&chunk, "namespace") {
            n if n.is_empty() => "default".to_string(),
            n => n,
        };
        let or = |k: &str, d: &str| -> String {
            match rawfield(&chunk, k) {
                v if v.is_empty() => d.to_string(),
                v => v,
            }
        };
        match s(&chunk, "chunk_type") {
            "k8s_deployment" => {
                let image = or("image", "nginx:latest");
                let replicas = or("replicas", "1");
                let port = or("containerPort", "80");
                let env_fields: Vec<Value> = fields_of(&chunk)
                    .into_iter()
                    .filter(|f| matches!(s(f, "field_type"), "env_var" | "secret"))
                    .collect();
                let env_block = if env_fields.is_empty() {
                    String::new()
                } else {
                    let mut b = String::from("\n        env:");
                    for f in &env_fields {
                        b.push_str(&format!(
                            "\n          - name: {}\n            value: {}",
                            s(f, "key"),
                            json_str(s(f, "value"))
                        ));
                    }
                    b
                };
                manifests.push(format!(
                    "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {name}\n  namespace: {ns}\nspec:\n  replicas: {replicas}\n  selector:\n    matchLabels:\n      app: {name}\n  template:\n    metadata:\n      labels:\n        app: {name}\n    spec:\n      containers:\n        - name: {name}\n          image: {image}\n          ports:\n            - containerPort: {port}{env_block}"
                ));
            }
            "k8s_service" => {
                let port = or("port", "80");
                let target_port = or("targetPort", "80");
                let ty = or("type", "ClusterIP");
                manifests.push(format!(
                    "apiVersion: v1\nkind: Service\nmetadata:\n  name: {name}\n  namespace: {ns}\nspec:\n  selector:\n    app: {name}\n  type: {ty}\n  ports:\n    - port: {port}\n      targetPort: {target_port}"
                ));
            }
            "k8s_configmap" => {
                let data: Vec<String> = fields_of(&chunk)
                    .iter()
                    .filter(|f| s(f, "key") != "name" && s(f, "key") != "namespace")
                    .map(|f| format!("  {}: {}", s(f, "key"), json_str(s(f, "value"))))
                    .collect();
                manifests.push(format!(
                    "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: {name}\n  namespace: {ns}\ndata:\n{}",
                    data.join("\n")
                ));
            }
            "k8s_secret" => {
                // References are resolved *before* encoding. A field holding
                // `${DB_PASSWORD}` was base64'd literally, shipping the
                // placeholder text to the cluster as if it were the secret.
                let data: Vec<String> = fields_of(&chunk)
                    .iter()
                    .filter(|f| s(f, "key") != "name" && s(f, "key") != "namespace")
                    .map(|f| format!("  {}: {}", s(f, "key"), b64_utf8(&xv(r, s(f, "value")))))
                    .collect();
                manifests.push(format!(
                    "apiVersion: v1\nkind: Secret\nmetadata:\n  name: {name}\n  namespace: {ns}\ntype: Opaque\ndata:\n{}",
                    data.join("\n")
                ));
            }
            "k8s_ingress" => {
                let host = or("host", "example.com");
                let svc_name = match rawfield(&chunk, "serviceName") {
                    v if v.is_empty() => name.clone(),
                    v => v,
                };
                let svc_port = or("servicePort", "80");
                manifests.push(format!(
                    "apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: {name}\n  namespace: {ns}\nspec:\n  rules:\n    - host: {host}\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service:\n                name: {svc_name}\n                port:\n                  number: {svc_port}"
                ));
            }
            _ => {}
        }
    }
    manifests.join("\n---\n")
}

// ── SSH client config ─────────────────────────────────────────────────────────

pub fn export_ssh_config(project: &Value, r: &Resolver) -> String {
    let mut lines: Vec<String> = vec!["# Generated by EnvVault".into(), String::new()];
    for chunk in chunks_of(project) {
        if s(&chunk, "chunk_type") != "ssh_host" {
            continue;
        }
        lines.push(format!("Host {}", s(&chunk, "name")));
        for f in fields_of(&chunk) {
            let raw = s(&f, "value");
            if raw.is_empty() {
                continue;
            }
            lines.push(format!("    {} {}", s(&f, "key"), xv(r, raw)));
        }
        lines.push(String::new());
    }
    lines.join("\n")
}

// ── Traefik (dynamic configuration) ───────────────────────────────────────────

pub fn export_traefik(project: &Value, r: &Resolver) -> String {
    let chunks = chunks_of(project);
    let routers = of_type(&chunks, "traefik_router");
    let services = of_type(&chunks, "traefik_service");
    let middlewares = of_type(&chunks, "traefik_middleware");
    let mut lines: Vec<String> = vec!["# Generated by EnvVault".into(), "http:".into()];

    if !routers.is_empty() {
        lines.push("  routers:".into());
        for rt in &routers {
            lines.push(format!("    {}:", s(rt, "name")));
            for f in fields_of(rt) {
                let raw = s(&f, "value");
                if raw.is_empty() {
                    continue;
                }
                if s(&f, "field_type") == "list" {
                    lines.push(format!("      {}:", s(&f, "key")));
                    for item in split_items(&xv(r, raw), false) {
                        lines.push(format!("        - {item}"));
                    }
                } else {
                    lines.push(format!("      {}: {}", s(&f, "key"), json_str(&xv(r, raw))));
                }
            }
        }
    }
    if !services.is_empty() {
        lines.push("  services:".into());
        for sv in &services {
            let url = xfield(r, sv, "url");
            let pass_host = match xfield(r, sv, "passHostHeader") {
                p if p.is_empty() => "true".to_string(),
                p => p,
            };
            lines.push(format!("    {}:", s(sv, "name")));
            lines.push("      loadBalancer:".into());
            lines.push(format!("        passHostHeader: {pass_host}"));
            if !url.is_empty() {
                lines.push("        servers:".into());
                lines.push(format!("          - url: {}", json_str(&url)));
            }
        }
    }
    if !middlewares.is_empty() {
        lines.push("  middlewares:".into());
        for m in &middlewares {
            let ty = xfield(r, m, "type");
            lines.push(format!("    {}:", s(m, "name")));
            if !ty.is_empty() {
                lines.push(format!("      {ty}:"));
                for f in fields_of(m) {
                    let raw = s(&f, "value");
                    if s(&f, "key") == "type" || raw.is_empty() {
                        continue;
                    }
                    lines.push(format!("        {}: {}", s(&f, "key"), xv(r, raw)));
                }
            }
        }
    }
    lines.join("\n")
}

// ── Single chunk → its native config text ─────────────────────────────────────

pub fn chunk_to_string(chunk: &Value, r: &Resolver) -> String {
    let ctype = s(chunk, "chunk_type");
    let is_env_file = ctype == "env_file";
    let rv = |raw: &str, field: &Value| {
        r.or_literal_secret(raw, is_env_file || crate::out::chunk_field_is_secret(field))
    };

    match ctype {
        "wg_interface" | "wg_peer" => {
            let header = if ctype == "wg_interface" {
                "[Interface]"
            } else {
                "[Peer]"
            };
            let mut lines = vec![header.to_string()];
            for f in fields_of(chunk) {
                lines.push(format!("{} = {}", s(&f, "key"), rv(s(&f, "value"), &f)));
            }
            lines.join("\n")
        }
        "env_file" => fields_of(chunk)
            .iter()
            .filter(|f| !s(f, "key").is_empty())
            .map(|f| format!("{}={}", s(f, "key"), rv(s(f, "value"), f)))
            .collect::<Vec<_>>()
            .join("\n"),
        "nginx_key" => fields_of(chunk)
            .iter()
            .find(|f| s(f, "key") == "content")
            .map(|f| s(f, "value").to_string())
            .unwrap_or_default(),
        "nginx_server" | "nginx_location" | "nginx_upstream" => {
            let block_type = match ctype {
                "nginx_location" => "location",
                "nginx_upstream" => "upstream",
                _ => "server",
            };
            let block_name = match ctype {
                "nginx_location" => fields_of(chunk)
                    .iter()
                    .find(|f| s(f, "key") == "path")
                    .map(|f| s(f, "value").to_string())
                    .filter(|p| !p.is_empty())
                    .map(|p| format!(" {p}"))
                    .unwrap_or_default(),
                "nginx_upstream" => {
                    let n = s(chunk, "name");
                    if n.is_empty() {
                        String::new()
                    } else {
                        format!(" {n}")
                    }
                }
                _ => String::new(),
            };
            let inner = fields_of(chunk)
                .iter()
                .filter(|f| {
                    !s(f, "key").is_empty() && s(f, "key") != "path" && !s(f, "value").is_empty()
                })
                .map(|f| format!("    {} {};", s(f, "key"), rv(s(f, "value"), f)))
                .collect::<Vec<_>>()
                .join("\n");
            format!("{block_type}{block_name} {{\n{inner}\n}}")
        }
        "ssh_host" => {
            let mut lines = vec![format!("Host {}", s(chunk, "name"))];
            for f in fields_of(chunk) {
                if !s(&f, "key").is_empty() && !s(&f, "value").is_empty() {
                    lines.push(format!("    {} {}", s(&f, "key"), rv(s(&f, "value"), &f)));
                }
            }
            lines.join("\n")
        }
        "docker_service" => service_chunk_to_yaml(chunk),
        _ => fields_of(chunk)
            .iter()
            .filter(|f| !s(f, "key").is_empty())
            .map(|f| format!("{}: {}", s(f, "key"), s(f, "value")))
            .collect::<Vec<_>>()
            .join("\n"),
    }
}

fn service_chunk_to_yaml(sc: &Value) -> String {
    let svc_name = s(sc, "name")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join("_")
        .to_lowercase();
    let mut out = vec![format!("{svc_name}:")];

    let mut env_fields: Vec<Value> = Vec::new();
    let mut port_items: Vec<String> = Vec::new();
    let mut volume_items: Vec<String> = Vec::new();
    let mut list_map: Vec<(String, Vec<String>)> = Vec::new();
    let mut scalars: Vec<(String, String)> = Vec::new();

    for f in fields_of(sc) {
        let key = s(&f, "key").to_string();
        let ftype = s(&f, "field_type").to_string();
        let desc = s(&f, "description").to_string();
        let value = s(&f, "value").to_string();
        if key.is_empty() || key == "restart" {
            continue;
        }
        if desc == "env" || ftype == "env_var" {
            env_fields.push(f.clone());
        } else if key == "ports" || ftype == "port" {
            port_items.extend(split_items(&value, false));
        } else if key == "volumes" || ftype == "volume_mount" {
            volume_items.extend(split_items(&value, true));
        } else if key == "networks" || key == "depends_on" || ftype == "list" {
            let items = split_items(&value, false);
            match list_map.iter_mut().find(|(k, _)| *k == key) {
                Some((_, v)) => v.extend(items),
                None => list_map.push((key.clone(), items)),
            }
        } else if !value.is_empty() {
            scalars.push((key, value));
        }
    }

    const PRIO: [&str; 8] = [
        "image",
        "container_name",
        "user",
        "hostname",
        "network_mode",
        "pid",
        "entrypoint",
        "command",
    ];
    let mut remaining = scalars;
    for k in PRIO {
        if let Some(pos) = remaining.iter().position(|(key, _)| key == k) {
            let (key, val) = remaining.remove(pos);
            out.push(format!("  {key}: {}", yaml_str(&val)));
        }
    }
    for (k, v) in &remaining {
        out.push(format!("  {k}: {}", yaml_str(v)));
    }
    if !port_items.is_empty() {
        out.push("  ports:".into());
        for p in &port_items {
            out.push(format!(
                "    - {}",
                serde_json::to_string(p).unwrap_or_default()
            ));
        }
    }
    if !env_fields.is_empty() {
        out.push("  environment:".into());
        for f in &env_fields {
            let raw = s(f, "value");
            let ref_name = if !s(f, "ref_name").is_empty() {
                Some(s(f, "ref_name").to_string())
            } else if raw.starts_with("${") && raw.ends_with('}') && raw.len() > 3 {
                Some(raw[2..raw.len() - 1].to_string())
            } else {
                None
            };
            match ref_name {
                Some(r) => out.push(format!("    - {}=${{{r}}}", s(f, "key"))),
                None => out.push(format!("    - {}={raw}", s(f, "key"))),
            }
        }
    }
    if !volume_items.is_empty() {
        out.push("  volumes:".into());
        for v in &volume_items {
            out.push(format!("    - {}", quote_item(v)));
        }
    }
    for (k, items) in &list_map {
        out.push(format!("  {k}:"));
        for item in items {
            out.push(format!("    - {}", yaml_str(item)));
        }
    }
    let restart = fields_of(sc)
        .iter()
        .find(|f| s(f, "key") == "restart")
        .map(|f| s(f, "value").to_string())
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| "unless-stopped".into());
    out.push(format!("  restart: {restart}"));
    out.join("\n")
}

// ── Vault-level export formats ────────────────────────────────────────────────

pub fn dotenv(entries: &[Value]) -> String {
    entries
        .iter()
        .map(|e| {
            let p = crate::data::env_key(s(e, "provider"));
            format!("{p}={}", s(e, "api_key"))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn yaml(entries: &[Value]) -> String {
    let mut out = String::from("# EnvVault Export\n");
    for e in entries {
        let p = crate::data::env_key(s(e, "provider"));
        out.push_str(&format!(
            "{p}: {}\n",
            serde_json::to_string(s(e, "api_key")).unwrap_or_default()
        ));
    }
    out
}

/// Kubernetes Secret manifest (stringData — values kept readable, not base64).
pub fn k8s_secret(entries: &[Value], name: &str) -> String {
    let mut lines = vec![
        "apiVersion: v1".to_string(),
        "kind: Secret".to_string(),
        "metadata:".to_string(),
        format!("  name: {name}"),
        "type: Opaque".to_string(),
        "stringData:".to_string(),
    ];
    for e in entries {
        lines.push(format!(
            "  {}: {}",
            crate::data::env_key(s(e, "provider")),
            serde_json::to_string(s(e, "api_key")).unwrap_or_default()
        ));
    }
    lines.join("\n")
}

/// Terraform .tfvars — `variable = "value"` pairs.
pub fn tfvars(entries: &[Value]) -> String {
    entries
        .iter()
        .map(|e| {
            format!(
                "{} = {}",
                crate::data::env_key(s(e, "provider")).to_lowercase(),
                serde_json::to_string(s(e, "api_key")).unwrap_or_default()
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}
