//! Config-file generation, ported from `src/ts/chunk-ops.ts` and
//! `src/ts/import-export.ts` for the four stable project types.
//!
//! Every value goes through [`crate::refs`] first: a `${…}` placeholder that
//! reaches a wg0.conf, a compose file or a `.env` is a broken deploy, not a
//! cosmetic bug.

use crate::refs::Resolver;
use serde_json::Value;

fn fields_of(chunk: &Value) -> Vec<Value> {
    chunk
        .get("fields")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default()
}

fn s<'a>(v: &'a Value, key: &str) -> &'a str {
    v.get(key).and_then(|x| x.as_str()).unwrap_or("")
}

fn chunks_of(project: &Value) -> Vec<Value> {
    project
        .get("chunks")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default()
        .into_iter()
        // A disabled chunk is greyed out in the UI and excluded from exports.
        .filter(|c| !c.get("disabled").and_then(|d| d.as_bool()).unwrap_or(false))
        .collect()
}

/// YAML scalar quoting, matching `yamlStr()` in chunk-ops.ts.
fn yaml_str(v: &str) -> String {
    if v.is_empty() {
        return "\"\"".into();
    }
    if v.chars()
        .any(|c| c.is_whitespace() || "':#[]{},|>&*!\"@`".contains(c))
    {
        return serde_json::to_string(v).unwrap_or_else(|_| format!("\"{v}\""));
    }
    v.to_string()
}

fn quote_item(v: &str) -> String {
    if v.chars().any(char::is_whitespace) {
        serde_json::to_string(v).unwrap_or_else(|_| format!("\"{v}\""))
    } else {
        v.to_string()
    }
}

fn split_items(raw: &str, newline_only: bool) -> Vec<String> {
    let parts: Vec<&str> = if newline_only {
        raw.split('\n').collect()
    } else {
        raw.split(['\n', ',']).collect()
    };
    parts
        .iter()
        .map(|p| p.trim().to_string())
        .filter(|p| !p.is_empty())
        .collect()
}

// ── WireGuard ─────────────────────────────────────────────────────────────────

pub fn export_wireguard(project: &Value, r: &Resolver) -> String {
    let mut sections: Vec<String> = Vec::new();
    for chunk in chunks_of(project) {
        let header = match s(&chunk, "chunk_type") {
            "wg_interface" => "[Interface]".to_string(),
            "wg_peer" => "[Peer]".to_string(),
            _ => format!("# {}", s(&chunk, "name")),
        };
        let mut lines = vec![header];
        for field in fields_of(&chunk) {
            let raw = s(&field, "value");
            if raw.is_empty() {
                continue;
            }
            let val = r.or_literal_secret(raw, crate::out::chunk_field_is_secret(&field));
            lines.push(format!("{} = {}", s(&field, "key"), val));
        }
        sections.push(lines.join("\n"));
    }
    sections.join("\n\n")
}

// ── Docker Compose ────────────────────────────────────────────────────────────

pub struct Compose {
    pub yaml: String,
    pub env_file: String,
}

pub fn export_docker_compose(project: &Value, r: &Resolver) -> Compose {
    let chunks = chunks_of(project);
    let by_type = |t: &str| -> Vec<Value> {
        chunks
            .iter()
            .filter(|c| s(c, "chunk_type") == t)
            .cloned()
            .collect()
    };
    let service_chunks = by_type("docker_service");
    let network_chunks = by_type("docker_network");
    let volume_chunks = by_type("docker_volume");

    let mut out: Vec<String> = vec!["# Generated by EnvVault".into(), String::new()];
    let mut env_lines: Vec<String> = Vec::new();

    if !network_chunks.is_empty() {
        out.push("networks:".into());
        for nc in &network_chunks {
            let fields = fields_of(nc);
            for f in &fields {
                let key = s(f, "key");
                if key.is_empty() {
                    continue;
                }
                out.push(format!("  {key}:"));
                let val = s(f, "value");
                if !val.is_empty() {
                    out.push(format!("    driver: {val}"));
                }
            }
            if fields.is_empty() {
                out.push(format!("  {}:", s(nc, "name")));
            }
        }
        out.push(String::new());
    }

    if !volume_chunks.is_empty() {
        out.push("volumes:".into());
        for vc in &volume_chunks {
            let fields = fields_of(vc);
            for f in &fields {
                let key = s(f, "key");
                if !key.is_empty() {
                    out.push(format!("  {key}:"));
                }
            }
            if fields.is_empty() {
                out.push(format!("  {}:", s(vc, "name")));
            }
        }
        out.push(String::new());
    }

    if !service_chunks.is_empty() {
        out.push("services:".into());
        for sc in &service_chunks {
            let svc_name = s(sc, "name")
                .split_whitespace()
                .collect::<Vec<_>>()
                .join("_")
                .to_lowercase();
            out.push(format!("  {svc_name}:"));

            let mut env_fields: Vec<Value> = Vec::new();
            let mut port_items: Vec<String> = Vec::new();
            let mut volume_items: Vec<String> = Vec::new();
            let mut list_map: Vec<(String, Vec<String>)> = Vec::new();
            let mut scalars: Vec<(String, String)> = Vec::new();

            for f in fields_of(sc) {
                let key = s(&f, "key").to_string();
                let ftype = s(&f, "field_type").to_string();
                let desc = s(&f, "description").to_string();
                let value = s(&f, "value").to_string();
                if key.is_empty() || key == "restart" {
                    continue;
                }
                if desc == "env" || ftype == "env_var" {
                    env_fields.push(f.clone());
                } else if key == "ports" || ftype == "port" {
                    port_items.extend(split_items(&value, false));
                } else if key == "volumes" || ftype == "volume_mount" {
                    volume_items.extend(split_items(&value, true));
                } else if key == "networks" || key == "depends_on" || ftype == "list" {
                    let items = split_items(&value, false);
                    match list_map.iter_mut().find(|(k, _)| *k == key) {
                        Some((_, v)) => v.extend(items),
                        None => list_map.push((key.clone(), items)),
                    }
                } else if !value.is_empty() {
                    scalars.push((key, value));
                }
            }

            const PRIO: [&str; 8] = [
                "image",
                "container_name",
                "user",
                "hostname",
                "network_mode",
                "pid",
                "entrypoint",
                "command",
            ];
            let mut remaining = scalars.clone();
            for k in PRIO {
                if let Some(pos) = remaining.iter().position(|(key, _)| key == k) {
                    let (key, val) = remaining.remove(pos);
                    out.push(format!("    {key}: {}", yaml_str(&val)));
                }
            }
            for (k, v) in &remaining {
                out.push(format!("    {k}: {}", yaml_str(v)));
            }

            if !port_items.is_empty() {
                out.push("    ports:".into());
                for p in &port_items {
                    out.push(format!(
                        "      - {}",
                        serde_json::to_string(p).unwrap_or_default()
                    ));
                }
            }

            if !env_fields.is_empty() {
                out.push("    environment:".into());
                for f in &env_fields {
                    let key = s(f, "key");
                    let raw = s(f, "value");
                    let has_ref = !s(f, "ref_name").is_empty()
                        || (raw.starts_with("${") && raw.ends_with('}') && raw.len() > 3);
                    if has_ref {
                        // Compose substitutes ${NAME} from the .env beside it, and
                        // NAME must be a valid shell identifier — `Provider/field`
                        // is not one, so derive the variable name from the key.
                        let var_name: String = key
                            .to_uppercase()
                            .chars()
                            .map(|c| {
                                if c.is_ascii_alphanumeric() || c == '_' {
                                    c
                                } else {
                                    '_'
                                }
                            })
                            .collect();
                        out.push(format!("      - {key}=${{{var_name}}}"));
                        // The .env beside a compose file is pure secret
                        // material, so it is masked like any other value that
                        // came out of the vault.
                        let resolved = r.or_literal_secret(raw, true);
                        env_lines.push(format!("{var_name}={resolved}"));
                    } else {
                        out.push(format!("      - {key}={raw}"));
                    }
                }
            }

            if !volume_items.is_empty() {
                out.push("    volumes:".into());
                for v in &volume_items {
                    out.push(format!("      - {}", quote_item(v)));
                }
            }

            for (k, items) in &list_map {
                out.push(format!("    {k}:"));
                for item in items {
                    out.push(format!("      - {}", yaml_str(item)));
                }
            }

            let restart = fields_of(sc)
                .iter()
                .find(|f| s(f, "key") == "restart")
                .map(|f| s(f, "value").to_string())
                .filter(|v| !v.is_empty())
                .unwrap_or_else(|| "unless-stopped".into());
            out.push(format!("    restart: {restart}"));
            out.push(String::new());
        }
    }

    Compose {
        yaml: out.join("\n"),
        env_file: env_lines.join("\n"),
    }
}

// ── nginx ─────────────────────────────────────────────────────────────────────

pub fn export_nginx(project: &Value, r: &Resolver) -> String {
    let chunks = chunks_of(project);
    let of_type = |t: &str| -> Vec<Value> {
        chunks
            .iter()
            .filter(|c| s(c, "chunk_type") == t)
            .cloned()
            .collect()
    };
    let upstreams = of_type("nginx_upstream");
    let servers = of_type("nginx_server");
    let locations = of_type("nginx_location");

    let mut lines: Vec<String> = vec!["# Generated by EnvVault".into(), String::new()];

    for u in &upstreams {
        lines.push(format!("upstream {} {{", s(u, "name")));
        for f in fields_of(u) {
            let raw = s(&f, "value");
            if raw.is_empty() {
                continue;
            }
            let val = r.or_literal(raw);
            if s(&f, "key") == "server" {
                for v in split_items(&val, false) {
                    lines.push(format!("    server {v};"));
                }
            } else {
                lines.push(format!("    {} {val};", s(&f, "key")));
            }
        }
        lines.push("}".into());
        lines.push(String::new());
    }

    for sv in &servers {
        lines.push("server {".into());
        for f in fields_of(sv) {
            let raw = s(&f, "value");
            if raw.is_empty() {
                continue;
            }
            let val = r.or_literal_secret(raw, crate::out::chunk_field_is_secret(&f));
            lines.push(format!("    {} {val};", s(&f, "key")));
        }
        if !locations.is_empty() {
            lines.push(String::new());
            for loc in &locations {
                let path = fields_of(loc)
                    .iter()
                    .find(|f| s(f, "key") == "path")
                    .map(|f| s(f, "value").to_string())
                    .filter(|p| !p.is_empty())
                    .unwrap_or_else(|| "/".into());
                lines.push(format!("    location {path} {{"));
                for f in fields_of(loc) {
                    if s(&f, "key") == "path" {
                        continue;
                    }
                    let raw = s(&f, "value");
                    if raw.is_empty() {
                        continue;
                    }
                    let val = r.or_literal_secret(raw, crate::out::chunk_field_is_secret(&f));
                    lines.push(format!("        {} {val};", s(&f, "key")));
                }
                lines.push("    }".into());
            }
        }
        lines.push("}".into());
        lines.push(String::new());
    }
    lines.join("\n")
}

// ── .env from a project's env_file chunks ─────────────────────────────────────

pub struct EnvOut {
    pub text: String,
    pub unresolved: Vec<String>,
    pub had_chunks: bool,
}

pub fn export_project_env(project: &Value, r: &Resolver) -> EnvOut {
    let mut out: Vec<String> = Vec::new();
    let mut unresolved: Vec<String> = Vec::new();
    let mut had_chunks = false;

    for chunk in chunks_of(project) {
        if s(&chunk, "chunk_type") != "env_file" {
            continue;
        }
        had_chunks = true;
        let name = match s(&chunk, "name") {
            "" => "env",
            n => n,
        };
        out.push(format!("# {name}"));
        for f in fields_of(&chunk) {
            let key = s(&f, "key");
            if key.is_empty() {
                continue;
            }
            let raw = s(&f, "value");
            // Every line of a .env is secret material by construction, so the
            // literal values are masked too, not only the resolved references.
            let val = if r.resolve(raw).unresolved {
                unresolved.push(raw.to_string());
                raw.to_string()
            } else {
                r.or_literal_secret(raw, true)
            };
            out.push(format!("{key}={val}"));
        }
        out.push(String::new());
    }
    EnvOut {
        text: out.join("\n"),
        unresolved,
        had_chunks,
    }
}

// ── Single chunk → its native config text ─────────────────────────────────────

pub fn chunk_to_string(chunk: &Value, r: &Resolver) -> String {
    let ctype = s(chunk, "chunk_type");
    let is_env_file = ctype == "env_file";
    let rv = |raw: &str, field: &Value| {
        r.or_literal_secret(raw, is_env_file || crate::out::chunk_field_is_secret(field))
    };

    match ctype {
        "wg_interface" | "wg_peer" => {
            let header = if ctype == "wg_interface" {
                "[Interface]"
            } else {
                "[Peer]"
            };
            let mut lines = vec![header.to_string()];
            for f in fields_of(chunk) {
                lines.push(format!("{} = {}", s(&f, "key"), rv(s(&f, "value"), &f)));
            }
            lines.join("\n")
        }
        "env_file" => fields_of(chunk)
            .iter()
            .filter(|f| !s(f, "key").is_empty())
            .map(|f| format!("{}={}", s(f, "key"), rv(s(f, "value"), f)))
            .collect::<Vec<_>>()
            .join("\n"),
        "nginx_key" => fields_of(chunk)
            .iter()
            .find(|f| s(f, "key") == "content")
            .map(|f| s(f, "value").to_string())
            .unwrap_or_default(),
        "nginx_server" | "nginx_location" | "nginx_upstream" => {
            let block_type = match ctype {
                "nginx_location" => "location",
                "nginx_upstream" => "upstream",
                _ => "server",
            };
            let block_name = match ctype {
                "nginx_location" => fields_of(chunk)
                    .iter()
                    .find(|f| s(f, "key") == "path")
                    .map(|f| s(f, "value").to_string())
                    .filter(|p| !p.is_empty())
                    .map(|p| format!(" {p}"))
                    .unwrap_or_default(),
                "nginx_upstream" => {
                    let n = s(chunk, "name");
                    if n.is_empty() {
                        String::new()
                    } else {
                        format!(" {n}")
                    }
                }
                _ => String::new(),
            };
            let inner = fields_of(chunk)
                .iter()
                .filter(|f| {
                    !s(f, "key").is_empty() && s(f, "key") != "path" && !s(f, "value").is_empty()
                })
                .map(|f| format!("    {} {};", s(f, "key"), rv(s(f, "value"), f)))
                .collect::<Vec<_>>()
                .join("\n");
            format!("{block_type}{block_name} {{\n{inner}\n}}")
        }
        "ssh_host" => {
            let mut lines = vec![format!("Host {}", s(chunk, "name"))];
            for f in fields_of(chunk) {
                if !s(&f, "key").is_empty() && !s(&f, "value").is_empty() {
                    lines.push(format!("    {} {}", s(&f, "key"), rv(s(&f, "value"), &f)));
                }
            }
            lines.join("\n")
        }
        "docker_service" => service_chunk_to_yaml(chunk),
        _ => fields_of(chunk)
            .iter()
            .filter(|f| !s(f, "key").is_empty())
            .map(|f| format!("{}: {}", s(f, "key"), s(f, "value")))
            .collect::<Vec<_>>()
            .join("\n"),
    }
}

fn service_chunk_to_yaml(sc: &Value) -> String {
    let svc_name = s(sc, "name")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join("_")
        .to_lowercase();
    let mut out = vec![format!("{svc_name}:")];

    let mut env_fields: Vec<Value> = Vec::new();
    let mut port_items: Vec<String> = Vec::new();
    let mut volume_items: Vec<String> = Vec::new();
    let mut list_map: Vec<(String, Vec<String>)> = Vec::new();
    let mut scalars: Vec<(String, String)> = Vec::new();

    for f in fields_of(sc) {
        let key = s(&f, "key").to_string();
        let ftype = s(&f, "field_type").to_string();
        let desc = s(&f, "description").to_string();
        let value = s(&f, "value").to_string();
        if key.is_empty() || key == "restart" {
            continue;
        }
        if desc == "env" || ftype == "env_var" {
            env_fields.push(f.clone());
        } else if key == "ports" || ftype == "port" {
            port_items.extend(split_items(&value, false));
        } else if key == "volumes" || ftype == "volume_mount" {
            volume_items.extend(split_items(&value, true));
        } else if key == "networks" || key == "depends_on" || ftype == "list" {
            let items = split_items(&value, false);
            match list_map.iter_mut().find(|(k, _)| *k == key) {
                Some((_, v)) => v.extend(items),
                None => list_map.push((key.clone(), items)),
            }
        } else if !value.is_empty() {
            scalars.push((key, value));
        }
    }

    const PRIO: [&str; 8] = [
        "image",
        "container_name",
        "user",
        "hostname",
        "network_mode",
        "pid",
        "entrypoint",
        "command",
    ];
    let mut remaining = scalars;
    for k in PRIO {
        if let Some(pos) = remaining.iter().position(|(key, _)| key == k) {
            let (key, val) = remaining.remove(pos);
            out.push(format!("  {key}: {}", yaml_str(&val)));
        }
    }
    for (k, v) in &remaining {
        out.push(format!("  {k}: {}", yaml_str(v)));
    }
    if !port_items.is_empty() {
        out.push("  ports:".into());
        for p in &port_items {
            out.push(format!(
                "    - {}",
                serde_json::to_string(p).unwrap_or_default()
            ));
        }
    }
    if !env_fields.is_empty() {
        out.push("  environment:".into());
        for f in &env_fields {
            let raw = s(f, "value");
            let ref_name = if !s(f, "ref_name").is_empty() {
                Some(s(f, "ref_name").to_string())
            } else if raw.starts_with("${") && raw.ends_with('}') && raw.len() > 3 {
                Some(raw[2..raw.len() - 1].to_string())
            } else {
                None
            };
            match ref_name {
                Some(r) => out.push(format!("    - {}=${{{r}}}", s(f, "key"))),
                None => out.push(format!("    - {}={raw}", s(f, "key"))),
            }
        }
    }
    if !volume_items.is_empty() {
        out.push("  volumes:".into());
        for v in &volume_items {
            out.push(format!("    - {}", quote_item(v)));
        }
    }
    for (k, items) in &list_map {
        out.push(format!("  {k}:"));
        for item in items {
            out.push(format!("    - {}", yaml_str(item)));
        }
    }
    let restart = fields_of(sc)
        .iter()
        .find(|f| s(f, "key") == "restart")
        .map(|f| s(f, "value").to_string())
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| "unless-stopped".into());
    out.push(format!("  restart: {restart}"));
    out.join("\n")
}

// ── Vault-level export formats ────────────────────────────────────────────────

pub fn dotenv(entries: &[Value]) -> String {
    entries
        .iter()
        .map(|e| {
            let p = crate::data::env_key(s(e, "provider"));
            format!("{p}={}", s(e, "api_key"))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn yaml(entries: &[Value]) -> String {
    let mut out = String::from("# EnvVault Export\n");
    for e in entries {
        let p = crate::data::env_key(s(e, "provider"));
        out.push_str(&format!(
            "{p}: {}\n",
            serde_json::to_string(s(e, "api_key")).unwrap_or_default()
        ));
    }
    out
}

/// Kubernetes Secret manifest (stringData — values kept readable, not base64).
pub fn k8s_secret(entries: &[Value], name: &str) -> String {
    let mut lines = vec![
        "apiVersion: v1".to_string(),
        "kind: Secret".to_string(),
        "metadata:".to_string(),
        format!("  name: {name}"),
        "type: Opaque".to_string(),
        "stringData:".to_string(),
    ];
    for e in entries {
        lines.push(format!(
            "  {}: {}",
            crate::data::env_key(s(e, "provider")),
            serde_json::to_string(s(e, "api_key")).unwrap_or_default()
        ));
    }
    lines.join("\n")
}

/// Terraform .tfvars — `variable = "value"` pairs.
pub fn tfvars(entries: &[Value]) -> String {
    entries
        .iter()
        .map(|e| {
            format!(
                "{} = {}",
                crate::data::env_key(s(e, "provider")).to_lowercase(),
                serde_json::to_string(s(e, "api_key")).unwrap_or_default()
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}
