#!/usr/bin/env node
/**
 * Generates `src/ts/icon-paths.ts` — the SVG path data for every slug in
 * `SI_REGISTRY`, taken from the `simple-icons` npm package at build time.
 *
 * Why this exists: the app used to build every provider icon as
 * `https://cdn.simpleicons.org/<slug>/e4e4e4` and let the browser fetch it. That
 * meant a third party — and any observer on the path — learned the exact set of
 * services the user holds credentials for, how many entries each has, their IP,
 * and when they opened their vault. For a product whose first sentence is
 * "runs on your machine and talks to nothing else … no telemetry", that was the
 * most sensitive metadata the application holds, leaving by default.
 * (review-01 §3.3.)
 *
 * Only the ~457 slugs the registry actually offers are emitted, not all 3400+
 * icons in the package.
 *
 * Run with `npm run icons`. The output is committed, because a fresh clone must
 * build without regenerating it; `tests/icon-bundle.test.ts` is what catches the
 * two files drifting apart.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(ROOT, 'src', 'ts', 'icons.ts');
const OUT = join(ROOT, 'src', 'ts', 'icon-paths.ts');

// The registry is a TypeScript literal of `['slug', 'Display Name', 'Category'],`
// tuples. Parsing our own source is fragile, so the guard below refuses to write
// anything if the shape stops matching, rather than silently emitting an empty
// map that would turn every icon into a letter avatar.
const src = readFileSync(SOURCE, 'utf8');
const block = src.match(/const SI_REGISTRY[^=]*=\s*\[([\s\S]*?)\n\];/);
if (!block) {
  console.error('gen-icons: could not find the SI_REGISTRY array in src/ts/icons.ts');
  process.exit(1);
}
const slugs = [...block[1].matchAll(/\[\s*'([^']+)'\s*,/g)].map((m) => m[1]);
if (slugs.length < 300) {
  console.error(`gen-icons: only found ${slugs.length} slugs — the registry format changed`);
  process.exit(1);
}

const si = require('simple-icons');
const bySlug = new Map();
for (const icon of Object.values(si)) {
  if (icon && typeof icon === 'object' && typeof icon.slug === 'string')
    bySlug.set(icon.slug, icon);
}

const paths = {};
const missing = [];
for (const slug of [...new Set(slugs)].sort()) {
  const icon = bySlug.get(slug);
  if (icon?.path) paths[slug] = icon.path;
  else missing.push(slug);
}

// `simple-icons` does not export package.json, so read it off disk. The version
// goes in the generated header: knowing which release the paths came from is the
// only way to explain a diff in that file later.
const version = JSON.parse(
  readFileSync(join(ROOT, 'node_modules', 'simple-icons', 'package.json'), 'utf8'),
).version;
const lines = [
  '/**',
  ' * @file',
  ' * SVG path data for the provider icons, bundled at build time.',
  ' *',
  ' * **Generated by `npm run icons`. Do not edit.**',
  ' *',
  ' * Every icon used to be fetched from `cdn.simpleicons.org` on render, which',
  ' * told a third party exactly which services the user holds credentials for,',
  ' * every time the vault was opened. Bundling the ~457 slugs the picker offers',
  ' * closes that permanently and removes the host from the CSP; see',
  ' * `scripts/gen-icons.mjs` and review-01 §3.3.',
  ' *',
  ` * Source: simple-icons@${version}, ${Object.keys(paths).length} icons.`,
  ' */',
  '',
  '/** Simple Icons slug → the `d` attribute of its single 24×24 path. */',
  'export const ICON_PATHS: Readonly<Record<string, string>> = {',
  ...Object.entries(paths).map(([slug, d]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(d)},`),
  '};',
  '',
];
writeFileSync(OUT, lines.join('\n'));

console.log(`gen-icons: wrote ${Object.keys(paths).length} icons from simple-icons@${version}`);
if (missing.length) {
  console.warn(
    `gen-icons: ${missing.length} registry slug(s) not in simple-icons@${version}:\n  ${missing.join(', ')}`,
  );
  console.warn('  These render as letter avatars. Fix the slug in SI_REGISTRY or drop the entry.');
}
