import { st, Settings, inTauri, newEntryId } from './state';
import type { VaultEntry } from './types';
import { showToast, clipboardWrite } from './utils';
import {
  hasTotp,
  totpParamsOf,
  startTotpTicker,
  stopTotpTicker,
  resetTotpCache,
  parseTotpSeed,
  TOTP_DEFAULTS,
  type TotpKind,
} from './totp';
import { render } from './render';
import { html, setHtml, type SafeHtml } from './html';

/** Which kinds the panel is showing. Panel-local: it filters nothing else. */
let kindFilter: 'all' | TotpKind = 'all';
/** The search box's current text, lowercased. */
let query = '';

/** Every entry carrying a seed, in the order the panel shows them. */
function seeded(): VaultEntry[] {
  const all = st.vault?.api_keys ?? [];
  return all
    .filter(hasTotp)
    .filter((e) => kindFilter === 'all' || totpParamsOf(e).kind === kindFilter)
    .filter((e) => {
      if (!query) return true;
      const hay = `${e.provider} ${e.account_name ?? ''} ${e.username ?? ''}`.toLowerCase();
      return hay.includes(query);
    })
    .sort((a, b) => a.provider.localeCompare(b.provider));
}

/** How a kind is labelled on a card. */
const KIND_LABEL: Record<TotpKind, string> = {
  totp: 'Time-based',
  hotp: 'Counter',
  steam: 'Steam',
};

/**
 * One card.
 *
 * `data-totp-for` is the ticker's contract and carries the entry **id**, never
 * an index (invariant 1): the ticker re-looks-up the entry every second, so a
 * card left over from a previous render resolves to nothing rather than to
 * whatever took its position. The digits are deliberately absent from this
 * markup — the ticker writes them, so a re-render cannot bake a live code into
 * the document.
 */
function cardHtml(entry: VaultEntry, showNext: boolean): SafeHtml {
  const id = entry.id ?? '';
  const params = totpParamsOf(entry);
  const label = entry.account_name ? `${entry.provider} · ${entry.account_name}` : entry.provider;
  const isHotp = params.kind === 'hotp';
  return html`<article
    class="auth-card"
    data-totp-for="${id}"
    ${showNext ? html` data-totp-next="1"` : ''}
    data-totp-kind="${params.kind}"
  >
    <header class="auth-card-head">
      <span class="auth-card-name">${label}</span>
      <span class="auth-kind-badge auth-kind-${params.kind}">${KIND_LABEL[params.kind]}</span>
    </header>
    <button
      class="auth-code-row"
      data-action="copy-totp"
      aria-label="${'Copy the code for ' + label}"
    >
      <span class="totp-code auth-code">— — —</span>${isHotp ? html`<span class="totp-counter auth-counter" aria-hidden="true"></span>` : html`<span class="totp-countdown auth-ring"><i class="totp-countdown-fill"></i></span><span class="totp-secs auth-secs" aria-hidden="true"></span>`}</button>
    <div class="auth-next-row" ${showNext ? '' : ' hidden'}>
      <span class="auth-next-label">next</span>
      <span class="totp-next auth-next" hidden></span>
    </div>${
      isHotp
        ? html`<footer class="auth-card-foot">
            <button
              class="btn btn-xs"
              data-auth-advance="${id}"
              title="Move this seed to its next position. Reading a code never advances it."
            >
              Advance
            </button>
          </footer>`
        : ''
    }</article>`;
}

/**
 * Paint the panel.
 *
 * Safe to call on every render: the ticker it starts is idempotent by
 * assignment (invariant 9), so this leaves one interval rather than one per
 * call.
 */
export function renderAuthPanel(): void {
  const grid = document.getElementById('auth-grid');
  const empty = document.getElementById('auth-empty');
  const count = document.getElementById('auth-count');
  const side = document.getElementById('auth-side-list');
  if (!grid) return;

  const rows = seeded();
  const total = (st.vault?.api_keys ?? []).filter(hasTotp).length;
  const showNext = !!Settings.get('authShowNext');

  if (count) {
    count.textContent = inTauri
      ? `${total} seed${total === 1 ? '' : 's'}${rows.length !== total ? `, ${rows.length} shown` : ''}`
      : 'Codes are generated by the desktop app.';
  }
  if (empty) empty.hidden = total !== 0;
  // Same rule the sidebar section follows: offering Export with nothing to write
  // produces an error toast for a button the user was right to press.
  const exportBtn = document.getElementById('auth-export-btn') as HTMLButtonElement | null;
  if (exportBtn) exportBtn.disabled = total === 0;

  setHtml(grid, html`${rows.map((e) => cardHtml(e, showNext))}`);
  if (side) {
    setHtml(
      side,
      html`${rows.map(
        (e) =>
          html`<button class="auth-side-item" data-auth-focus="${e.id ?? ''}">
            <span class="auth-side-name">${e.provider}</span>
            <span class="auth-side-kind">${totpParamsOf(e).kind}</span>
          </button>`,
      )}`,
    );
  }

  if (rows.length) startTotpTicker();
  else stopTotpTicker();
}

/**
 * Advance a counter-based seed by one.
 *
 * Reading a code deliberately does not do this. A counter-based code stands
 * until it is used and the service moves on only when it accepts one, so
 * advancing on every read would walk the vault past the service the first time
 * somebody looked at a card twice — and the resulting failure, a second factor
 * that stops working with no error anywhere, looks exactly like a wrong seed.
 */
async function advance(id: string): Promise<void> {
  const entry = (st.vault?.api_keys ?? []).find((e) => e.id === id);
  if (!entry) return;
  const params = totpParamsOf(entry);
  if (params.kind !== 'hotp') return;

  entry.totp_counter = params.counter + 1;
  // The cache is keyed by the counter, so the new position shows immediately
  // rather than serving the code for the position just left.
  try {
    await st.store.save(st.vault!);
    showToast(`Advanced to #${entry.totp_counter}`);
  } catch {
    entry.totp_counter = params.counter;
    showToast('Could not save the new counter');
    return;
  }
  renderAuthPanel();
}

// ── Add 2FA (Phase 24.2) ────────────────────────────────────────────────────

/**
 * Reads the seed + kind/counter fields, applying the same default-omission
 * rule the main add/edit form's `readTotpFields` does: a parameter equal to
 * its `otpauth://` default is written as absent, because a stored
 * `totp_algorithm: "SHA1"` cannot otherwise be told apart from a defaulted
 * one. Unlike that form, only kind and counter are user-adjustable here —
 * algorithm/digits/period come from whatever the seed itself parsed to.
 *
 * `null` when the seed field is empty or unusable; the caller is what decides
 * whether that is an error worth showing.
 */
function readAdd2faFields(): Pick<
  VaultEntry,
  'totp_secret' | 'totp_algorithm' | 'totp_digits' | 'totp_period' | 'totp_kind' | 'totp_counter'
> | null {
  const raw =
    (document.getElementById('add2fa-seed') as HTMLInputElement | null)?.value?.trim() ?? '';
  if (!raw) return null;
  let parsed: ReturnType<typeof parseTotpSeed>;
  try {
    parsed = parseTotpSeed(raw);
  } catch {
    return null;
  }
  const kindSel = (document.getElementById('add2fa-kind') as HTMLSelectElement | null)?.value;
  const kind = (kindSel as TotpKind) || parsed.kind;
  const counterRaw = Number(
    (document.getElementById('add2fa-counter') as HTMLInputElement | null)?.value ?? '0',
  );
  const counter = Number.isFinite(counterRaw) ? Math.max(0, Math.trunc(counterRaw)) : 0;

  // Steam forces its own shape on read (`totpParamsOf`) whatever is stored, so
  // the parameter boxes describe nothing for it — writing what they happen to
  // hold would store a seed that validates and produces characters Steam
  // rejects.
  if (kind === 'steam') {
    return {
      totp_secret: parsed.secret,
      totp_algorithm: undefined,
      totp_digits: undefined,
      totp_period: undefined,
      totp_kind: 'steam',
      totp_counter: undefined,
    };
  }
  return {
    totp_secret: parsed.secret,
    totp_algorithm: parsed.algorithm === TOTP_DEFAULTS.algorithm ? undefined : parsed.algorithm,
    totp_digits: parsed.digits === TOTP_DEFAULTS.digits ? undefined : parsed.digits,
    totp_period: parsed.period === TOTP_DEFAULTS.period ? undefined : parsed.period,
    totp_kind: kind === TOTP_DEFAULTS.kind ? undefined : kind,
    totp_counter: kind === 'hotp' ? counter : undefined,
  };
}

/** Populates the "attach to existing entry" select. Only entries without a
 * seed already — attaching to one that has one would either silently replace
 * a working second factor or need its own conflict UI, and the entry's own
 * edit form is already the place to re-enroll one on purpose. */
function populateAdd2faExisting(): void {
  const sel = document.getElementById('add2fa-existing') as HTMLSelectElement | null;
  if (!sel) return;
  const candidates = (st.vault?.api_keys ?? []).filter((e) => !hasTotp(e));
  setHtml(
    sel,
    html`${candidates.map((e) => {
      const label = e.account_name ? `${e.provider} · ${e.account_name}` : e.provider;
      return html`<option value="${e.id ?? ''}">${label}</option>`;
    })}`,
  );
}

/** Live status line under the seed field — valid/invalid, never blocking
 * typing. Also where issuer/account are *offered*: filled into the Name/
 * Account boxes only while those are still empty, never overwriting what the
 * user already typed (the same rule Phase 22's URI import follows). */
function updateAdd2faStatus(): void {
  const status = document.getElementById('add2fa-status');
  const raw =
    (document.getElementById('add2fa-seed') as HTMLInputElement | null)?.value?.trim() ?? '';
  const counterRow = document.getElementById('add2fa-counter-row');
  const kindSel = document.getElementById('add2fa-kind') as HTMLSelectElement | null;
  if (counterRow) counterRow.style.display = kindSel?.value === 'hotp' ? '' : 'none';

  if (!status) return;
  if (!raw) {
    status.textContent = '';
    return;
  }
  try {
    const parsed = parseTotpSeed(raw);
    status.textContent = '✓ Looks like a usable seed';
    status.style.color = 'var(--price-free)';
    if (kindSel && !kindSel.dataset.userTouched) kindSel.value = parsed.kind;
    const nameEl = document.getElementById('add2fa-name') as HTMLInputElement | null;
    const acctEl = document.getElementById('add2fa-account') as HTMLInputElement | null;
    if (nameEl && !nameEl.value && parsed.issuer) nameEl.value = parsed.issuer;
    if (acctEl && !acctEl.value && parsed.account) acctEl.value = parsed.account;
  } catch (e) {
    status.textContent = e instanceof Error ? e.message : 'Not a usable seed';
    status.style.color = 'var(--price-paid)';
  }
}

function openAdd2fa(): void {
  const overlay = document.getElementById('add2fa-overlay');
  if (!overlay) return;
  // Every field is blanked on open rather than only on save: a form that
  // shows the last attempt's values after a cancel reads as still trying it.
  (document.getElementById('add2fa-name') as HTMLInputElement | null)!.value = '';
  (document.getElementById('add2fa-account') as HTMLInputElement | null)!.value = '';
  (document.getElementById('add2fa-seed') as HTMLInputElement | null)!.value = '';
  (document.getElementById('add2fa-counter') as HTMLInputElement | null)!.value = '0';
  const kindSel = document.getElementById('add2fa-kind') as HTMLSelectElement | null;
  if (kindSel) {
    kindSel.value = 'totp';
    delete kindSel.dataset.userTouched;
  }
  (document.getElementById('add2fa-target-new') as HTMLInputElement | null)!.checked = true;
  document.getElementById('add2fa-new-row')!.style.display = '';
  document.getElementById('add2fa-existing-row')!.style.display = 'none';
  const status = document.getElementById('add2fa-status');
  if (status) status.textContent = '';
  populateAdd2faExisting();
  overlay.classList.add('open');
  (document.getElementById('add2fa-name') as HTMLInputElement | null)?.focus();
}

function closeAdd2fa(): void {
  document.getElementById('add2fa-overlay')?.classList.remove('open');
}

async function saveAdd2fa(): Promise<void> {
  const fields = readAdd2faFields();
  if (!fields) {
    showToast('Enter a valid seed or otpauth:// URI', 'err');
    return;
  }
  const attachExisting = (
    document.getElementById('add2fa-target-existing') as HTMLInputElement | null
  )?.checked;

  if (attachExisting) {
    const id = (document.getElementById('add2fa-existing') as HTMLSelectElement | null)?.value;
    const entry = (st.vault?.api_keys ?? []).find((e) => e.id === id);
    if (!entry) {
      showToast('Choose an entry to attach to', 'err');
      return;
    }
    if (hasTotp(entry)) {
      // Refused rather than silently replaced — the same rule the totp-import
      // merge follows for exactly this reason: an import (or, here, a manual
      // add) is exactly the moment a stale attempt could overwrite a working
      // second factor.
      showToast(`${entry.provider} already has a seed — edit it directly to re-enroll`, 'err');
      return;
    }
    Object.assign(entry, fields);
  } else {
    const name = (document.getElementById('add2fa-name') as HTMLInputElement | null)?.value.trim();
    if (!name) {
      showToast('Name the entry', 'err');
      return;
    }
    const account =
      (document.getElementById('add2fa-account') as HTMLInputElement | null)?.value.trim() ||
      undefined;
    const entry: VaultEntry = {
      id: newEntryId(),
      provider: name,
      account_name: account,
      api_key: '',
      secretType: 'password',
      price_type: 'free',
      categories: [],
      scopes: [],
      projectIds: ['Universal'],
      ...fields,
    };
    st.vault!.api_keys.push(entry);
  }

  try {
    await st.store.save(st.vault!);
  } catch {
    showToast('Could not save the new seed', 'err');
    return;
  }
  closeAdd2fa();
  showToast('2FA added ✓', 'ok');
  render();
  renderAuthPanel();
}

let wired = false;

/**
 * Bind the panel's controls.
 *
 * Assignment, not `addEventListener` (invariant 9): this panel is shown, hidden
 * and shown again across a lock cycle, and a stacked handler would advance a
 * counter twice per click — which is the one action here that cannot be undone
 * without resynchronising against the service.
 */
export function initAuthPanel(): void {
  if (wired) return;
  wired = true;

  const search = document.getElementById('auth-search') as HTMLInputElement | null;
  if (search) {
    search.oninput = () => {
      query = search.value.trim().toLowerCase();
      renderAuthPanel();
    };
  }

  document.querySelectorAll<HTMLButtonElement>('.auth-kind-btn').forEach((btn) => {
    btn.onclick = () => {
      kindFilter = (btn.dataset.kind as typeof kindFilter) || 'all';
      document
        .querySelectorAll('.auth-kind-btn')
        .forEach((b) => b.classList.toggle('active', b === btn));
      renderAuthPanel();
    };
  });

  const next = document.getElementById('auth-show-next') as HTMLInputElement | null;
  if (next) {
    next.checked = !!Settings.get('authShowNext');
    next.onchange = () => {
      Settings.set('authShowNext', next.checked);
      // The next code is fetched separately and cached separately, so turning
      // this on must not be served a cached answer that has no next code in it.
      resetTotpCache();
      renderAuthPanel();
    };
  }

  // The sidebar list addresses cards by entry **id**, not by position: the grid
  // is filtered and re-sorted independently of nothing in particular, and an
  // index captured here would point at whatever took its place (invariant 1).
  const side = document.getElementById('auth-side-list');
  if (side) {
    side.onclick = (ev) => {
      const row = (ev.target as HTMLElement).closest<HTMLElement>('[data-auth-focus]');
      if (!row) return;
      const card = document.querySelector<HTMLElement>(
        `#auth-grid .auth-card[data-totp-for="${CSS.escape(row.dataset.authFocus || '')}"]`,
      );
      if (!card) return;
      card.scrollIntoView({ block: 'nearest' });
      // A class rather than focus(): the card is not a control, and moving focus
      // onto it would take the keyboard out of the list the user is walking.
      document
        .querySelectorAll('#auth-grid .auth-card.flash')
        .forEach((c) => c.classList.remove('flash'));
      card.classList.add('flash');
      setTimeout(() => card.classList.remove('flash'), 1200);
    };
  }

  const grid = document.getElementById('auth-grid');
  if (grid) {
    grid.onclick = (ev) => {
      const el = ev.target as HTMLElement;
      const adv = el.closest<HTMLElement>('[data-auth-advance]');
      if (adv) {
        void advance(adv.dataset.authAdvance!);
        return;
      }
      const card = el.closest<HTMLElement>('.auth-card');
      const code = card?.dataset.totpCode;
      if (code && el.closest('.auth-code-row')) {
        // The code the ticker painted, not a re-derived one: re-deriving hands
        // over the *next* code when the click crosses a step boundary.
        void clipboardWrite(code);
        showToast('Code copied');
      }
    };
  }

  // ── Add 2FA modal ──────────────────────────────────────────────────────
  document.getElementById('auth-add-btn')?.addEventListener('click', openAdd2fa);
  document.getElementById('add2fa-close')?.addEventListener('click', closeAdd2fa);
  document.getElementById('add2fa-cancel')?.addEventListener('click', closeAdd2fa);
  document.getElementById('add2fa-overlay')?.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) closeAdd2fa();
  });
  document.getElementById('add2fa-save')?.addEventListener('click', () => void saveAdd2fa());

  const seedInput = document.getElementById('add2fa-seed') as HTMLInputElement | null;
  if (seedInput) seedInput.oninput = updateAdd2faStatus;

  const add2faKind = document.getElementById('add2fa-kind') as HTMLSelectElement | null;
  if (add2faKind) {
    add2faKind.onchange = () => {
      // Once the user has picked a kind by hand, the seed field's own live
      // guess (in `updateAdd2faStatus`) must stop overwriting it — otherwise
      // choosing "Counter" and then editing the seed silently flips it back.
      add2faKind.dataset.userTouched = '1';
      updateAdd2faStatus();
    };
  }

  document.querySelectorAll<HTMLInputElement>('input[name="add2fa-target"]').forEach((radio) => {
    radio.onchange = () => {
      const existing = radio.value === 'existing' && radio.checked;
      const newRow = document.getElementById('add2fa-new-row');
      const existingRow = document.getElementById('add2fa-existing-row');
      if (newRow) newRow.style.display = existing ? 'none' : '';
      if (existingRow) existingRow.style.display = existing ? '' : 'none';
    };
  });
}
