/**
 * @file
 * Chunk operations — chunk card rendering, config exporters, cert linking.
 *
 * This module was ~2350 lines covering six unrelated concerns. The
 * self-contained pieces now live under `./chunks/` and are re-exported below,
 * so every existing `from './chunk-ops'` import keeps working unchanged:
 *
 * - `chunks/starters`   — starter chunk templates for new typed projects
 * - `chunks/parsers`    — wg0.conf / compose / nginx / apache / haproxy / ssh parsers
 * - `chunks/edit-modal` — the chunk field editor
 * - `chunks/env-link`   — env-file field ↔ vault entry matching
 *
 * What remains here is the part that is genuinely interdependent: card
 * rendering, the exporters and the nginx certificate auto-linking.
 */

import type {
  Project,
  SecretChunk,
  ChunkField,
  ChunkFieldType,
  ChunkType,
  ProjectType,
  VaultEntry,
} from './types';
import { st, Settings, triggerRender, persist } from './state';
import { esc, escAttr, copySVG, editSVG, delSVG, showToast } from './utils';

// ── Re-exports (barrel) ────────────────────────────────────────────────────
export * from './chunks/starters';
export * from './chunks/parsers';
export * from './chunks/edit-modal';
export * from './chunks/env-link';

/**
 * The chunks an export should actually emit.
 *
 * `disabled` is documented as "excluded from exports", and the later exporters
 * (apache, haproxy, ansible, postgres) each check it inline. The four that
 * people actually deploy — WireGuard, Compose, nginx, k8s — did not, so
 * disabling a peer or a service in the UI greyed the card out and then shipped
 * it anyway. Disabling a WireGuard peer and still writing it into wg0.conf means
 * the tunnel keeps trusting a peer the user believes they removed.
 */
export function activeChunks(project: Project): SecretChunk[] {
  return (project.chunks || []).filter((c) => !c.disabled);
}

/**
 * Resolve a `${ref}` for an exporter, falling back to the literal on failure.
 *
 * Six of the seven experimental exporters interpolated `f.value` raw, so a
 * `${Provider/field}` reached the generated config as literal text: a `.pgpass`
 * line whose password is the string `${DB/password}`, an Apache `SSLCertificateFile`
 * pointing at nothing. That is invariant 5, and it is the *same* bug that was
 * found in `exportNginx` during Phase 13 — found there by a golden fixture,
 * missed here because these types had no fixture.
 *
 * `true` selects the env-copy field, matching every other exporter that
 * materialises a real config file.
 */
function xv(value: string | undefined | null): string {
  const v = value ?? '';
  if (!v) return '';
  return resolveFieldRef(v, true).resolved ?? v;
}

export function exportApache(project: Project): string {
  const chunks = project.chunks || [];
  const lines: string[] = ['# Generated by EnvVault', ''];
  for (const chunk of chunks) {
    if (chunk.disabled) continue;
    if (chunk.chunk_type === 'apache_vhost') {
      const port = chunk.fields.find((f) => f.key === 'SSLEngine') ? '443' : '80';
      lines.push(`<VirtualHost *:${port}>`);
      for (const f of chunk.fields) {
        if (f.value) lines.push(`    ${f.key} ${xv(f.value)}`);
      }
      lines.push('</VirtualHost>', '');
    } else if (chunk.chunk_type === 'apache_directory') {
      const path = xv(chunk.fields.find((f) => f.key === 'path')?.value) || '/';
      lines.push(`<Directory ${path}>`);
      for (const f of chunk.fields) {
        if (f.key !== 'path' && f.value) lines.push(`    ${f.key} ${xv(f.value)}`);
      }
      lines.push('</Directory>', '');
    }
  }
  return lines.join('\n');
}

export function exportHaproxy(project: Project): string {
  const chunks = project.chunks || [];
  const lines: string[] = ['# Generated by EnvVault', ''];
  for (const chunk of chunks) {
    if (chunk.disabled) continue;
    if (chunk.chunk_type === 'haproxy_global') {
      lines.push('global');
      for (const f of chunk.fields) {
        if (f.value) lines.push(`    ${f.key} ${xv(f.value)}`);
      }
      lines.push('');
    } else if (chunk.chunk_type === 'haproxy_frontend') {
      lines.push(`frontend ${chunk.name}`);
      for (const f of chunk.fields) {
        if (f.value) lines.push(`    ${f.key} ${xv(f.value)}`);
      }
      lines.push('');
    } else if (chunk.chunk_type === 'haproxy_backend') {
      lines.push(`backend ${chunk.name}`);
      for (const f of chunk.fields) {
        if (f.value) lines.push(`    ${f.key} ${xv(f.value)}`);
      }
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function exportAnsible(project: Project): string {
  const chunks = project.chunks || [];
  const varChunks = chunks.filter((c) => !c.disabled && c.chunk_type === 'ansible_vars');
  const taskChunks = chunks.filter((c) => !c.disabled && c.chunk_type === 'ansible_task');

  const varLines = (indent: string) => {
    const out: string[] = [];
    for (const chunk of varChunks) {
      out.push(`${indent}# ${chunk.name}`);
      for (const f of chunk.fields) {
        if (f.key) out.push(`${indent}${f.key}: ${JSON.stringify(xv(f.value))}`);
      }
    }
    return out;
  };

  const taskLines = (indent: string) => {
    const out: string[] = [];
    for (const chunk of taskChunks) {
      const name = xv(chunk.fields.find((f) => f.key === 'name')?.value) || chunk.name;
      const module = xv(chunk.fields.find((f) => f.key === 'module')?.value) || 'debug';
      out.push(`${indent}- name: ${name}`, `${indent}  ${module}:`);
      for (const f of chunk.fields) {
        if (f.key !== 'name' && f.key !== 'module' && f.key)
          out.push(`${indent}    ${f.key}: ${JSON.stringify(xv(f.value))}`);
      }
    }
    return out;
  };

  // Emitting vars and tasks into one document produced a mapping immediately
  // followed by a sequence, which is not valid YAML in any parser — so the
  // output was unusable by the tool it targets, and nothing noticed because
  // nothing had ever run `ansible-playbook` against it. Found by the Phase 18
  // validation matrix.
  //
  // The shape now follows how Ansible actually consumes these files:
  //   tasks present → a playbook (one play, with vars folded into it)
  //   vars only     → a bare mapping, which is what group_vars/host_vars want
  if (taskChunks.length) {
    const lines = ['# Generated by EnvVault', '- hosts: all'];
    if (varChunks.length) {
      lines.push('  vars:');
      lines.push(...varLines('    '));
    }
    lines.push('  tasks:');
    lines.push(...taskLines('    '));
    return lines.join('\n');
  }

  const lines = ['# Generated by EnvVault'];
  if (varChunks.length) lines.push(...varLines(''));
  return lines.join('\n');
}

export function exportPostgres(project: Project): string {
  const chunks = project.chunks || [];
  const lines: string[] = [
    '# Generated by EnvVault — .pgpass format: host:port:dbname:user:password',
  ];
  for (const chunk of chunks) {
    if (chunk.disabled) continue;
    if (chunk.chunk_type === 'pg_connection') {
      const g = (k: string) => xv(chunk.fields.find((f) => f.key === k)?.value);
      lines.push(
        `${g('host')}:${g('port') || '5432'}:${g('dbname')}:${g('user')}:${g('password')}`,
      );
    }
  }
  return lines.join('\n');
}

// ── Field resolution ───────────────────────────────────────────────────────

/** Canonical names for well-known field suffixes used in env var naming conventions. */
const FIELD_ALIASES: Readonly<Record<string, string>> = {
  APIKEY: 'key',
  API_KEY: 'key',
  KEY: 'key',
  TOKEN: 'key',
  ACCESS_TOKEN: 'key',
  BEARER: 'key',
  SECRET_KEY: 'key',
  PASSWORD: 'key',
  PASS: 'key',
  PWD: 'key',
  // ↑ a password entry stores its secret in api_key, so ${name/password} resolves there too
  SECRET: 'secret',
  API_SECRET: 'secret',
  CLIENT_SECRET: 'secret',
  SHARED_SECRET: 'secret',
  USERNAME: 'username',
  USER: 'username',
  LOGIN: 'username',
  USER_NAME: 'username',
  URL: 'url',
  URI: 'url',
  ENDPOINT: 'url',
  API_URL: 'url',
  BASE_URL: 'url',
  EMAIL: 'email',
  MAIL: 'email',
  KEY_ID: 'key_id',
  KEYID: 'key_id',
  KID: 'key_id',
};

/** Resolve a named field from a vault entry. Supports built-in fields, aliases, and extra_vars keys. */
function getEntryFieldValue(entry: VaultEntry, field: string): string | null | undefined {
  const canonical = FIELD_ALIASES[field.toUpperCase()] ?? field;
  switch (canonical) {
    case 'key':
      return entry.api_key;
    case 'secret':
      return entry.api_secret;
    case 'username':
      return entry.username;
    case 'url':
      return entry.api_url;
    case 'key_id':
      return entry.key_id;
    case 'email':
      return entry.email;
    default:
      return entry.extra_vars?.find((v) => v.key === field || v.key === canonical)?.value;
  }
}

export function resolveFieldRef(
  value: string,
  useEnvCopyField = false,
  _depth = 0,
): {
  resolved: string | null;
  refName: string | null;
  unresolved: boolean;
  source: 'vault' | 'env_file' | 'chunk' | null;
} {
  const match = /^\$\{(.+)}$/.exec(value);
  if (!match) return { resolved: value, refName: null, unresolved: false, source: null };
  const refName = match[1];

  // Cross-chunk notation: ${chunk:ChunkName/FieldKey} — resolve any chunk field across all projects.
  // Recursively resolves if the target is itself a ${ref} (depth-guarded against cycles).
  if (refName.startsWith('chunk:')) {
    const body = refName.slice(6);
    const slash = body.indexOf('/');
    if (slash < 0) return { resolved: null, refName, unresolved: true, source: null };
    const chunkName = body.slice(0, slash);
    const fieldKey = body.slice(slash + 1);
    for (const project of st.vault.projects) {
      for (const chunk of project.chunks || []) {
        if (chunk.name !== chunkName) continue;
        const f = chunk.fields.find((ff) => ff.key === fieldKey);
        if (!f) continue;
        if (_depth < 4 && /^\$\{.+}$/.test(f.value)) {
          const nested = resolveFieldRef(f.value, useEnvCopyField, _depth + 1);
          return {
            resolved: nested.resolved,
            refName,
            unresolved: nested.unresolved,
            source: nested.source ?? 'chunk',
          };
        }
        return { resolved: f.value, refName, unresolved: false, source: 'chunk' };
      }
    }
    return { resolved: null, refName, unresolved: true, source: null };
  }

  // Slash notation: ${PROVIDER/field} or ${PROVIDER_LABEL/field} — direct field access.
  const slashIdx = refName.indexOf('/');
  if (slashIdx >= 0) {
    const provPart = refName.slice(0, slashIdx);
    const field = refName.slice(slashIdx + 1);
    // Try exact provider match, then provider_keyid split (e.g. TMDB_v2 → provider=TMDB key_id=v2).
    let entry = st.vault.api_keys.find((e) => e.provider === provPart);
    if (!entry && provPart.includes('_')) {
      const lastUs = provPart.lastIndexOf('_');
      const prov = provPart.slice(0, lastUs);
      const kid = provPart.slice(lastUs + 1);
      entry = st.vault.api_keys.find((e) => e.provider === prov && e.key_id === kid);
    }
    if (entry) {
      const val = getEntryFieldValue(entry, field);
      const resolved = val != null && val !== '' ? String(val) : null;
      return { resolved, refName, unresolved: !resolved, source: 'vault' };
    }
    return { resolved: null, refName, unresolved: true, source: null };
  }

  // Legacy: exact provider match, then compound PROVIDER_KEYID match.
  let entry = st.vault.api_keys.find((e) => e.provider === refName);
  if (!entry && refName.includes('_')) {
    const lastUs = refName.lastIndexOf('_');
    const provPart = refName.slice(0, lastUs);
    const labelPart = refName.slice(lastUs + 1);
    entry = st.vault.api_keys.find((e) => e.provider === provPart && e.key_id === labelPart);
  }

  if (entry) {
    let resolved: string | null;
    if (useEnvCopyField) {
      const fieldName = (Settings.get('envCopyField') || 'api_key') as keyof VaultEntry;
      const rawVal = entry[fieldName];
      resolved = rawVal != null && rawVal !== '' ? String(rawVal) : entry.api_key || null;
    } else {
      resolved = entry.api_key || null;
    }
    return { resolved, refName, unresolved: false, source: 'vault' };
  }

  for (const project of st.vault.projects) {
    for (const chunk of project.chunks || []) {
      if (chunk.chunk_type !== 'env_file') continue;
      const field = chunk.fields.find((f) => f.key === refName);
      if (field) return { resolved: field.value, refName, unresolved: false, source: 'env_file' };
    }
  }
  return { resolved: null, refName, unresolved: true, source: null };
}

// ── Field copy text formatter ──────────────────────────────────────────────

/** Returns the field formatted in its native config syntax for clipboard. */
/**
 * Rewrites every `${PROVIDER…}` chunk reference after an entry is renamed.
 *
 * References resolve by provider name (see {@link resolveFieldRef}), so
 * renaming an entry used to break every chunk field pointing at it — silently,
 * with the field simply starting to render unresolved. The security audit could
 * already *detect* the resulting stale refs; nothing prevented them. Projects
 * and categories cascade their renames, and this brings entries in line.
 *
 * Handles all four reference spellings: `${Provider}`, `${Provider/field}`,
 * `${Provider_KeyId}` and `${Provider_KeyId/field}`. Leaves `${chunk:…}` alone —
 * those address a chunk, not an entry.
 *
 * @returns how many fields were rewritten.
 */
export function renameProviderRefs(
  oldProvider: string,
  oldKeyId: string | null | undefined,
  newProvider: string,
  newKeyId: string | null | undefined,
): number {
  const oldNames = new Set<string>([oldProvider]);
  if (oldKeyId) oldNames.add(`${oldProvider}_${oldKeyId}`);
  const newCompound = newKeyId ? `${newProvider}_${newKeyId}` : newProvider;

  let changed = 0;
  for (const project of st.vault.projects) {
    for (const chunk of project.chunks || []) {
      for (const field of chunk.fields || []) {
        const match = typeof field.value === 'string' && /^\$\{(.+)}$/.exec(field.value);
        if (!match) continue;
        const body = match[1];
        if (body.startsWith('chunk:')) continue;

        const slash = body.indexOf('/');
        const head = slash >= 0 ? body.slice(0, slash) : body;
        if (!oldNames.has(head)) continue;

        // A bare `${Provider}` becomes the new compound name; a `${x/field}`
        // keeps its field suffix.
        const replacement =
          head === oldProvider && slash < 0 && !oldKeyId ? newProvider : newCompound;
        field.value = slash >= 0 ? `\${${replacement}${body.slice(slash)}}` : `\${${replacement}}`;
        changed++;
      }
    }
  }
  return changed;
}

function chunkFieldCopyText(key: string, value: string, chunkType: string): string {
  if (chunkType === 'env_file') return `${key}=${value}`;
  if (chunkType === 'wg_interface' || chunkType === 'wg_peer') return `${key} = ${value}`;
  if (chunkType === 'ssh_host') return `    ${key} ${value}`;
  if (chunkType.startsWith('nginx_')) return `${key} ${value};`;
  if (chunkType.startsWith('k8s_') || chunkType.startsWith('traefik_')) return `${key}: ${value}`;
  return `${key} = ${value}`;
}

// ── Cert link helpers ──────────────────────────────────────────────────────

/** Find a vault cert entry linked to a field value (${REF} or path pattern). */
function findLinkedCert(value: string): VaultEntry | null {
  if (!value) return null;

  // ${REF} syntax
  const ref = /^\$\{(.+)}$/.exec(value);
  if (ref) {
    const name = ref[1];
    const base = name.replace(/[_-]?(key|privkey|fullchain|cert|certificate)$/i, '');
    return (
      st.vault.api_keys.find(
        (e) => e.secretType === 'certificate' && (e.provider === name || e.provider === base),
      ) ||
      st.vault.api_keys.find((e) => e.provider === name || e.provider === base) ||
      null
    );
  }

  // /etc/letsencrypt/live/DOMAIN/...
  const lePath = /\/live\/([^/]+)\//.exec(value);
  if (lePath) {
    const domain = lePath[1];
    return (
      st.vault.api_keys.find(
        (e) =>
          e.secretType === 'certificate' &&
          (e.provider === domain ||
            e.provider.replace(/^www\./, '') === domain.replace(/^www\./, '')),
      ) || null
    );
  }

  return null;
}

/** Render a certificate info panel for a linked vault cert entry. */
function renderCertPanel(entry: VaultEntry, isCertKey: boolean): string {
  const cn = entry.api_description || entry.provider;
  const expiry = entry.expires_at ? new Date(entry.expires_at) : null;
  const now = new Date();
  const soon = expiry && expiry.getTime() - now.getTime() < 30 * 86_400_000;
  const expired = expiry && expiry < now;
  const expiryColor = expired ? 'var(--price-paid)' : soon ? '#f0ad4e' : 'var(--text3)';
  const expiryText = expiry ? expiry.toISOString().slice(0, 10) : 'no expiry';
  const pemContent = isCertKey
    ? entry.cert_key_data || ''
    : entry.certificate_data || entry.api_key || '';
  const pemPreview = pemContent ? pemContent.split('\n').slice(0, 3).join('\n') + '\n…' : '—';

  return `
    <div class="cert-panel">
      <div class="cert-panel-row">
        <div class="cert-panel-meta">
          <span class="cert-panel-cn">${esc(cn)}</span>
          <span class="cert-panel-expiry" style="color:${expiryColor}">${expired ? '⚠ EXPIRED ' : soon ? '⚠ expires ' : 'exp '}${esc(expiryText)}</span>
        </div>
        <div class="cert-panel-actions">
          ${pemContent ? `<button class="btn btn-ghost btn-xs" data-action="chunk-copy" data-value="${escAttr(pemContent)}" title="Copy PEM">Copy PEM</button>` : ''}
        </div>
      </div>
      <pre class="cert-panel-pem">${esc(pemPreview)}</pre>
    </div>
  `;
}

// ── Nginx ↔ certificate auto-linking ───────────────────────────────────────

const normDomain = (s: string): string =>
  s
    .trim()
    .toLowerCase()
    .replace(/^\*?\./, '')
    .replace(/^www\./, '');

/** Extract a domain from a letsencrypt-style path, e.g. ".../live/darthdemono.com/fullchain.pem". */
export function domainFromCertPath(path: string): string | null {
  const m =
    /(?:^|\/)live\/([^/]+)\//i.exec(path) ||
    /(?:^|\/)([a-z0-9.-]+\.[a-z]{2,})\/(?:fullchain|privkey|cert|chain)\b/i.exec(path);
  return m ? normDomain(m[1]) : null;
}

/** All cert domains an nginx project references: project name, server_name values, ssl paths, nginx_key paths. */
export function nginxCertDomains(project: Project): string[] {
  const out = new Set<string>();
  const add = (d: string | null | undefined) => {
    if (!d) return;
    const n = normDomain(d);
    if (n && /^[a-z0-9.-]+\.[a-z]{2,}$/.test(n)) out.add(n);
  };
  add(project.name);
  for (const chunk of project.chunks ?? []) {
    for (const f of chunk.fields ?? []) {
      if (/server_name/i.test(f.key)) f.value.split(/\s+/).forEach(add);
      if (/^(ssl_certificate|ssl_certificate_key|ssl_trusted_certificate)$/i.test(f.key))
        add(domainFromCertPath(f.value));
      if (chunk.chunk_type === 'nginx_key' && (f.key === 'path' || f.key === 'name'))
        add(domainFromCertPath(f.value));
    }
    if (chunk.chunk_type === 'nginx_key') add(domainFromCertPath(chunk.name));
  }
  return [...out];
}

/** Find a `certificate` vault entry whose site (provider) matches the domain. */
export function certEntryForDomain(domain: string): VaultEntry | null {
  const d = normDomain(domain);
  return (
    st.vault.api_keys.find((e) => e.secretType === 'certificate' && normDomain(e.provider) === d) ||
    null
  );
}

/** Create (if missing) a stub `certificate` vault entry for a domain. Returns the entry. Does not save. */
export function ensureCertForDomain(domain: string, projectId?: string): VaultEntry {
  const existing = certEntryForDomain(domain);
  if (existing) return existing;
  const entry: VaultEntry = {
    provider: normDomain(domain),
    api_key: '',
    secretType: 'certificate',
    certificate_data: '',
    cert_key_data: '',
    price_type: 'free',
    categories: [],
    projectIds: ['Universal', ...(projectId && projectId !== 'Universal' ? [projectId] : [])],
    scopes: [],
    api_description: `TLS certificate for ${normDomain(domain)}`,
  };
  st.vault.api_keys.push(entry);
  return entry;
}

/** IDs of nginx_key chunks whose PEM content duplicates a shown cert entry (fullchain/privkey). */
export function redundantCertKeyChunkIds(project: Project): string[] {
  const pems = new Set<string>();
  for (const d of nginxCertDomains(project)) {
    const e = certEntryForDomain(d);
    if (e?.certificate_data) pems.add(e.certificate_data.trim());
    if (e?.cert_key_data) pems.add(e.cert_key_data.trim());
  }
  if (!pems.size) return [];
  return (project.chunks ?? [])
    .filter((c) => {
      if (c.chunk_type !== 'nginx_key') return false;
      const content = (c.fields.find((f) => f.key === 'content')?.value || '').trim();
      return !!content && pems.has(content);
    })
    .map((c) => c.id);
}

/** Big canonical card for a domain's certificate in the nginx view: full fullchain + privkey, or a create prompt. */
export function renderNginxCertCard(domain: string): string {
  const entry = certEntryForDomain(domain);
  if (!entry) {
    return `<div class="cert-link-card cert-link-card--missing">
      <div class="cert-link-head"><span class="cert-link-domain">${esc(domain)}</span></div>
      <div class="cert-link-empty">No certificate entry yet.</div>
      <button class="btn btn-ghost btn-sm" data-action="create-cert-stub" data-domain="${escAttr(domain)}">+ Create cert entry</button>
    </div>`;
  }
  const fc = entry.certificate_data || entry.api_key || '';
  const pk = entry.cert_key_data || '';
  const expiry = entry.expires_at ? new Date(entry.expires_at) : null;
  const now = new Date();
  const expired = expiry && expiry < now;
  const soon = expiry && !expired && expiry.getTime() - now.getTime() < 30 * 86_400_000;
  const expColor = expired ? 'var(--price-paid)' : soon ? '#f0ad4e' : 'var(--text3)';
  const expText = expiry
    ? `${expired ? 'EXPIRED ' : soon ? 'expires ' : 'exp '}${expiry.toISOString().slice(0, 10)}`
    : 'no expiry';

  const section = (label: string, pem: string) => {
    const blocks = pem
      .split(/(?=-----BEGIN )/)
      .map((s) => s.trim())
      .filter(Boolean);
    const certCount = blocks.filter((b) => b.includes('-----BEGIN CERTIFICATE-----')).length;
    const sub = label === 'Fullchain' && certCount > 1 ? ` · ${certCount} certs` : '';
    const body = blocks.length
      ? blocks.map((b) => `<pre class="cert-link-pem-full">${esc(b)}</pre>`).join('')
      : `<pre class="cert-link-pem-full cert-link-pem-empty">— empty —</pre>`;
    return `<div class="cert-link-section">
      <div class="cert-link-section-head">
        <span class="cert-link-section-label">${label}${sub}</span>
        ${pem ? `<button class="btn btn-ghost btn-xs" data-action="chunk-copy" data-value="${escAttr(pem)}" title="Copy PEM">Copy</button>` : ''}
      </div>
      ${body}
    </div>`;
  };

  return `<div class="cert-link-card cert-link-card--full">
    <div class="cert-link-head">
      <span class="cert-link-domain">${esc(entry.provider)}</span>
      ${entry.cert_issuer ? `<span class="cert-link-issuer" title="Issuer">${esc(entry.cert_issuer)}</span>` : ''}
      <span class="cert-link-expiry" style="color:${expColor}">${esc(expText)}</span>
      <button class="btn btn-ghost btn-xs" data-action="edit-cert-entry" data-provider="${escAttr(entry.provider)}" title="Edit certificate entry">Edit</button>
    </div>
    ${section('Fullchain', fc)}
    ${section('Privkey', pk)}
  </div>`;
}

// ── Nginx display helpers ──────────────────────────────────────────────────

/** Render an nginx listen directive as a badge row. */
function renderListenBadge(value: string): string {
  const raw = value.trim();
  const parts = raw.split(/\s+/);
  const addr = parts[0];
  const hasSSL = parts.includes('ssl');
  const hasH2 = parts.includes('http2');
  const hasH3 = parts.includes('http3');
  const isIpv6 = addr.startsWith('[');

  // Extract port from addr (could be "443", "[::]:443", "0.0.0.0:443")
  const portMatch = /:(\d+)$/.exec(addr) || /^(\d+)$/.exec(addr);
  const port = portMatch ? portMatch[1] : addr;

  return `<span class="listen-badge">
    ${isIpv6 ? `<span class="listen-tag listen-ipv6">ipv6</span>` : ''}
    <span class="listen-port">${esc(port)}</span>
    ${hasSSL ? `<span class="listen-tag listen-ssl">SSL</span>` : ''}
    ${hasH2 ? `<span class="listen-tag listen-proto">h2</span>` : ''}
    ${hasH3 ? `<span class="listen-tag listen-proto">h3</span>` : ''}
  </span>`;
}

/** Render server_name value as individual hostname badges. */
function renderServerNameBadges(value: string): string {
  return value
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((n) => `<span class="hostname-badge">${esc(n)}</span>`)
    .join('');
}

/** Render an nginx return directive as a redirect badge. */
function renderReturnBadge(value: string): string {
  const m = /^(\d{3})\s+(.+)$/.exec(value);
  if (!m) return esc(value);
  const code = m[1];
  const dest = m[2];
  const color = code === '301' ? '#4fc97e' : code === '302' ? '#f0ad4e' : 'var(--text2)';
  return `<span class="redirect-badge">
    <span class="redirect-status" style="color:${color}">${esc(code)}</span>
    <span class="redirect-arrow">→</span>
    <span class="redirect-dest">${esc(dest)}</span>
  </span>`;
}

// ── PEM normalization ──────────────────────────────────────────────────────

function normalizePem(raw: string): string {
  if (!raw) return '';
  // If already has newlines after header, it's fine
  if (/-----BEGIN [^-]+-----\n/.test(raw)) return raw.trim();
  // Re-wrap: split on -----BEGIN, reconstruct each block with 64-char lines
  return raw
    .replace(/-----BEGIN ([^-]+)-----([\s\S]*?)-----END \1-----/g, (_m, type, body) => {
      const b64 = body.replace(/\s+/g, '');
      const lines = b64.match(/.{1,64}/g) ?? [];
      return `-----BEGIN ${type}-----\n${lines.join('\n')}\n-----END ${type}-----`;
    })
    .trim();
}

// ── Chunk card renderer ────────────────────────────────────────────────────

export function renderChunkCard(chunk: SecretChunk, project: Project): HTMLElement {
  const card = document.createElement('div');
  card.className = `chunk-card${chunk.disabled ? ' chunk-disabled' : ''}`;
  const typeLabel = chunk.chunk_type.replace(/_/g, ' ');

  const isWg = chunk.chunk_type === 'wg_interface' || chunk.chunk_type === 'wg_peer';
  const isDockerSvc = chunk.chunk_type === 'docker_service';
  const isNginx = ['nginx_server', 'nginx_location', 'nginx_upstream'].includes(chunk.chunk_type);

  const chunkEnvFields = isDockerSvc
    ? chunk.fields.filter((f) => f.description === 'env' || f.field_type === 'env_var')
    : [];
  const hasChunkEnvFields = chunkEnvFields.length > 0;
  const hasChunkEnvRefs = chunkEnvFields.some((f) => /^\$\{.+\}$/.test(f.value));

  let fieldsHtml = '';
  for (const field of chunk.fields) {
    const { resolved, refName, unresolved, source: refSource } = resolveFieldRef(field.value);
    const isSecret = field.secret || field.field_type === 'secret';

    // Context-aware effective type — lets old imported data display smartly
    // without needing a data migration.
    let effType: ChunkFieldType = field.field_type;
    if (!isSecret && !refName) {
      if (isWg) {
        if (/^(Address|AllowedIPs)$/i.test(field.key)) effType = 'subnet';
        else if (/^DNS$/i.test(field.key)) effType = 'ip';
        else if (/^Endpoint$/i.test(field.key)) effType = 'endpoint';
        else if (/^ListenPort$/i.test(field.key)) effType = 'port';
        else if (/^(PostUp|PostDown|PreUp|PreDown)$/i.test(field.key)) effType = 'multiline';
      }
      if (isNginx) {
        if (/^listen$/i.test(field.key)) effType = 'port';
        else if (/^server_name$/i.test(field.key))
          effType = 'ip'; // repurpose as multi-badge via nginx branch
        else if (/^(ssl_certificate|ssl_certificate_key|ssl_trusted_certificate)$/i.test(field.key))
          effType = 'cert';
        else if (/^return$/i.test(field.key))
          effType = 'endpoint'; // repurpose; handled in nginx branch
        else if (/^(proxy_pass|fastcgi_pass|uwsgi_pass)$/i.test(field.key)) effType = 'endpoint';
        else if (/^(add_header|proxy_set_header|more_set_headers)$/i.test(field.key))
          effType = 'multiline';
      }
      if (field.field_type === 'cert') effType = 'cert';
      if (isDockerSvc && field.field_type === 'list') {
        if (field.key === 'volumes') effType = 'volume_mount';
      }
    }

    let displayVal = '';
    let badgeHtml = '';

    if (refName) {
      if (unresolved) {
        displayVal = `\${${refName}}`;
        badgeHtml = `<span class="chunk-ref-badge chunk-ref-unresolved" title="Not linked — no vault entry or .env field named '${esc(refName)}'">unresolved: ${esc(refName)}</span>`;
      } else if (refSource === 'env_file') {
        displayVal = '••••••••';
        badgeHtml = `<span class="chunk-ref-badge chunk-ref-env" title="Linked from .env chunk field '${esc(refName)}'">→ .env: ${esc(refName)}</span>`;
      } else if (refSource === 'chunk') {
        displayVal = '••••••••';
        badgeHtml = `<span class="chunk-ref-badge chunk-ref-chunk" title="Linked from chunk '${esc(refName)}'">→ chunk: ${esc(refName.replace(/^chunk:/, ''))}</span>`;
      } else {
        displayVal = '••••••••';
        badgeHtml = `<span class="chunk-ref-badge chunk-ref-jump" data-action="jump-ref" data-ref="${escAttr(refName)}" style="cursor:pointer" title="Click to open vault entry '${esc(refName)}'">→ vault: ${esc(refName)}</span>`;
      }
    } else if (isSecret && field.value) {
      displayVal = '••••••••';
    } else {
      displayVal = field.value || '';
    }

    const isEnvField =
      chunk.chunk_type === 'env_file' ||
      (isDockerSvc && (field.description === 'env' || field.field_type === 'env_var'));
    const envCopyResolved =
      isEnvField && refName ? resolveFieldRef(field.value, true).resolved : null;
    const valClass = `chunk-field-val${isSecret && field.value ? ' masked' : ''}`;
    // Copy format: KEY=VALUE for env, native config syntax for everything else.
    // Linked ${REF} fields copy the template string (not the resolved secret).
    const copyData = isEnvField
      ? `${field.key}=${field.value}`
      : refName
        ? chunkFieldCopyText(field.key, field.value, chunk.chunk_type)
        : isSecret
          ? field.value || ''
          : chunkFieldCopyText(field.key, field.value, chunk.chunk_type);
    const isMultiline = (effType === 'multiline' || effType === 'list') && !isSecret && !refName;
    const copyBtn =
      copyData !== undefined && copyData !== ''
        ? `<button class="icon-btn sm" data-action="chunk-copy" data-value="${escAttr(copyData)}" title="Copy">${copySVG}</button>`
        : '';
    const envCopyBtn =
      envCopyResolved !== null
        ? `<button class="btn btn-ghost btn-xs" data-action="chunk-copy" data-value="${escAttr(`${field.key}=${envCopyResolved}`)}" title="Copy resolved value">.env</button>`
        : '';

    // JSON object/array detection for pretty display
    let parsedJson: object | null = null;
    if (!isSecret && !refName && field.value) {
      const trimmed = field.value.trim();
      if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
        try {
          parsedJson = JSON.parse(trimmed) as object;
        } catch {}
      }
    }
    const isJsonVal = parsedJson !== null;

    const renderPortBadge = (portStr: string) => {
      const protoMatch = /\/(tcp|udp|sctp)$/i.exec(portStr);
      const proto = protoMatch ? protoMatch[1].toLowerCase() : '';
      const base = portStr.replace(/\/(tcp|udp|sctp)$/i, '');
      const parts = base.split(':');
      if (parts.length === 1) {
        return `<span class="port-badge"><span class="port-container">${esc(parts[0])}</span>${proto ? `<span class="port-proto">${esc(proto)}</span>` : ''}</span>`;
      }
      const host = parts[0];
      const container = parts.slice(1).join(':');
      return `<span class="port-badge"><span class="port-host">${esc(host)}</span><span class="port-arrow">→</span><span class="port-container">${esc(container)}</span>${proto ? `<span class="port-proto">${esc(proto)}</span>` : ''}</span>`;
    };

    const renderVolBadge = (str: string) => {
      const colon1 = str.indexOf(':');
      if (colon1 < 0)
        return `<span class="volume-badge"><span class="vol-name">${esc(str)}</span></span>`;
      const host = str.slice(0, colon1);
      const rest = str.slice(colon1 + 1);
      const modeMatch = /:?(ro|rw)$/.exec(rest);
      const mode = modeMatch ? modeMatch[1] : '';
      const container = mode ? rest.slice(0, rest.lastIndexOf(':')) : rest;
      const hostShort = host.length > 30 ? '…' + host.slice(host.lastIndexOf('/')) : host;
      return `<span class="volume-badge" title="${escAttr(str)}"><span class="vol-host">${esc(hostShort)}</span><span class="port-arrow">→</span><span class="vol-container">${esc(container)}</span>${mode ? `<span class="port-proto">${esc(mode)}</span>` : ''}</span>`;
    };

    if (isNginx && effType === 'port' && /^listen$/i.test(field.key)) {
      // nginx listen: parse port + SSL/http2 indicators
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val">${renderListenBadge(displayVal)}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (effType === 'port') {
      const portLines = (displayVal || '')
        .split(/\n/)
        .filter(Boolean)
        .map(renderPortBadge)
        .join('');
      fieldsHtml += `
        <div class="chunk-field-row multiline-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-actions">${copyBtn}</div>
          <div class="chunk-field-val port-list">${portLines || '<span style="color:var(--text3);font-size:10px">empty</span>'}</div>
        </div>`;
    } else if (effType === 'volume_mount') {
      const volLines = (displayVal || '').split(/\n/).filter(Boolean).map(renderVolBadge).join('');
      fieldsHtml += `
        <div class="chunk-field-row multiline-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-actions">${copyBtn}</div>
          <div class="chunk-field-val port-list">${volLines || '<span style="color:var(--text3);font-size:10px">empty</span>'}</div>
        </div>`;
    } else if (effType === 'subnet') {
      const cidrs = (displayVal || '')
        .split(/[\n,;]+/)
        .map((s) => s.trim())
        .filter(Boolean);
      const badges = cidrs.map((c) => `<span class="subnet-badge">${esc(c)}</span>`).join('');
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val badge-list">${badges || '<span style="color:var(--text3);font-size:10px">empty</span>'}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (isNginx && /^server_name$/i.test(field.key)) {
      // nginx server_name: each hostname as a badge
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val badge-list">${renderServerNameBadges(displayVal)}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (isNginx && /^return$/i.test(field.key)) {
      // nginx return: redirect badge — return has effType 'endpoint' from detection but handled here
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val">${renderReturnBadge(displayVal)}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (effType === 'ip') {
      const ips = (displayVal || '')
        .split(/[\n,;]+/)
        .map((s) => s.trim())
        .filter(Boolean);
      const badges = ips.map((ip) => `<span class="ip-badge">${esc(ip)}</span>`).join('');
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val badge-list">${badges || '<span style="color:var(--text3);font-size:10px">empty</span>'}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (effType === 'cert') {
      // SSL certificate / key: path + linked vault cert panel
      const isCertKey = /key/i.test(field.key);
      const linkedCert = findLinkedCert(field.value);
      const pathDisplay = refName
        ? `<span class="cert-ref-badge">${esc(displayVal)}</span>`
        : `<span class="chunk-field-val">${esc(displayVal)}</span>`;
      fieldsHtml += `
        <div class="chunk-field-row chunk-field-cert-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val">${pathDisplay}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>
        ${linkedCert ? renderCertPanel(linkedCert, isCertKey) : ''}`;
    } else if (effType === 'endpoint') {
      const lastColon = displayVal.lastIndexOf(':');
      const epHost = lastColon > 0 ? displayVal.slice(0, lastColon) : displayVal;
      const epPort = lastColon > 0 ? displayVal.slice(lastColon + 1) : '';
      const endpointBadge = `<span class="endpoint-badge"><span class="endpoint-host">${esc(epHost)}</span>${epPort ? `<span class="port-arrow">:</span><span class="endpoint-port">${esc(epPort)}</span>` : ''}</span>`;
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val">${endpointBadge}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (effType === 'list' && isDockerSvc && field.key === 'networks') {
      const nets = (displayVal || '')
        .split(/[\n,]+/)
        .map((s) => s.trim())
        .filter(Boolean);
      const badges = nets.map((n) => `<span class="net-badge">${esc(n)}</span>`).join('');
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val badge-list">${badges || '<span style="color:var(--text3);font-size:10px">empty</span>'}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (effType === 'list' && isDockerSvc && field.key === 'devices') {
      const devLines = (displayVal || '').split(/\n/).filter(Boolean).map(renderVolBadge).join('');
      fieldsHtml += `
        <div class="chunk-field-row multiline-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-actions">${copyBtn}</div>
          <div class="chunk-field-val port-list">${devLines || '<span style="color:var(--text3);font-size:10px">empty</span>'}</div>
        </div>`;
    } else if (effType === 'list' && isDockerSvc && field.key === 'cap_add') {
      const caps = (displayVal || '')
        .split(/[\n,]+/)
        .map((s) => s.trim())
        .filter(Boolean);
      const badges = caps.map((c) => `<span class="cap-badge">${esc(c)}</span>`).join('');
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val badge-list">${badges || '<span style="color:var(--text3);font-size:10px">empty</span>'}</div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else if (isJsonVal) {
      const formatted = JSON.stringify(parsedJson, null, 2);
      fieldsHtml += `
        <div class="chunk-field-row multiline-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-actions">${copyBtn}${envCopyBtn}</div>
          <pre class="${valClass} code-block">${esc(formatted)}</pre>
        </div>`;
    } else if (isMultiline) {
      fieldsHtml += `
        <div class="chunk-field-row multiline-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-actions">${copyBtn}</div>
          <pre class="${valClass} code-block">${esc(displayVal)}</pre>
        </div>`;
    } else if (isDockerSvc && field.key === 'image' && field.value && !isSecret && !refName) {
      const colonIdx = field.value.lastIndexOf(':');
      const hasTag = colonIdx > field.value.lastIndexOf('/');
      const tag = hasTag ? field.value.slice(colonIdx + 1) : '';
      const nameWithReg = hasTag ? field.value.slice(0, colonIdx) : field.value;
      const lastSlash = nameWithReg.lastIndexOf('/');
      const imgName = lastSlash >= 0 ? nameWithReg.slice(lastSlash + 1) : nameWithReg;
      const registry = lastSlash >= 0 ? nameWithReg.slice(0, lastSlash) : '';
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <div class="chunk-field-val">
            <span class="image-badge">
              ${registry ? `<span class="img-registry">${esc(registry)}/</span>` : ''}<span class="img-name">${esc(imgName)}</span>${tag ? `<span class="img-tag">:${esc(tag)}</span>` : ''}
            </span>
          </div>
          <div class="chunk-field-actions">${copyBtn}</div>
        </div>`;
    } else {
      let extraBadge = '';
      if (field.field_type === 'user_id' && field.value && !refName) {
        const [uid, gid] = field.value.split(':');
        extraBadge = `<span class="user-id-badge">uid:${esc(uid)}${gid ? `·gid:${esc(gid)}` : ''}</span>`;
      }
      fieldsHtml += `
        <div class="chunk-field-row">
          <span class="chunk-field-key">${esc(field.key)}</span>
          <span class="${valClass}">${esc(displayVal)} ${badgeHtml}${extraBadge}</span>
          <div class="chunk-field-actions">${copyBtn}${envCopyBtn}</div>
        </div>`;
    }
  }

  // Interface / nginx server / k8s deployment are "wide" chunks — span full grid width
  if (
    ['wg_interface', 'nginx_server', 'k8s_deployment', 'traefik_router'].includes(chunk.chunk_type)
  ) {
    card.classList.add('span-full');
  }

  // nginx_key: PEM certificate/key file — special display
  if (chunk.chunk_type === 'nginx_key') {
    const pid = escAttr(project.id);
    const cid = escAttr(chunk.id);
    const pathField = chunk.fields.find((f) => f.key === 'path');
    const keyTypeField = chunk.fields.find((f) => f.key === 'key_type');
    const contentField = chunk.fields.find((f) => f.key === 'content');
    const keyPath = pathField?.value || '';

    // Detect type: explicit field → path heuristic → default fullchain
    const isPrivkey =
      keyTypeField?.value === 'privkey' || (!keyTypeField && /privkey|private\.key/i.test(keyPath));
    const keyTypeLabel = isPrivkey ? 'privkey' : 'fullchain';
    const keyTypeCls = isPrivkey ? 'pem-key-badge' : 'pem-cert-badge';

    // Find nginx_server chunks that reference this path via ssl_certificate / ssl_certificate_key
    const certFields = ['ssl_certificate', 'ssl_certificate_key', 'ssl_trusted_certificate'];
    const usedBy = (project.chunks || []).filter(
      (c) =>
        c.chunk_type === 'nginx_server' &&
        c.fields.some((f) => certFields.includes(f.key) && f.value === keyPath),
    );

    const usedByHtml = usedBy.length
      ? usedBy
          .map(
            (c) =>
              `<span class="nginx-key-usedby-badge" title="ssl_certificate path matches">${esc(c.name)}</span>`,
          )
          .join('')
      : '';

    const pem = normalizePem(contentField?.value || '');
    const pemBlocks = pem
      .split(/(?=-----BEGIN )/)
      .map((s) => s.trim())
      .filter(Boolean);
    const renderPemBlock = (raw: string) => {
      const header = /^-----BEGIN ([^-]+)-----/.exec(raw)?.[1] ?? '';
      const cls = /CERTIFICATE/i.test(header)
        ? 'pem-cert'
        : /PRIVATE|RSA|EC|OPENSSH/i.test(header)
          ? 'pem-key'
          : 'pem-other';
      return `<div class="pem-block ${cls}"><div class="pem-label">${esc(header || 'PEM Block')}</div><pre class="pem-pre">${esc(raw)}</pre></div>`;
    };
    const certCount = pemBlocks.filter((b) => b.includes('-----BEGIN CERTIFICATE-----')).length;
    const chainLabel = !isPrivkey && certCount > 1 ? ` · ${certCount} certs` : '';
    const pemHtml = pemBlocks.length
      ? pemBlocks.map(renderPemBlock).join('')
      : `<div class="pem-empty">No PEM content — click Import or Edit to add</div>`;

    card.innerHTML = `
      <div class="chunk-card-head">
        <span class="chunk-card-title">${esc(chunk.name)}</span>
        <span class="chunk-type-badge ${keyTypeCls}">${keyTypeLabel}${chainLabel}</span>
        ${usedByHtml ? `<span class="nginx-key-usedby">${usedByHtml}</span>` : ''}
        <div style="display:flex;gap:4px;margin-left:auto;flex-shrink:0">
          <button class="btn btn-ghost btn-sm" data-action="import-nginx-key-file" data-project-id="${pid}" data-chunk-id="${cid}">Import file</button>
          <button class="btn btn-ghost btn-sm" data-action="copy-chunk-full"       data-project-id="${pid}" data-chunk-id="${cid}" title="Copy PEM">Copy</button>
          <button class="btn btn-ghost btn-sm" data-action="chunk-up"              data-project-id="${pid}" data-chunk-id="${cid}">↑</button>
          <button class="btn btn-ghost btn-sm" data-action="chunk-down"            data-project-id="${pid}" data-chunk-id="${cid}">↓</button>
          <button class="btn btn-ghost btn-sm" data-action="edit-chunk"            data-project-id="${pid}" data-chunk-id="${cid}">Edit</button>
          <button class="btn btn-ghost btn-sm" data-action="delete-chunk"          data-project-id="${pid}" data-chunk-id="${cid}" style="color:var(--price-paid)">Delete</button>
        </div>
      </div>
      ${keyPath ? `<div class="nginx-key-path">${esc(keyPath)}</div>` : ''}
      <div class="nginx-key-body">${pemHtml}</div>
    `;
    return card;
  }

  card.innerHTML = `
    <div class="chunk-card-head">
      <span class="chunk-card-title">${esc(chunk.name)}</span>
      <span class="chunk-type-badge">${esc(typeLabel)}</span>
      <div style="display:flex;gap:4px;margin-left:auto">
        <button class="btn btn-ghost btn-sm" data-action="copy-chunk-full" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}" title="Copy entire chunk in native format">Copy</button>
        ${chunk.chunk_type === 'env_file' ? `<button class="btn btn-ghost btn-sm" data-action="export-env-chunk" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}">Export .env</button>` : ''}
        ${chunk.chunk_type === 'env_file' ? `<button class="btn btn-ghost btn-sm" data-action="link-env-chunk" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}" title="Link fields to vault entries">Link</button>` : ''}
        ${hasChunkEnvRefs ? `<button class="btn btn-ghost btn-sm" data-action="copy-chunk-env" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}" title="Copy env fields with resolved secret values">Copy (resolved)</button>` : ''}
        <button class="btn btn-ghost btn-sm" data-action="chunk-up" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}" title="Move up">↑</button>
        <button class="btn btn-ghost btn-sm" data-action="chunk-down" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}" title="Move down">↓</button>
        <button class="btn btn-ghost btn-sm" data-action="dup-chunk" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}">Dup</button>
        <button class="btn btn-ghost btn-sm" data-action="edit-chunk" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}">Edit</button>
        <button class="btn btn-ghost btn-sm" data-action="delete-chunk" data-project-id="${escAttr(project.id)}" data-chunk-id="${escAttr(chunk.id)}" style="color:var(--price-paid)">Delete</button>
      </div>
    </div>
    ${chunk.notes ? `<div class="chunk-notes">${esc(chunk.notes)}</div>` : ''}
    <div class="chunk-fields">${fieldsHtml || '<div class="chunk-no-fields">No fields</div>'}</div>
  `;
  return card;
}

// ── Chunk → string (copy-chunk-full) ──────────────────────────────────────

function serviceChunkToYaml(sc: SecretChunk): string {
  const yamlStr = (v: string): string => {
    if (!v) return '""';
    if (/[\s:#\[\]{},|>&*!'"@`]/.test(v)) return JSON.stringify(v);
    return v;
  };
  const quoteItem = (v: string): string => (/\s/.test(v) ? JSON.stringify(v) : v);
  const svcName = sc.name.replace(/\s+/g, '_').toLowerCase();
  const out: string[] = [`${svcName}:`];

  const envFields: ChunkField[] = [];
  const portItems: string[] = [];
  const volumeItems: string[] = [];
  const listMap = new Map<string, string[]>();
  const scalars: [string, string][] = [];

  for (const f of sc.fields) {
    if (!f.key || f.key === 'restart') continue;
    if (f.description === 'env' || f.field_type === 'env_var') {
      envFields.push(f);
    } else if (f.key === 'ports' || f.field_type === 'port') {
      portItems.push(
        ...f.value
          .split(/[\n,]+/)
          .map((s) => s.trim())
          .filter(Boolean),
      );
    } else if (f.key === 'volumes' || f.field_type === 'volume_mount') {
      volumeItems.push(
        ...f.value
          .split(/\n/)
          .map((s) => s.trim())
          .filter(Boolean),
      );
    } else if (f.key === 'networks' || f.key === 'depends_on' || f.field_type === 'list') {
      if (!listMap.has(f.key)) listMap.set(f.key, []);
      listMap.get(f.key)!.push(
        ...f.value
          .split(/[\n,]+/)
          .map((s) => s.trim())
          .filter(Boolean),
      );
    } else if (f.value != null && f.value !== '') {
      scalars.push([f.key, f.value]);
    }
  }

  const PRIO = [
    'image',
    'container_name',
    'user',
    'hostname',
    'network_mode',
    'pid',
    'entrypoint',
    'command',
  ];
  const scalarMap = new Map(scalars);
  for (const k of PRIO) {
    if (scalarMap.has(k)) {
      out.push(`  ${k}: ${yamlStr(scalarMap.get(k)!)}`);
      scalarMap.delete(k);
    }
  }
  for (const [k, v] of scalarMap) out.push(`  ${k}: ${yamlStr(v)}`);

  if (portItems.length) {
    out.push('  ports:');
    for (const p of portItems) out.push(`    - ${JSON.stringify(p)}`);
  }
  if (envFields.length) {
    out.push('  environment:');
    for (const f of envFields) {
      const ref = f.ref_name || (/^\$\{(.+)}$/.exec(f.value) || [])[1];
      out.push(`    - ${f.key}=${ref ? `\${${ref}}` : (f.value ?? '')}`);
    }
  }
  if (volumeItems.length) {
    out.push('  volumes:');
    for (const v of volumeItems) out.push(`    - ${quoteItem(v)}`);
  }
  for (const [k, items] of listMap) {
    out.push(`  ${k}:`);
    for (const item of items) out.push(`    - ${yamlStr(item)}`);
  }
  const restartF = sc.fields.find((f) => f.key === 'restart');
  out.push(`  restart: ${restartF?.value || 'unless-stopped'}`);
  return out.join('\n');
}

/** Format a single chunk as its native config text for clipboard copy. */
export function chunkToString(chunk: SecretChunk): string {
  const isWg = chunk.chunk_type === 'wg_interface' || chunk.chunk_type === 'wg_peer';
  const isEnv = chunk.chunk_type === 'env_file';
  const isNginxBlock = ['nginx_server', 'nginx_location', 'nginx_upstream'].includes(
    chunk.chunk_type,
  );
  if (chunk.chunk_type === 'nginx_key') {
    return chunk.fields.find((f) => f.key === 'content')?.value ?? '';
  }
  const isTraefik = ['traefik_router', 'traefik_service', 'traefik_middleware'].includes(
    chunk.chunk_type,
  );
  const isK8s = ['k8s_deployment', 'k8s_service', 'k8s_ingress', 'k8s_configmap'].includes(
    chunk.chunk_type,
  );
  const isSsh = chunk.chunk_type === 'ssh_host';

  if (isWg) {
    const header = chunk.chunk_type === 'wg_interface' ? '[Interface]' : '[Peer]';
    const lines = [header];
    for (const f of chunk.fields) {
      // Resolve, like the env_file branch below and like exportWireGuard. The
      // old comment here said the caller would decide, but the only caller is
      // copy-to-clipboard and it does not resolve — so copying an Interface
      // pasted `PrivateKey = ${MyKey}` into wg0.conf and the tunnel would not
      // come up. A copied config has to be deployable.
      lines.push(`${f.key} = ${resolveFieldRef(f.value ?? '', true).resolved ?? f.value ?? ''}`);
    }
    return lines.join('\n');
  }

  if (isEnv) {
    // Resolve ${ref} values to actual secrets — a copied .env must be deployable.
    return chunk.fields
      .filter((f) => f.key)
      .map((f) => `${f.key}=${resolveFieldRef(f.value ?? '', true).resolved ?? f.value ?? ''}`)
      .join('\n');
  }

  if (isNginxBlock) {
    // `upstream` was folded in with `server`, so copying an upstream chunk
    // produced `server { server 10.0.0.1; }` — the wrong directive, with the
    // upstream's name dropped, which nginx rejects. exportNginx has always got
    // this right; the two disagreed.
    const blockType =
      chunk.chunk_type === 'nginx_location'
        ? 'location'
        : chunk.chunk_type === 'nginx_upstream'
          ? 'upstream'
          : 'server';
    const pathField = chunk.fields.find((f) => f.key === 'path');
    const blockName =
      chunk.chunk_type === 'nginx_location'
        ? pathField?.value
          ? ` ${pathField.value}`
          : ''
        : chunk.chunk_type === 'nginx_upstream'
          ? chunk.name
            ? ` ${chunk.name}`
            : ''
          : ''; // server block has no inline name
    const inner = chunk.fields
      .filter((f) => f.key && f.key !== 'path' && f.value)
      .map((f) => `    ${f.key} ${resolveFieldRef(f.value, true).resolved ?? f.value};`)
      .join('\n');
    return `${blockType}${blockName} {\n${inner}\n}`;
  }

  if (isSsh) {
    const lines = [`Host ${chunk.name}`];
    for (const f of chunk.fields) {
      if (f.key && f.value)
        lines.push(`    ${f.key} ${resolveFieldRef(f.value, true).resolved ?? f.value}`);
    }
    return lines.join('\n');
  }

  if (isTraefik || isK8s) {
    // YAML-like key: value
    return chunk.fields
      .filter((f) => f.key)
      .map((f) => `${f.key}: ${f.value ?? ''}`)
      .join('\n');
  }

  if (chunk.chunk_type === 'docker_service') {
    return serviceChunkToYaml(chunk);
  }

  // Generic unknown: key: value
  return chunk.fields
    .filter((f) => f.key)
    .map((f) => `${f.key}: ${f.value ?? ''}`)
    .join('\n');
}

// ── Export functions ───────────────────────────────────────────────────────

export function exportWireGuard(project: Project): string {
  const chunks = activeChunks(project);
  const sections: string[] = [];
  for (const chunk of chunks) {
    const header =
      chunk.chunk_type === 'wg_interface'
        ? '[Interface]'
        : chunk.chunk_type === 'wg_peer'
          ? '[Peer]'
          : `# ${chunk.name}`;
    const lines = [header];
    for (const field of chunk.fields) {
      if (!field.value) continue;
      // Use the shared resolver rather than matching `${PROVIDER}` by hand.
      // The hand-rolled version understood only the bare legacy form, so
      // `${Provider/field}`, `${Provider_KeyId}`, `${chunk:…}` and .env-backed
      // references were all written out as literal `${…}` text — producing a
      // wg0.conf with a placeholder where the private key should be, which
      // WireGuard then rejects.
      const { resolved } = resolveFieldRef(field.value, true);
      lines.push(`${field.key} = ${resolved ?? field.value}`);
    }
    sections.push(lines.join('\n'));
  }
  return sections.join('\n\n');
}

export function exportDockerCompose(project: Project): { yaml: string; envFile: string } {
  const chunks = activeChunks(project);
  const serviceChunks = chunks.filter((c) => c.chunk_type === 'docker_service');
  const networkChunks = chunks.filter((c) => c.chunk_type === 'docker_network');
  const volumeChunks = chunks.filter((c) => c.chunk_type === 'docker_volume');

  const out: string[] = ['# Generated by EnvVault', ''];
  const envLines: string[] = [];

  const yamlStr = (v: string): string => {
    if (!v) return '""';
    if (/[\s:#\[\]{},|>&*!'"@`]/.test(v)) return JSON.stringify(v);
    return v;
  };
  const quoteItem = (v: string): string => (/\s/.test(v) ? JSON.stringify(v) : v);

  if (networkChunks.length) {
    out.push('networks:');
    for (const nc of networkChunks) {
      for (const f of nc.fields) {
        if (!f.key) continue;
        out.push(`  ${f.key}:`);
        if (f.value) out.push(`    driver: ${f.value}`);
      }
      if (!nc.fields.length) out.push(`  ${nc.name}:`);
    }
    out.push('');
  }

  if (volumeChunks.length) {
    out.push('volumes:');
    for (const vc of volumeChunks) {
      for (const f of vc.fields) {
        if (f.key) out.push(`  ${f.key}:`);
      }
      if (!vc.fields.length) out.push(`  ${vc.name}:`);
    }
    out.push('');
  }

  if (serviceChunks.length) {
    out.push('services:');
    for (const sc of serviceChunks) {
      const svcName = sc.name.replace(/\s+/g, '_').toLowerCase();
      out.push(`  ${svcName}:`);

      const envFields: ChunkField[] = [];
      const portItems: string[] = [];
      const volumeItems: string[] = [];
      const listMap = new Map<string, string[]>();
      const scalars: [string, string][] = [];

      for (const f of sc.fields) {
        if (!f.key || f.key === 'restart') continue;
        if (f.description === 'env' || f.field_type === 'env_var') {
          envFields.push(f);
        } else if (f.key === 'ports' || f.field_type === 'port') {
          portItems.push(
            ...f.value
              .split(/[\n,]+/)
              .map((s) => s.trim())
              .filter(Boolean),
          );
        } else if (f.key === 'volumes' || f.field_type === 'volume_mount') {
          volumeItems.push(
            ...f.value
              .split(/\n/)
              .map((s) => s.trim())
              .filter(Boolean),
          );
        } else if (f.key === 'networks' || f.key === 'depends_on' || f.field_type === 'list') {
          const key = f.key;
          if (!listMap.has(key)) listMap.set(key, []);
          listMap.get(key)!.push(
            ...f.value
              .split(/[\n,]+/)
              .map((s) => s.trim())
              .filter(Boolean),
          );
        } else if (f.value != null && f.value !== '') {
          scalars.push([f.key, f.value]);
        }
      }

      // Scalars — priority order
      const PRIO = [
        'image',
        'container_name',
        'user',
        'hostname',
        'network_mode',
        'pid',
        'entrypoint',
        'command',
      ];
      const scalarMap = new Map(scalars);
      for (const k of PRIO) {
        if (scalarMap.has(k)) {
          out.push(`    ${k}: ${yamlStr(scalarMap.get(k)!)}`);
          scalarMap.delete(k);
        }
      }
      for (const [k, v] of scalarMap) out.push(`    ${k}: ${yamlStr(v)}`);

      // Ports
      if (portItems.length) {
        out.push('    ports:');
        for (const p of portItems) out.push(`      - ${JSON.stringify(p)}`);
      }

      // Environment: - KEY=value format
      if (envFields.length) {
        out.push('    environment:');
        for (const f of envFields) {
          const ref = f.ref_name || (/^\$\{(.+)}$/.exec(f.value) || [])[1];
          if (ref) {
            // Compose substitutes ${NAME} from the .env beside it, and NAME has
            // to be a valid shell identifier — a reference like `Provider/field`
            // is not one, so derive the variable name from the field key.
            const varName = f.key.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
            out.push(`      - ${f.key}=\${${varName}}`);
            // Resolve through the shared resolver: matching provider names by
            // hand only understood the bare `${PROVIDER}` form, so every other
            // reference shape wrote an empty value into the .env file and the
            // container started with a blank secret.
            const { resolved } = resolveFieldRef(f.value ?? '', true);
            envLines.push(`${varName}=${resolved ?? ''}`);
          } else {
            out.push(`      - ${f.key}=${f.value ?? ''}`);
          }
        }
      }

      // Volumes
      if (volumeItems.length) {
        out.push('    volumes:');
        for (const v of volumeItems) out.push(`      - ${quoteItem(v)}`);
      }

      // Networks, depends_on, and other lists
      for (const [k, items] of listMap) {
        out.push(`    ${k}:`);
        for (const item of items) out.push(`      - ${yamlStr(item)}`);
      }

      // Restart
      const restartF = sc.fields.find((f) => f.key === 'restart');
      out.push(`    restart: ${restartF?.value || 'unless-stopped'}`);
      out.push('');
    }
  }

  return { yaml: out.join('\n'), envFile: envLines.join('\n') };
}

export function exportServicesSection(project: Project): string {
  const svcChunks = activeChunks(project).filter((c) => c.chunk_type === 'docker_service');
  if (!svcChunks.length) return '';
  const lines = ['services:'];
  for (const sc of svcChunks) {
    serviceChunkToYaml(sc)
      .split('\n')
      .forEach((l) => lines.push('  ' + l));
    lines.push('');
  }
  return lines.join('\n');
}

export function renderDockerServicesCard(project: Project): HTMLElement {
  const pid = escAttr(project.id);
  const svcChunks = (project.chunks || []).filter((c) => c.chunk_type === 'docker_service');

  const makeSubCard = (label: string, bodyHtml: string): string =>
    `<div class="docker-sub-card">
      <div class="docker-sub-card-label">${esc(label)}</div>
      <div class="docker-sub-card-body">${bodyHtml}</div>
    </div>`;

  const renderSvcCard = (sc: SecretChunk): string => {
    const cid = escAttr(sc.id);
    const envFields: ChunkField[] = [];
    const portItems: string[] = [];
    const volumeItems: string[] = [];
    const listMap = new Map<string, string[]>();
    const scalars: [string, string][] = [];

    for (const f of sc.fields) {
      if (!f.key) continue;
      if (f.description === 'env' || f.field_type === 'env_var') {
        envFields.push(f);
      } else if (f.key === 'ports' || f.field_type === 'port') {
        portItems.push(
          ...f.value
            .split(/[\n,]+/)
            .map((s) => s.trim())
            .filter(Boolean),
        );
      } else if (f.key === 'volumes' || f.field_type === 'volume_mount') {
        volumeItems.push(
          ...f.value
            .split(/\n/)
            .map((s) => s.trim())
            .filter(Boolean),
        );
      } else if (f.key === 'networks' || f.key === 'depends_on' || f.field_type === 'list') {
        if (!listMap.has(f.key)) listMap.set(f.key, []);
        listMap.get(f.key)!.push(
          ...f.value
            .split(/[\n,]+/)
            .map((s) => s.trim())
            .filter(Boolean),
        );
      } else if (f.value != null && f.value !== '') {
        scalars.push([f.key, f.value]);
      }
    }

    const PRIO = [
      'image',
      'container_name',
      'user',
      'hostname',
      'network_mode',
      'pid',
      'entrypoint',
      'command',
      'restart',
    ];
    const scalarMap = new Map(scalars);
    let scalarsHtml = '';
    for (const k of PRIO) {
      if (scalarMap.has(k)) {
        scalarsHtml += `<div class="dsvc-field"><span class="dsvc-key">${esc(k)}</span><span class="dsvc-val">${esc(scalarMap.get(k)!)}</span></div>`;
        scalarMap.delete(k);
      }
    }
    for (const [k, v] of scalarMap) {
      scalarsHtml += `<div class="dsvc-field"><span class="dsvc-key">${esc(k)}</span><span class="dsvc-val">${esc(v)}</span></div>`;
    }

    let subCards = '';

    if (envFields.length) {
      let envBody = '';
      for (const f of envFields) {
        const { refName, unresolved, source } = resolveFieldRef(f.value);
        const valDisplay = refName ? (unresolved ? `\${${refName}}` : '••••••••') : (f.value ?? '');
        let badge = '';
        if (refName) {
          if (unresolved) {
            badge = `<span class="chunk-ref-badge chunk-ref-unresolved" title="Not linked — no vault entry or .env field named '${esc(refName!)}'">${esc(refName!)}</span>`;
          } else if (source === 'env_file') {
            badge = `<span class="chunk-ref-badge chunk-ref-env" title="Linked from .env: ${esc(refName!)}">→ .env</span>`;
          } else {
            badge = `<span class="chunk-ref-badge" title="Linked from vault: ${esc(refName!)}">→ vault</span>`;
          }
        }
        envBody += `<div class="dsvc-env-row"><span class="dsvc-env-key">${esc(f.key)}</span><span class="dsvc-env-eq">=</span><span class="dsvc-env-val">${esc(valDisplay)}</span>${badge ? `<span class="dsvc-env-badge">${badge}</span>` : ''}</div>`;
      }
      subCards += makeSubCard('environment', envBody);
    }

    if (portItems.length) {
      let portBody = '';
      for (const p of portItems) {
        const parts = p.split(':');
        const inner =
          parts.length >= 2
            ? `<span class="dsvc-port-host">${esc(parts[0])}</span><span class="dsvc-port-sep">→</span><span class="dsvc-port-cont">${esc(parts.slice(1).join(':'))}</span>`
            : `<span class="dsvc-port-cont">${esc(p)}</span>`;
        portBody += `<div class="dsvc-list-item"><span class="dsvc-port-badge">${inner}</span></div>`;
      }
      subCards += makeSubCard('ports', portBody);
    }

    if (volumeItems.length) {
      let volBody = '';
      for (const v of volumeItems) {
        const parts = v.split(':');
        const inner =
          parts.length >= 2
            ? `<span class="dsvc-vol-host">${esc(parts[0])}</span><span class="dsvc-vol-sep">:</span><span class="dsvc-vol-cont">${esc(parts.slice(1).join(':'))}</span>`
            : `<span class="dsvc-vol-host">${esc(v)}</span>`;
        volBody += `<div class="dsvc-list-item"><span class="dsvc-vol-badge">${inner}</span></div>`;
      }
      subCards += makeSubCard('volumes', volBody);
    }

    for (const [k, items] of listMap) {
      const listBody = items
        .map(
          (item) =>
            `<div class="dsvc-list-item"><span class="dsvc-net-badge">${esc(item)}</span></div>`,
        )
        .join('');
      subCards += makeSubCard(k, listBody);
    }

    return `<div class="docker-service-card" data-chunk-id="${cid}">
      <div class="docker-service-header">
        <span class="docker-service-name">${esc(sc.name)}</span>
        <div class="docker-service-actions">
          <button class="btn btn-ghost btn-xs" data-action="copy-chunk-full" data-project-id="${pid}" data-chunk-id="${cid}" title="Copy YAML">${copySVG}</button>
          <button class="btn btn-ghost btn-xs" data-action="chunk-up"    data-project-id="${pid}" data-chunk-id="${cid}">↑</button>
          <button class="btn btn-ghost btn-xs" data-action="chunk-down"  data-project-id="${pid}" data-chunk-id="${cid}">↓</button>
          <button class="btn btn-ghost btn-xs" data-action="edit-chunk"  data-project-id="${pid}" data-chunk-id="${cid}">${editSVG}</button>
          <button class="btn btn-ghost btn-xs" data-action="delete-chunk" data-project-id="${pid}" data-chunk-id="${cid}" style="color:var(--price-paid)">${delSVG}</button>
        </div>
      </div>
      ${scalarsHtml ? `<div class="docker-service-scalars">${scalarsHtml}</div>` : ''}
      ${subCards ? `<div class="docker-service-subcards">${subCards}</div>` : ''}
      ${!scalarsHtml && !subCards ? '<div class="dsvc-empty">No fields — click Edit to configure</div>' : ''}
    </div>`;
  };

  const card = document.createElement('div');
  card.className = 'chunk-card docker-services-card';
  card.innerHTML = `
    <div class="chunk-card-head">
      <span class="chunk-card-title">Services</span>
      ${svcChunks.length ? `<span class="chunk-type-badge">${svcChunks.length} service${svcChunks.length !== 1 ? 's' : ''}</span>` : ''}
      <div style="display:flex;gap:4px;margin-left:auto;flex-shrink:0">
        <button class="btn btn-ghost btn-sm" data-action="import-docker"          data-project-id="${pid}">Import</button>
        <button class="btn btn-ghost btn-sm" data-action="add-docker-service"     data-project-id="${pid}">+ Service</button>
        <button class="btn btn-ghost btn-sm" data-action="export-docker"          data-project-id="${pid}">Export</button>
        <button class="btn btn-ghost btn-sm" data-action="export-docker-services" data-project-id="${pid}" title="Copy services: block">${copySVG} All</button>
      </div>
    </div>
    <div class="docker-services-body">
      ${svcChunks.map(renderSvcCard).join('')}
      ${!svcChunks.length ? '<div class="chunk-no-fields">No services yet — click Import or + Service</div>' : ''}
    </div>
  `;
  return card;
}

export function getProjectTypeLabel(type: ProjectType): string {
  return (
    (
      {
        wireguard: 'WireGuard',
        docker: 'Docker',
        nginx: 'Nginx',
        kubernetes: 'Kubernetes',
        ssh_config: 'SSH Config',
        traefik: 'Traefik',
        apache: 'Apache',
        haproxy: 'HAProxy',
        ansible: 'Ansible',
        postgres: 'PostgreSQL',
        generic: 'Generic',
      } as Record<string, string>
    )[type] ?? type
  );
}

export function makeConfigViewHeaderBtns(project: Project): string {
  const pid = escAttr(project.id);
  switch (project.project_type) {
    case 'wireguard':
      return `<button class="btn btn-ghost btn-sm" data-action="import-wg" data-project-id="${pid}">Import wg0.conf</button>
              <button class="btn btn-ghost btn-sm" data-action="add-wg-peer" data-project-id="${pid}">+ Add Peer</button>
              <button class="btn btn-ghost btn-sm" data-action="export-wg" data-project-id="${pid}">Export wg0.conf</button>`;
    case 'docker':
      return `<button class="btn btn-ghost btn-sm" data-action="add-docker-network" data-project-id="${pid}">+ Network</button>
              <button class="btn btn-ghost btn-sm" data-action="add-docker-volume" data-project-id="${pid}">+ Volume</button>`;
    case 'nginx':
      return `<button class="btn btn-ghost btn-sm" data-action="import-nginx" data-project-id="${pid}">Import site config</button>
              <button class="btn btn-ghost btn-sm" data-action="add-nginx-server" data-project-id="${pid}">+ Server</button>
              <button class="btn btn-ghost btn-sm" data-action="add-nginx-upstream" data-project-id="${pid}">+ Upstream</button>
              <button class="btn btn-ghost btn-sm" data-action="add-nginx-location" data-project-id="${pid}">+ Location</button>
              <button class="btn btn-ghost btn-sm" data-action="add-nginx-key" data-project-id="${pid}">+ Key File</button>
              <button class="btn btn-ghost btn-sm" data-action="export-nginx" data-project-id="${pid}">Export nginx.conf</button>`;
    case 'kubernetes':
      return `<button class="btn btn-ghost btn-sm" data-action="add-k8s-deployment" data-project-id="${pid}">+ Deploy</button>
              <button class="btn btn-ghost btn-sm" data-action="add-k8s-service" data-project-id="${pid}">+ Service</button>
              <button class="btn btn-ghost btn-sm" data-action="add-k8s-configmap" data-project-id="${pid}">+ ConfigMap</button>
              <button class="btn btn-ghost btn-sm" data-action="add-k8s-secret" data-project-id="${pid}">+ Secret</button>
              <button class="btn btn-ghost btn-sm" data-action="add-k8s-ingress" data-project-id="${pid}">+ Ingress</button>
              <button class="btn btn-ghost btn-sm" data-action="export-k8s" data-project-id="${pid}">Export YAML</button>`;
    case 'ssh_config':
      return `<button class="btn btn-ghost btn-sm" data-action="import-ssh" data-project-id="${pid}">Import Config</button>
              <button class="btn btn-ghost btn-sm" data-action="add-ssh-host" data-project-id="${pid}">+ Add Host</button>
              <button class="btn btn-ghost btn-sm" data-action="export-ssh" data-project-id="${pid}">Export ~/.ssh/config</button>`;
    case 'traefik':
      return `<button class="btn btn-ghost btn-sm" data-action="add-traefik-router" data-project-id="${pid}">+ Router</button>
              <button class="btn btn-ghost btn-sm" data-action="add-traefik-service" data-project-id="${pid}">+ Service</button>
              <button class="btn btn-ghost btn-sm" data-action="add-traefik-middleware" data-project-id="${pid}">+ Middleware</button>
              <button class="btn btn-ghost btn-sm" data-action="export-traefik" data-project-id="${pid}">Export traefik.yaml</button>`;
    case 'apache':
      return `<button class="btn btn-ghost btn-sm" data-action="import-apache" data-project-id="${pid}">Import httpd.conf</button>
              <button class="btn btn-ghost btn-sm" data-action="add-apache-vhost" data-project-id="${pid}">+ VirtualHost</button>
              <button class="btn btn-ghost btn-sm" data-action="add-apache-directory" data-project-id="${pid}">+ Directory</button>
              <button class="btn btn-ghost btn-sm" data-action="export-apache" data-project-id="${pid}">Export config</button>`;
    case 'haproxy':
      return `<button class="btn btn-ghost btn-sm" data-action="import-haproxy" data-project-id="${pid}">Import haproxy.cfg</button>
              <button class="btn btn-ghost btn-sm" data-action="add-haproxy-frontend" data-project-id="${pid}">+ Frontend</button>
              <button class="btn btn-ghost btn-sm" data-action="add-haproxy-backend" data-project-id="${pid}">+ Backend</button>
              <button class="btn btn-ghost btn-sm" data-action="export-haproxy" data-project-id="${pid}">Export haproxy.cfg</button>`;
    case 'ansible':
      return `<button class="btn btn-ghost btn-sm" data-action="add-ansible-vars" data-project-id="${pid}">+ vars</button>
              <button class="btn btn-ghost btn-sm" data-action="add-ansible-task" data-project-id="${pid}">+ task</button>
              <button class="btn btn-ghost btn-sm" data-action="export-ansible" data-project-id="${pid}">Export YAML</button>`;
    case 'postgres':
      return `<button class="btn btn-ghost btn-sm" data-action="add-pg-connection" data-project-id="${pid}">+ Connection</button>
              <button class="btn btn-ghost btn-sm" data-action="add-pg-role" data-project-id="${pid}">+ Role</button>
              <button class="btn btn-ghost btn-sm" data-action="export-postgres" data-project-id="${pid}">Export .pgpass</button>`;
    default:
      return '';
  }
}

export function exportNginx(project: Project): string {
  const chunks = activeChunks(project);
  const upstreams = chunks.filter((c) => c.chunk_type === 'nginx_upstream');
  const servers = chunks.filter((c) => c.chunk_type === 'nginx_server');
  const locations = chunks.filter((c) => c.chunk_type === 'nginx_location');
  const lines: string[] = ['# Generated by EnvVault', ''];

  // Resolve, as every other exporter does. This one interpolated `f.value`
  // raw, so an `ssl_certificate ${TLS}` written by the starter template reached
  // nginx as the literal text `${TLS}` and the server refused to start — while
  // copying the same chunk from the card resolved it correctly, so the two
  // disagreed about what the config said.
  const rv = (v: string) => resolveFieldRef(v ?? '', true).resolved ?? v ?? '';

  for (const u of upstreams) {
    lines.push(`upstream ${u.name} {`);
    for (const f of u.fields) {
      if (!f.value) continue;
      if (f.key === 'server') {
        for (const v of rv(f.value)
          .split(/[\n,]+/)
          .map((s) => s.trim())
          .filter(Boolean))
          lines.push(`    server ${v};`);
      } else {
        lines.push(`    ${f.key} ${rv(f.value)};`);
      }
    }
    lines.push('}', '');
  }

  for (const s of servers) {
    lines.push('server {');
    for (const f of s.fields) {
      if (f.value) lines.push(`    ${f.key} ${rv(f.value)};`);
    }
    if (locations.length) {
      lines.push('');
      for (const loc of locations) {
        const path = loc.fields.find((f) => f.key === 'path')?.value || '/';
        lines.push(`    location ${path} {`);
        for (const f of loc.fields) {
          if (f.key !== 'path' && f.value) lines.push(`        ${f.key} ${rv(f.value)};`);
        }
        lines.push('    }');
      }
    }
    lines.push('}', '');
  }
  return lines.join('\n');
}

/**
 * Base64 of a string's UTF-8 bytes, as Kubernetes `Secret.data` requires.
 *
 * `btoa` operates on Latin-1 code units, which broke this two ways: any
 * character above U+00FF (an emoji, CJK, anything outside Latin-1) threw
 * `InvalidCharacterError` and took the whole export down, and a character in
 * U+0080–U+00FF — `é`, `£`, `ü` — encoded its Latin-1 byte instead of its UTF-8
 * bytes, so the cluster silently decoded a *different* secret than the one
 * stored. The quiet corruption is the worse of the two.
 */
function b64Utf8(s: string): string {
  const bytes = new TextEncoder().encode(s);
  const CHUNK = 0x8000;
  let bin = '';
  for (let i = 0; i < bytes.length; i += CHUNK) {
    bin += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(bin);
}

export function exportK8s(project: Project): string {
  const manifests: string[] = [];
  for (const chunk of activeChunks(project)) {
    const name = chunk.fields.find((f) => f.key === 'name')?.value || chunk.name;
    const ns = chunk.fields.find((f) => f.key === 'namespace')?.value || 'default';
    if (chunk.chunk_type === 'k8s_deployment') {
      const image = chunk.fields.find((f) => f.key === 'image')?.value || 'nginx:latest';
      const replicas = chunk.fields.find((f) => f.key === 'replicas')?.value || '1';
      const port = chunk.fields.find((f) => f.key === 'containerPort')?.value || '80';
      const envFields = chunk.fields.filter(
        (f) => f.field_type === 'env_var' || f.field_type === 'secret',
      );
      const envBlock = envFields.length
        ? '\n        env:' +
          envFields
            .map(
              (f) => `\n          - name: ${f.key}\n            value: ${JSON.stringify(f.value)}`,
            )
            .join('')
        : '';
      manifests.push(
        `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ${name}\n  namespace: ${ns}\nspec:\n  replicas: ${replicas}\n  selector:\n    matchLabels:\n      app: ${name}\n  template:\n    metadata:\n      labels:\n        app: ${name}\n    spec:\n      containers:\n        - name: ${name}\n          image: ${image}\n          ports:\n            - containerPort: ${port}${envBlock}`,
      );
    } else if (chunk.chunk_type === 'k8s_service') {
      const port = chunk.fields.find((f) => f.key === 'port')?.value || '80';
      const targetPort = chunk.fields.find((f) => f.key === 'targetPort')?.value || '80';
      const type = chunk.fields.find((f) => f.key === 'type')?.value || 'ClusterIP';
      manifests.push(
        `apiVersion: v1\nkind: Service\nmetadata:\n  name: ${name}\n  namespace: ${ns}\nspec:\n  selector:\n    app: ${name}\n  type: ${type}\n  ports:\n    - port: ${port}\n      targetPort: ${targetPort}`,
      );
    } else if (chunk.chunk_type === 'k8s_configmap') {
      const dataFields = chunk.fields.filter((f) => f.key !== 'name' && f.key !== 'namespace');
      manifests.push(
        `apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: ${name}\n  namespace: ${ns}\ndata:\n${dataFields.map((f) => `  ${f.key}: ${JSON.stringify(f.value)}`).join('\n')}`,
      );
    } else if (chunk.chunk_type === 'k8s_secret') {
      const dataFields = chunk.fields.filter((f) => f.key !== 'name' && f.key !== 'namespace');
      // Resolve references before encoding — a field holding `${DB_PASSWORD}`
      // was base64'd literally, shipping the placeholder text to the cluster as
      // if it were the secret.
      manifests.push(
        `apiVersion: v1\nkind: Secret\nmetadata:\n  name: ${name}\n  namespace: ${ns}\ntype: Opaque\ndata:\n${dataFields.map((f) => `  ${f.key}: ${b64Utf8(resolveFieldRef(f.value ?? '', true).resolved ?? f.value ?? '')}`).join('\n')}`,
      );
    } else if (chunk.chunk_type === 'k8s_ingress') {
      const host = chunk.fields.find((f) => f.key === 'host')?.value || 'example.com';
      const svcName = chunk.fields.find((f) => f.key === 'serviceName')?.value || name;
      const svcPort = chunk.fields.find((f) => f.key === 'servicePort')?.value || '80';
      manifests.push(
        `apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: ${name}\n  namespace: ${ns}\nspec:\n  rules:\n    - host: ${host}\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service:\n                name: ${svcName}\n                port:\n                  number: ${svcPort}`,
      );
    }
  }
  return manifests.join('\n---\n');
}

export function exportSshConfig(project: Project): string {
  const lines: string[] = ['# Generated by EnvVault', ''];
  for (const chunk of activeChunks(project)) {
    if (chunk.chunk_type !== 'ssh_host') continue;
    lines.push(`Host ${chunk.name}`);
    for (const f of chunk.fields) {
      if (f.value) lines.push(`    ${f.key} ${xv(f.value)}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function exportTraefik(project: Project): string {
  const chunks = activeChunks(project);
  const routers = chunks.filter((c) => c.chunk_type === 'traefik_router');
  const services = chunks.filter((c) => c.chunk_type === 'traefik_service');
  const middlewares = chunks.filter((c) => c.chunk_type === 'traefik_middleware');
  const lines: string[] = ['# Generated by EnvVault', 'http:'];

  if (routers.length) {
    lines.push('  routers:');
    for (const r of routers) {
      lines.push(`    ${r.name}:`);
      for (const f of r.fields) {
        if (!f.value) continue;
        if (f.field_type === 'list') {
          lines.push(`      ${f.key}:`);
          for (const item of xv(f.value)
            .split(/[\n,]+/)
            .map((s) => s.trim())
            .filter(Boolean))
            lines.push(`        - ${item}`);
        } else {
          lines.push(`      ${f.key}: ${JSON.stringify(xv(f.value))}`);
        }
      }
    }
  }
  if (services.length) {
    lines.push('  services:');
    for (const s of services) {
      const url = xv(s.fields.find((f) => f.key === 'url')?.value);
      const passHost = xv(s.fields.find((f) => f.key === 'passHostHeader')?.value) || 'true';
      lines.push(`    ${s.name}:`, `      loadBalancer:`, `        passHostHeader: ${passHost}`);
      if (url) {
        lines.push(`        servers:`, `          - url: ${JSON.stringify(url)}`);
      }
    }
  }
  if (middlewares.length) {
    lines.push('  middlewares:');
    for (const m of middlewares) {
      const type = xv(m.fields.find((f) => f.key === 'type')?.value);
      lines.push(`    ${m.name}:`);
      if (type) {
        lines.push(`      ${type}:`);
        for (const f of m.fields) {
          if (f.key !== 'type' && f.value) lines.push(`        ${f.key}: ${xv(f.value)}`);
        }
      }
    }
  }
  return lines.join('\n');
}

export function pickFileText(
  accept: string,
  cb: (text: string, name: string) => void | Promise<void>,
): void {
  const inp = document.createElement('input');
  inp.type = 'file';
  inp.accept = accept;
  document.body.appendChild(inp);
  let done = false;
  const cleanup = () => {
    if (done) return;
    done = true;
    if (document.body.contains(inp)) document.body.removeChild(inp);
  };
  inp.addEventListener(
    'change',
    function () {
      const file = (this as HTMLInputElement).files?.[0];
      if (!file) {
        cleanup();
        return;
      }
      const reader = new FileReader();
      reader.onload = (ev) => cb(ev.target!.result as string, file.name);
      reader.readAsText(file);
      cleanup();
    },
    { once: true },
  );
  inp.addEventListener('cancel', cleanup, { once: true });
  inp.click();
  setTimeout(() => window.addEventListener('focus', cleanup, { once: true }), 300);
}
