import { buildBundle, bundleSuggestions } from './bundle-scope';
import { codeStatus, markUsed, nextCode } from './recovery-codes';
import { hideWifiQr } from './wifi-qr';
import {
  st,
  Settings,
  TauriVaultStore,
  LocalVaultStore,
  RemoteVaultStore,
  inTauri,
  setRenderFn,
  triggerRender,
  switchPanel,
  persist,
  entryId,
  ensureEntryIds,
  backfillCreatedAt,
  applyUsersPanelVisibility,
  applySidebarLayout,
  saveViewState,
  restoreViewState,
  clearAllFilters,
  SIDEBAR_MIN_W,
  SIDEBAR_MAX_W,
} from './state';
import type { AppSettings, VaultEntry } from './types';
import { initIconPicker, openIconPicker, iconHTML } from './icons';
import {
  showToast,
  errorMessage,
  showConfirm,
  showPrompt,
  showPasswordPrompt,
  clipboardWrite,
  saveFile,
} from './utils';
import { poolsOf, poolNext } from './pools';
import {
  CustomSelect,
  DropdownItem,
  TYPE_CONFIG,
  showDropdown,
  showContextMenu,
  dynamicSecretFields,
  openAdd,
  openEdit,
  closeModal,
  saveModal,
  duplicateKey,
  deleteKey,
  quickGenerate,
  toggleCard,
  toggleReveal,
  copyField,
  doCopyEnv,
  openCopyEnvMenu,
  onIconWrapClick,
  markAsRotated,
  suggestExtraVarsForType,
  confirmBundleMemberReferenceBreakage,
  pushUndo,
} from './modals';
import { renameBundleSlotRefs } from './bundle-scope';
import { buildBundleExport, type BundleExportFormat } from './copy-profile';
import {
  doSetFilter,
  openProjectCreateModal,
  closeProjectCreateModal,
  saveProjectCreate,
  setProjectCreateType,
  openCategoryCreateModal,
  closeCategoryCreateModal,
  saveCategoryCreate,
  deleteCategory,
  renameCategory,
  renameProject,
  deleteProject,
} from './projects';
import {
  copyAll,
  exportAs,
  handleFileSelect,
  closeEnvImportModal,
  confirmEnvImport,
  exportK8sSecret,
  exportTfvars,
  exportEncryptedBackup,
  importEncryptedBackup,
} from './import-export';
import { openSettings, saveSettings, closeSettings, cancelSettings } from './settings-panel';
import { lockVault, resetLock, showUnlockModal, setFinishInitFn } from './lock';
import { initTools } from './tools';
import { mountToolsPanes } from './tools-markup';
import { initUsersPanel } from './users';
import { initAuthPanel } from './auth-panel';
import { startVaultWatch } from './vault-watch';
import {
  initRemotePanel,
  setRemoteFinishInitFn,
  renderRemotePanel,
  switchToLocalVault,
} from './remote-panel';
import { initLanPanel } from './lan';
import { showOnboarding, shouldShowOnboarding } from './onboarding';
import { render, renderGrid, updateCopyAllBtn, closeEnvLinkModal, applyEnvLink } from './render';
import {
  closeChunkEditModal,
  saveChunkEdit,
  renderChunkEditFields,
  readChunkEditFields,
} from './chunk-ops';
import { wireSearchHistory, closeSearchHistory, wireCloseGuard, wireModalFocus } from './ui-qol';
import type { ProjectType, SecretType } from './types';
import { EXPORT_FORMATS, runTotpExport, runTotpImport } from './totp-io';
import { runCxfImport, runCxfExport } from './cxf-io';
import { setHtml } from './html';

// Wire the global render callback so all modules can call triggerRender()
setRenderFn(render);
setFinishInitFn(finishInit);

/* ================================ BOOTSTRAP ================================ */

/** Grid sort modes. Module-level so the persisted value can be validated against it. */
const SORT_OPTIONS = [
  { value: 'provider', label: 'A – Z' },
  { value: 'price', label: 'Price Type' },
  { value: 'category', label: 'Category' },
  { value: 'expiry', label: 'Expiry' },
];

/**
 * Applies the persisted sort mode and syncs the toolbar label to it.
 *
 * The stored value is checked against SORT_OPTIONS rather than trusted: an
 * unrecognised mode falls through every branch of `sorted()` and leaves the
 * grid in insertion order while the button claims otherwise.
 */

function restoreSort(): void {
  const saved = Settings.get('lastSortBy');
  const opt = SORT_OPTIONS.find((o) => o.value === saved);
  if (!opt) return;
  st.currentSortBy = opt.value;
  const labelEl = document.getElementById('sort-label-text');
  if (labelEl) labelEl.textContent = opt.label;
}

/**
 * Copy the authenticator code shown at `el`'s slot.
 *
 * Reads the code the ticker last painted (`data-totp-code` on the
 * `[data-totp-for]` container) rather than re-deriving it, so what lands on the
 * clipboard is what the user was looking at. Re-deriving would hand them the
 * *next* code if the click crossed a step boundary — the one failure that is
 * both invisible and guaranteed to be blamed on the website.
 */
function copyTotpFrom(el: HTMLElement): void {
  const slot = el.closest<HTMLElement>('[data-totp-for]');
  const code = slot?.dataset.totpCode ?? '';
  if (!code) {
    showToast(
      inTauri ? 'No code yet — try again in a moment' : 'Codes are generated by the desktop app',
      'err',
      2000,
    );
    return;
  }
  void clipboardWrite(code);
  showToast('Code copied ✓', 'ok', 1500);
}

/**
 * The pool card's Copy button — advances the pool cursor and copies whatever
 * it landed on, exactly `envv pool next`. Members are read from the **live**
 * vault via `poolsOf`, not a snapshot the card was built with, so a member
 * deleted between render and click cannot be copied.
 */
async function copyPoolNext(poolName: string): Promise<void> {
  if (!poolName) return;
  const members = poolsOf(st.vault).get(poolName) ?? [];
  if (!members.length) return;
  const chosen = await poolNext(poolName, members);
  if (!chosen) {
    showToast(
      inTauri
        ? `Every key in "${poolName}" is rate limited`
        : 'Pool cursors are read by the desktop app',
      'err',
      2500,
    );
    return;
  }
  const realIdx = st.vault.api_keys.indexOf(chosen);
  if (realIdx < 0) return;
  doCopyEnv({ stopPropagation() {} } as Event, realIdx);
  // The badge's ready/cooling split just changed; the copied member's card
  // (if the pool is expanded) may need its own use-count refreshed too.
  triggerRender();
}

let searchDebounceTimer: ReturnType<typeof setTimeout>;

function debouncedSearch() {
  clearTimeout(searchDebounceTimer);
  searchDebounceTimer = setTimeout(() => {
    renderGrid();
    updateCopyAllBtn();
  }, 150);
}

/**
 * The dynamic file picker, hoisted so `finishInit` can hand it to the onboarding
 * wizard. It is created inside `init()` because it closes over nothing else —
 * see the WebKitGTK ghost-widget note there.
 */
let _openFilePicker: ((accept: string) => void) | null = null;

async function finishInit() {
  // See `html.booting` in base.css: the shell paints only once boot knows
  // whether a lock screen is going up in front of it.
  document.documentElement.classList.remove('booting');
  try {
    const r = await fetch('./schema.json');
    if (r.ok) st.schema = (await r.json()) as typeof st.schema;
  } catch {}

  try {
    const data = await st.store.load();
    if (data) {
      const remoteEmpty = !data.api_keys?.length;
      const localHasData = st.vault.api_keys.length > 0;

      // Remote vault empty but in-memory vault has data: offer to push before overwriting.
      if (remoteEmpty && localHasData && st.store.isRemote) {
        const push = await showConfirm(
          `Remote vault is empty — push your ${st.vault.api_keys.length} local entries to it?`,
        );
        if (push) {
          await persist();
          showToast(`Pushed ${st.vault.api_keys.length} entries to remote ✓`, 'ok', 2500);
          // Keep existing st.vault — do not overwrite with empty remote data.
        } else {
          st.vault.api_keys = [];
          st.vault.user_categories = [];
          st.vault.projects = [{ id: 'Universal', name: 'Universal', description: '' }];
        }
      } else {
        // `|| []` on all three: a vault blob written by an older build (or an
        // edited backup) can be missing a key entirely, and an undefined
        // api_keys threw on the very next line that iterates it.
        st.vault.api_keys = data.api_keys || [];
        st.vault.user_categories = data.user_categories || [];
        st.vault.projects = data.projects || [
          { id: 'Universal', name: 'Universal', description: '' },
        ];
      }

      if (!st.vault.projects.find((p) => p.id === 'Universal')) {
        st.vault.projects.unshift({ id: 'Universal', name: 'Universal', description: '' });
      }

      let needsSave = false;
      for (const key of st.vault.api_keys) {
        if (!key.projectIds) {
          key.projectIds = ['Universal'];
          needsSave = true;
        } else if (!key.projectIds.includes('Universal')) {
          key.projectIds.push('Universal');
          needsSave = true;
        }
        if (!key.secretType) {
          key.secretType = 'api_key';
          needsSave = true;
        }
        // The 'chunk' secret type has been removed — it could never be saved
        // through the UI anyway (its key field was hidden but still required).
        // Its content lived in extra_vars, which the normal card renders too, so
        // relabelling loses nothing.
        if ((key.secretType as string) === 'chunk') {
          key.secretType = 'env_var';
          needsSave = true;
        }
      }
      // Backfill stable ids for vaults written before the field existed, and
      // repair any duplicates. Runs once; afterwards every entry carries an id.
      if (ensureEntryIds(st.vault.api_keys)) needsSave = true;

      // Creation dates, from the audit log's `add` rows. Wrapped because the
      // audit read can fail in ways that must not stop a vault opening: a
      // scoped sub-user gets 403 from `/api/audit`, and a vault restored
      // without its audit table has no rows at all. Either way the entries
      // simply stay undated.
      if (st.vault.api_keys.some((e) => !e.created_at)) {
        try {
          const { loadAuditRows } = await import('./audit');
          const rows = await loadAuditRows();
          if (backfillCreatedAt(st.vault.api_keys, rows)) needsSave = true;
        } catch {}
      }

      if (needsSave) await persist();

      document.getElementById('load-banner')!.style.display = 'none';
      st.vaultOpen = true;
      // From here the vault can also be written from outside this window — a
      // terminal running `envv`, or a LAN peer. Idempotent by assignment, so
      // re-unlocking leaves one timer.
      startVaultWatch();
      showToast(`Loaded ${st.vault.api_keys.length} keys`, 'ok', 1800);
    } else {
      document.getElementById('load-banner')!.style.display = 'flex';
    }
  } catch {
    document.getElementById('load-banner')!.style.display = 'flex';
  }

  // Restore the last grid view *before* the first render, so the app paints once
  // in its final state instead of flashing the unfiltered grid. restoreViewState
  // drops any id the loaded vault does not have — see its doc comment.
  restoreViewState();

  render();
  resetLock();
  initTools();
  initUsersPanel();
  initAuthPanel();
  applyUsersPanelVisibility();
  initRemotePanel();
  initLanPanel();
  setRemoteFinishInitFn(finishInit);

  // First-run wizard, last so it opens over a fully painted app rather than a
  // half-built one. Local vaults only: connecting to a remote is not a first
  // run, and the wizard writes local display settings that have nothing to do
  // with the server you just reached.
  if (!st.store.isRemote && st.vaultOpen && shouldShowOnboarding()) {
    showOnboarding({
      onAdd: () => openAdd(),
      onImport: () => _openFilePicker?.('.json,.env,text/plain'),
    });
  }
}

async function init() {
  // Must run before anything queries the tools DOM: the tool panes live in
  // tools-markup.ts and are injected here, not present in index.html.
  mountToolsPanes();

  await Settings.init();
  applySidebarLayout();
  restoreSort();
  initIconPicker();
  wireSearchHistory((q) => {
    // Store the query exactly as typed — parseSearch() lowercases what it needs
    // to, and pre-lowercasing here would both diverge from the input handler and
    // display a mangled query in the active-filter tooltip.
    const el = document.getElementById('search') as HTMLInputElement;
    el.value = q;
    st.searchQ = q;
    document.getElementById('search-clear')?.classList.add('visible');
    renderGrid();
    updateCopyAllBtn();
  });
  wireCloseGuard();
  // Focus trapping and restoration for every overlay. See its doc comment for
  // why it observes classes instead of hooking each open/close site.
  wireModalFocus();

  // Wrap form selects as custom dropdowns (WebKitGTK compositing workaround)
  ['f-secret-type', 'f-price', 'f-env'].forEach((id) => {
    const el = document.getElementById(id) as HTMLSelectElement | null;
    if (el) st.formCustomSelects.set(id, new CustomSelect(el));
  });

  st.store = inTauri ? new TauriVaultStore() : new LocalVaultStore();

  // File picker (dynamic input — WebKitGTK ghost widget workaround)
  /**
   * @param onText when given, receives the file's text instead of
   *        `handleFileSelect` deciding what the file is. The authenticator
   *        import needs it: an Aegis vault and a full EnvVault export are both
   *        `.json`, and letting the sniffer guess between them is how a 2FAS
   *        backup ends up interpreted as a vault replacement.
   */
  const openFilePicker = (accept: string, onText?: (text: string) => void) => {
    const inp = document.createElement('input');
    inp.type = 'file';
    inp.accept = accept;
    document.body.appendChild(inp);
    let done = false;
    const cleanup = () => {
      if (done) return;
      done = true;
      if (document.body.contains(inp)) document.body.removeChild(inp);
    };
    inp.addEventListener(
      'change',
      function () {
        if (onText) {
          const file = this.files?.[0];
          if (file) {
            const reader = new FileReader();
            // `readAsText` always yields a string, but `result` is typed as
            // `string | ArrayBuffer | null` — and `String()` on an ArrayBuffer
            // silently produces "[object ArrayBuffer]", which would reach the
            // parser as a file whose every line is unreadable.
            reader.onload = (ev) =>
              onText(typeof ev.target?.result === 'string' ? ev.target.result : '');
            reader.readAsText(file);
          }
        } else {
          handleFileSelect(this);
        }
        this.value = '';
        cleanup();
      },
      { once: true },
    );
    inp.addEventListener('cancel', cleanup, { once: true });
    inp.click();
    setTimeout(() => window.addEventListener('focus', cleanup, { once: true }), 300);
  };
  _openFilePicker = openFilePicker;

  document
    .getElementById('load-banner-browse-btn')
    ?.addEventListener('click', () => openFilePicker('.json,.env,text/plain'));

  // Authenticator import / export.
  //
  // Assigned, not added (invariant 9): `init()` runs once today, but every other
  // wire-up in this file that was written as `addEventListener` has eventually
  // been called twice by something.
  //
  // A2 (2026-09-14) removed the sidebar section's pair (`#totp-*`); the
  // Authenticator panel's (`#auth-*`) is the only surface left.
  for (const id of ['auth-import-btn']) {
    const btn = document.getElementById(id);
    if (!btn) continue;
    btn.onclick = () => {
      // Built and removed per use: WebKitGTK renders a native widget for any
      // `<input type="file">` in the DOM regardless of CSS (the Phase 3 ghost).
      openFilePicker(
        '.txt,.json,.2fas,text/plain,application/json',
        (text) => void runTotpImport(text),
      );
    };
  }
  for (const id of ['auth-export-btn']) {
    const btn = document.getElementById(id);
    if (!btn) continue;
    btn.onclick = () => {
      showDropdown(
        btn,
        EXPORT_FORMATS.map((f) => ({ label: f.label, fn: () => void runTotpExport(f.value) })),
      );
    };
  }

  // Sidebar — filter buttons
  document.getElementById('sidebar')!.addEventListener('click', (e) => {
    const btn = (e.target as HTMLElement).closest<HTMLButtonElement>('.sidebar-item');
    if (!btn) return;
    // Tag filter button
    if (btn.classList.contains('tag-filter-btn')) {
      const tag = btn.dataset.tag ?? '';
      st.activeTagFilter = st.activeTagFilter === tag ? null : tag;
      triggerRender();
      return;
    }
    // Env-prefix filter button
    if (btn.classList.contains('prefix-filter-btn')) {
      const pfx = btn.dataset.prefix ?? '';
      st.activePrefixFilter = st.activePrefixFilter === pfx ? null : pfx;
      triggerRender();
      return;
    }
    // Key-pool filter button
    if (btn.classList.contains('pool-filter-btn')) {
      const pool = btn.dataset.pool ?? '';
      st.activePoolFilter = st.activePoolFilter === pool ? null : pool;
      triggerRender();
      return;
    }
    const filterType = btn.dataset.filterType;
    const filterValue = btn.dataset.filterValue;
    if (filterType && filterValue !== undefined) {
      if (filterType === 'env') {
        st.currentEnvFilter = st.currentEnvFilter === filterValue ? '' : filterValue;
        triggerRender();
      } else {
        if (filterType === 'all') {
          st.currentSelectedProjectIds = ['Universal'];
          st.currentEnvFilter = '';
          st.activeTagFilter = null;
          // The prefix filter was added after this reset was written and never
          // added to it, so "All" left the grid narrowed with nothing in the
          // sidebar looking active to explain why.
          st.activePrefixFilter = null;
          st.activePoolFilter = null;
        }
        doSetFilter(filterType, filterValue);
      }
    }
  });

  // Type chip bar (Phase 24.2) — multi-toggle, so a click adds or removes one
  // chip from the Set rather than replacing it, unlike every sidebar filter
  // above which is single-select.
  document.getElementById('type-chip-bar')?.addEventListener('click', (e) => {
    const btn = (e.target as HTMLElement).closest<HTMLButtonElement>('.type-chip');
    const chip = btn?.dataset.chip;
    if (!chip) return;
    if (st.activeTypeChips.has(chip)) st.activeTypeChips.delete(chip);
    else st.activeTypeChips.add(chip);
    triggerRender();
  });

  // Categories section: rename/delete tags
  document.getElementById('category-tree')!.addEventListener('click', (e) => {
    const target = e.target as HTMLElement;
    const renameBtn = target.closest<HTMLElement>('.rename-cat');
    if (renameBtn?.dataset.category) {
      void renameCategory(renameBtn.dataset.category);
      return;
    }
    const deleteBtn = target.closest<HTMLElement>('.delete-cat');
    if (deleteBtn?.dataset.category) {
      void deleteCategory(deleteBtn.dataset.category);
      return;
    }
  });

  // Projects section: selection, rename, delete
  document.getElementById('project-list')!.addEventListener('click', (e) => {
    const target = e.target as HTMLElement;
    const projBtn = target.closest<HTMLButtonElement>('[data-project-id]');
    if (projBtn?.dataset.projectId) {
      const id = projBtn.dataset.projectId!;
      st.currentSelectedProjectIds = st.currentSelectedProjectIds[0] === id ? ['Universal'] : [id];
      render();
      return;
    }
    const renameBtn = target.closest<HTMLElement>('.rename-proj');
    if (renameBtn?.dataset.project) {
      void renameProject(renameBtn.dataset.project);
      return;
    }
    const deleteBtn = target.closest<HTMLElement>('.delete-proj');
    if (deleteBtn?.dataset.project) {
      void deleteProject(deleteBtn.dataset.project);
      return;
    }
  });

  // Search
  const searchEl = document.getElementById('search') as HTMLInputElement;
  const searchClearBtn = document.getElementById('search-clear')!;
  searchEl.addEventListener('input', (e) => {
    st.searchQ = (e.target as HTMLInputElement).value;
    if (st.searchQ) searchClearBtn.classList.add('visible');
    else searchClearBtn.classList.remove('visible');
    debouncedSearch();
  });
  searchClearBtn.addEventListener('click', () => {
    st.searchQ = '';
    searchEl.value = '';
    searchClearBtn.classList.remove('visible');
    renderGrid();
    updateCopyAllBtn();
  });

  // Sort dropdown
  document.getElementById('sort-btn')?.addEventListener('click', (e) => {
    const opts = SORT_OPTIONS;
    showDropdown(
      e.currentTarget as HTMLElement,
      opts.map((opt) => ({
        label: (opt.value === st.currentSortBy ? '✓ ' : '    ') + opt.label,
        active: opt.value === st.currentSortBy,
        fn: () => {
          st.currentSortBy = opt.value;
          Settings.set('lastSortBy', opt.value);
          const labelEl = document.getElementById('sort-label-text');
          if (labelEl) labelEl.textContent = opt.label;
          renderGrid();
        },
      })),
    );
  });

  // Expand all
  document.getElementById('expand-all-btn')!.addEventListener('click', () => {
    st.allExpanded = !st.allExpanded;
    if (st.allExpanded) st.vault.api_keys.forEach((k) => st.expanded.add(entryId(k)));
    else st.expanded.clear();
    renderGrid(); // renderGrid syncs the button label from st.allExpanded
  });

  // Sidebar toggle + add button. The collapsed state is persisted: it is a
  // layout preference, and resetting it on every launch made Ctrl-B feel like
  // it had not been remembered.
  document.getElementById('sidebar-toggle')!.addEventListener('click', () => {
    const sb = document.getElementById('sidebar');
    if (!sb) return;
    sb.classList.toggle('collapsed');
    const collapsed = sb.classList.contains('collapsed');
    Settings.set('sidebarCollapsed', collapsed);
    document.getElementById('sidebar-toggle')!.setAttribute('aria-expanded', String(!collapsed));
  });
  document.getElementById('add-btn')!.addEventListener('click', openAdd);

  // Sidebar resize handle
  {
    const resizer = document.getElementById('sidebar-resizer');
    const sidebar = document.getElementById('sidebar');
    if (resizer && sidebar) {
      let _startX = 0,
        _startW = 0;
      resizer.addEventListener('mousedown', (e) => {
        _startX = e.clientX;
        _startW = sidebar.getBoundingClientRect().width;
        resizer.classList.add('dragging');
        let _w = _startW;
        const onMove = (ev: MouseEvent) => {
          _w = Math.max(SIDEBAR_MIN_W, Math.min(SIDEBAR_MAX_W, _startW + ev.clientX - _startX));
          sidebar.style.width = _w + 'px';
          resizer.setAttribute('aria-valuenow', String(Math.round(_w)));
        };
        const onUp = () => {
          resizer.classList.remove('dragging');
          document.removeEventListener('mousemove', onMove);
          document.removeEventListener('mouseup', onUp);
          // Persist on mouseup, not on every mousemove: writing localStorage on
          // each pixel of the drag serialises the whole settings blob ~60×/sec.
          Settings.set('sidebarWidth', Math.round(_w));
        };
        document.addEventListener('mousemove', onMove);
        document.addEventListener('mouseup', onUp);
        e.preventDefault();
      });

      // Double-click the handle to go back to the stylesheet default — the only
      // way out once a persisted width has been dragged to an awkward size.
      resizer.addEventListener('dblclick', () => {
        Settings.set('sidebarWidth', 0);
        sidebar.style.width = '';
        resizer.setAttribute('aria-valuenow', String(SIDEBAR_MIN_W));
        showToast('Sidebar width reset', 'ok', 1500);
      });

      // Keyboard resizing. Without it the sidebar width is a mouse-only setting
      // that persists across restarts — so a keyboard user who inherits a
      // 150px sidebar has no way to widen it. Home/End jump to the bounds and
      // Enter restores the default, matching the double-click.
      resizer.addEventListener('keydown', (e) => {
        const cur = Math.round(sidebar.getBoundingClientRect().width);
        const step = e.shiftKey ? 40 : 10;
        let next: number | null = null;
        if (e.key === 'ArrowLeft') next = cur - step;
        else if (e.key === 'ArrowRight') next = cur + step;
        else if (e.key === 'Home') next = SIDEBAR_MIN_W;
        else if (e.key === 'End') next = SIDEBAR_MAX_W;
        else if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          Settings.set('sidebarWidth', 0);
          sidebar.style.width = '';
          resizer.setAttribute('aria-valuenow', String(SIDEBAR_MIN_W));
          showToast('Sidebar width reset', 'ok', 1500);
          return;
        }
        if (next === null) return;
        e.preventDefault();
        const w = Math.max(SIDEBAR_MIN_W, Math.min(SIDEBAR_MAX_W, next));
        sidebar.style.width = w + 'px';
        resizer.setAttribute('aria-valuenow', String(w));
        Settings.set('sidebarWidth', w);
      });
    }
  }

  // Entry modal buttons
  document.getElementById('modal-close')!.addEventListener('click', closeModal);
  document.getElementById('modal-cancel')!.addEventListener('click', closeModal);
  document.getElementById('modal-save')!.addEventListener('click', () => void saveModal());
  document.getElementById('modal-duplicate')!.addEventListener('click', () => {
    const idx = parseInt((document.getElementById('edit-index') as HTMLInputElement).value);
    if (idx >= 0) duplicateKey(new Event('click'), idx);
    closeModal();
  });

  // Icon picker (inside entry modal)
  document
    .getElementById('f-icon-pick')!
    .addEventListener('click', () =>
      openIconPicker(
        document.getElementById('f-icon') as HTMLInputElement,
        document.getElementById('f-icon-preview') as HTMLElement,
      ),
    );
  document.getElementById('f-icon')!.addEventListener('input', (e) => {
    const prev = document.getElementById('f-icon-preview')!;
    setHtml(
      prev,
      (e.target as HTMLInputElement).value
        ? iconHTML('', (e.target as HTMLInputElement).value)
        : '',
    );
  });

  // Settings panel
  document.getElementById('settings-btn')!.addEventListener('click', openSettings);
  document.getElementById('settings-close')!.addEventListener('click', () => {
    saveSettings();
    closeSettings();
  });
  document.getElementById('settings-overlay')!.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) {
      saveSettings();
      closeSettings();
    }
  });
  document.getElementById('settings-export-btn')!.addEventListener('click', () => {
    // A3: same fix as every other export — a blob-anchor click wrote nothing
    // in Tauri's webview and nothing said so.
    void saveFile(JSON.stringify(Settings.getAll(), null, 2), 'settings.json').then((res) =>
      showToast(
        res.ok
          ? res.path
            ? `Exported to ${res.path}`
            : 'Exported'
          : `Export failed: ${res.error}`,
        res.ok ? 'ok' : 'error',
      ),
    );
  });

  // Segmented controls (card size, grid columns, activity bar)
  document.querySelectorAll('.seg-control').forEach((ctrl) =>
    ctrl.addEventListener('click', (e) => {
      const btn = (e.target as HTMLElement).closest('button[data-val]') as HTMLButtonElement | null;
      if (!btn) return;
      ctrl.querySelectorAll('button').forEach((b) => b.classList.remove('active'));
      btn.classList.add('active');
      const key =
        ctrl.id === 's-card-size'
          ? 'cardSize'
          : ctrl.id === 's-grid-cols'
            ? 'gridColumns'
            : ctrl.id === 's-activity-bar-position'
              ? 'activityBarPosition'
              : 'activityBarStyle';
      Settings.set(key, btn.dataset.val as AppSettings[typeof key]);
      Settings._apply();
      render();
    }),
  );

  // Accent color
  document.getElementById('s-accent')!.addEventListener('input', (e) => {
    const v = (e.target as HTMLInputElement).value;
    document.getElementById('s-accent-val')!.textContent = v;
    Settings.set('accentColor', v);
    Settings._apply();
  });
  document.getElementById('s-accent-reset')!.addEventListener('click', () => {
    const def = '#7364c9';
    (document.getElementById('s-accent') as HTMLInputElement).value = def;
    document.getElementById('s-accent-val')!.textContent = def;
    Settings.set('accentColor', def);
    Settings._apply();
  });

  // Copy-All
  document.getElementById('copy-all-arrow')!.addEventListener('click', (e) =>
    showDropdown(e.currentTarget as HTMLElement, [
      { label: 'Copy .env', fn: () => copyAll('dotenv') },
      { label: 'Copy YAML', fn: () => copyAll('yaml') },
      { label: 'Copy JSON', fn: () => copyAll('json') },
    ]),
  );
  document
    .getElementById('copy-all-btn')!
    .addEventListener('click', () => copyAll(Settings.get('defaultExportFormat')));

  // Env import modal
  document.getElementById('env-import-close')?.addEventListener('click', closeEnvImportModal);
  document.getElementById('env-import-cancel')?.addEventListener('click', closeEnvImportModal);
  document.getElementById('env-import-confirm')?.addEventListener('click', confirmEnvImport);
  document
    .getElementById('env-import-select-all')
    ?.addEventListener('click', () =>
      document
        .querySelectorAll<HTMLInputElement>('.env-import-check')
        .forEach((cb) => (cb.checked = true)),
    );
  document
    .getElementById('env-import-select-none')
    ?.addEventListener('click', () =>
      document
        .querySelectorAll<HTMLInputElement>('.env-import-check')
        .forEach((cb) => (cb.checked = false)),
    );
  document.getElementById('env-import-overlay')?.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) closeEnvImportModal();
  });

  // ENV link modal
  document.getElementById('env-link-close')?.addEventListener('click', closeEnvLinkModal);
  document.getElementById('env-link-cancel')?.addEventListener('click', closeEnvLinkModal);
  document.getElementById('env-link-apply')?.addEventListener('click', applyEnvLink);
  document.getElementById('env-link-overlay')?.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) closeEnvLinkModal();
  });

  // Data import/export
  document
    .getElementById('settings-import-btn')
    ?.addEventListener('click', () => openFilePicker('.json,.env,.yaml,.yml,text/plain'));
  document
    .getElementById('settings-export-dotenv')
    ?.addEventListener('click', () => void exportAs('dotenv'));
  document
    .getElementById('settings-export-yaml')
    ?.addEventListener('click', () => void exportAs('yaml'));
  document
    .getElementById('settings-export-json')
    ?.addEventListener('click', () => void exportAs('json'));
  document
    .getElementById('settings-export-k8s')
    ?.addEventListener('click', () => exportK8sSecret());
  document
    .getElementById('settings-export-tfvars')
    ?.addEventListener('click', () => exportTfvars());
  document.getElementById('settings-cxf-import-btn')?.addEventListener('click', () => {
    openFilePicker('.json,.cxf,text/plain,application/json', (text) => void runCxfImport(text));
  });
  document
    .getElementById('settings-cxf-export-btn')
    ?.addEventListener('click', () => void runCxfExport());
  document.getElementById('settings-export-encrypted')?.addEventListener('click', () => {
    const pw = (document.getElementById('settings-backup-pw') as HTMLInputElement).value;
    void exportEncryptedBackup(pw);
  });
  document.getElementById('settings-import-encrypted')?.addEventListener('click', () => {
    const pw = (document.getElementById('settings-backup-pw') as HTMLInputElement).value;
    if (!pw) {
      showToast('Enter the backup password first', 'err');
      return;
    }
    const inp = document.createElement('input');
    inp.type = 'file';
    inp.accept = '.vaultbak,.json,text/plain';
    inp.onchange = () => {
      const f = inp.files?.[0];
      if (!f) {
        inp.remove();
        return;
      }
      const reader = new FileReader();
      reader.onload = (e) => {
        const data = e.target?.result;
        if (typeof data === 'string') void importEncryptedBackup(data, pw);
        inp.remove();
      };
      reader.readAsText(f);
    };
    document.body.appendChild(inp);
    inp.click();
  });

  // Category create modal
  document
    .getElementById('new-category-root-btn')
    ?.addEventListener('click', openCategoryCreateModal);
  document
    .getElementById('category-create-close')
    ?.addEventListener('click', closeCategoryCreateModal);
  document
    .getElementById('category-create-cancel')
    ?.addEventListener('click', closeCategoryCreateModal);
  document.getElementById('category-create-save')?.addEventListener('click', saveCategoryCreate);
  document.getElementById('category-create-overlay')?.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) closeCategoryCreateModal();
  });
  document.getElementById('category-create-name')?.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') saveCategoryCreate();
    if (e.key === 'Escape') closeCategoryCreateModal();
  });

  // Project create modal
  document.getElementById('new-project-btn')!.addEventListener('click', openProjectCreateModal);
  document
    .getElementById('project-create-close')
    ?.addEventListener('click', closeProjectCreateModal);
  document
    .getElementById('project-create-cancel')
    ?.addEventListener('click', closeProjectCreateModal);
  document.getElementById('project-create-save')?.addEventListener('click', saveProjectCreate);
  document.getElementById('project-create-overlay')?.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) closeProjectCreateModal();
  });
  document.getElementById('project-create-name')?.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') saveProjectCreate();
    if (e.key === 'Escape') closeProjectCreateModal();
  });
  document.querySelectorAll<HTMLButtonElement>('.project-type-btn').forEach((btn) => {
    btn.addEventListener('click', () => {
      document.querySelectorAll<HTMLButtonElement>('.project-type-btn').forEach((b) => {
        b.classList.remove('active');
        b.setAttribute('aria-checked', 'false');
      });
      btn.classList.add('active');
      btn.setAttribute('aria-checked', 'true');
      setProjectCreateType((btn.dataset.ptype || 'generic') as ProjectType);
    });
  });

  // Chunk edit modal
  document.getElementById('chunk-edit-close')?.addEventListener('click', closeChunkEditModal);
  document.getElementById('chunk-edit-cancel')?.addEventListener('click', closeChunkEditModal);
  document.getElementById('chunk-edit-save')?.addEventListener('click', saveChunkEdit);
  document.getElementById('chunk-edit-overlay')?.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) closeChunkEditModal();
  });
  document.getElementById('chunk-edit-add-field')?.addEventListener('click', () => {
    const current = readChunkEditFields();
    current.push({ key: '', value: '', field_type: 'var' });
    renderChunkEditFields(current);
  });

  // Clear every active filter
  document.getElementById('clear-filters-btn')?.addEventListener('click', () => {
    clearAllFilters();
    closeSearchHistory();
    triggerRender();
  });

  // Lock
  document.getElementById('lock-btn')!.addEventListener('click', () => {
    void (async () => {
      if (await showConfirm('Lock vault?')) void lockVault();
    })();
  });

  // Undo bar
  document.getElementById('undo-btn')!.addEventListener('click', () => {
    const last = st.undoStack.pop();
    if (last) {
      clearTimeout(last.t);
      void last.fn();
      if (!st.undoStack.length) document.getElementById('undo-bar')!.classList.remove('visible');
    }
  });

  // Keyboard shortcuts overlay
  const shortcutsEl = document.getElementById('shortcuts-overlay')!;
  document
    .getElementById('shortcuts-btn')!
    .addEventListener('click', () => shortcutsEl.classList.add('open'));
  document
    .getElementById('shortcuts-close')!
    .addEventListener('click', () => shortcutsEl.classList.remove('open'));
  shortcutsEl.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) shortcutsEl.classList.remove('open');
  });

  // Wi-Fi QR overlay: emptied on every close path.
  const wifiQrEl = document.getElementById('wifi-qr-overlay')!;
  document.getElementById('wifi-qr-close')!.addEventListener('click', hideWifiQr);
  wifiQrEl.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) hideWifiQr();
  });

  // Global keyboard shortcuts
  document.addEventListener('keydown', (e) => {
    // A non-<button> given role="button" (the card's icon) must answer Enter and
    // Space like one; a role without the keys is a control a keyboard can reach
    // and cannot use.
    const t = e.target as HTMLElement | null;
    if ((e.key === 'Enter' || e.key === ' ') && t?.matches('[role="button"][data-action]')) {
      e.preventDefault();
      t.click();
      return;
    }
    const inInput = ['INPUT', 'SELECT', 'TEXTAREA'].includes(
      (document.activeElement as HTMLElement)?.tagName,
    );
    if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
      e.preventDefault();
      (document.getElementById('search') as HTMLInputElement).focus();
      (document.getElementById('search') as HTMLInputElement).select();
      return;
    }
    if ((e.ctrlKey || e.metaKey) && e.key === 'n') {
      e.preventDefault();
      openAdd();
      return;
    }
    if (!inInput && e.key === 's') openSettings();
    if (!inInput && e.key === 'b') document.getElementById('sidebar-toggle')!.click();
    if (!inInput && e.key === '?') shortcutsEl.classList.add('open');
    // Shift+Esc: drop every filter at once. Plain Escape only clears the search
    // box, which is not enough now that a category/project/tag selection can be
    // restored from a previous session.
    if (e.key === 'Escape' && e.shiftKey) {
      e.preventDefault();
      clearAllFilters();
      triggerRender();
      showToast('Filters cleared', 'ok', 1500);
      return;
    }
    if (e.key === 'Escape') {
      shortcutsEl.classList.remove('open');
      // Escape used to just hide the panel: theme and accent apply live, so the
      // preview stayed on screen while never being committed — neither saved
      // nor reverted. Escape is a cancel, same as the Cancel button.
      if (document.getElementById('settings-overlay')?.classList.contains('open')) cancelSettings();
      // Only close the entry modal if it is actually open: closeModal() also
      // discards the saved form draft, so a stray Escape used to throw away a
      // draft left by a previous session before it could be restored.
      if (document.getElementById('modal-overlay')?.classList.contains('open')) closeModal();
      if (st.searchQ) {
        st.searchQ = '';
        (document.getElementById('search') as HTMLInputElement).value = '';
        renderGrid();
      }
    }
  });

  // Card grid — delegated click
  const onGridClick = (e: MouseEvent) => {
    const el = (e.target as HTMLElement).closest('[data-action]') as HTMLElement | null;
    if (!el) return;
    const action = el.dataset.action!;
    const idx = el.dataset.idx !== undefined ? parseInt(el.dataset.idx!) : -1;
    const value = el.dataset.value ?? '';
    const field = el.dataset.field ?? '';
    if (
      action === 'copy-env' &&
      el.classList.contains('card-head') &&
      (e.target as HTMLElement).closest('[data-action]') !== el
    )
      return;
    if (window.__envvIsBulkMode?.() && action !== 'bulk-toggle') {
      const card = el.closest<HTMLElement>('[data-idx]');
      if (card) {
        window.__envvBulkToggle?.(parseInt(card.dataset.idx!));
        return;
      }
    }
    e.stopPropagation();
    switch (action) {
      case 'toggle':
        toggleCard(e, idx);
        break;
      case 'reveal':
        toggleReveal(e, field, idx, value);
        break;
      case 'copy-field':
        copyField(e, value, el);
        break;
      case 'copy-env':
        doCopyEnv(e, idx);
        break;
      case 'copy-env-menu':
        openCopyEnvMenu(e, idx);
        break;
      case 'rotate':
        markAsRotated(idx);
        break;
      // The session equivalent (E13). Rotating a cookie means logging in again
      // in a browser, which nothing here can do, so "never rotated" was a
      // finding with no available fix; "never verified" has one.
      case 'verify': {
        const entry = st.vault.api_keys[idx];
        if (entry) {
          entry.last_verified_at = new Date().toISOString();
          void persist();
          triggerRender();
          showToast('Session verified ✓', 'ok', 1800);
        }
        break;
      }
      case 'pin': {
        const entry = st.vault.api_keys[idx];
        if (entry) {
          entry.pinned = entry.pinned ? undefined : true;
          void persist();
          triggerRender();
          showToast(entry.pinned ? 'Pinned ✓' : 'Unpinned', 'ok', 1500);
        }
        break;
      }
      case 'bulk-toggle':
        window.__envvBulkToggle?.(idx);
        break;
      case 'bundle-bulk-toggle': {
        if (!window.__envvIsBulkMode?.()) {
          showToast('Choose Select first to bulk-select bundle members', 'info');
          break;
        }
        const bundle = el.closest<HTMLElement>('.bundle-card-wrap');
        const indices = new Set(
          [...(bundle?.querySelectorAll<HTMLElement>('.card[data-idx]') ?? [])]
            .map((card) => Number(card.dataset.idx))
            .filter(Number.isInteger),
        );
        indices.forEach((memberIdx) => window.__envvBulkToggle?.(memberIdx));
        break;
      }
      case 'duplicate':
        duplicateKey(e, idx);
        break;
      case 'edit':
        openEdit(e, idx);
        break;
      case 'delete':
        deleteKey(e, idx);
        break;
      case 'icon':
        onIconWrapClick(e, idx);
        break;
      case 'copy-totp':
        copyTotpFrom(el);
        break;
      case 'toggle-desc':
        el.classList.toggle('open');
        (el.nextElementSibling as HTMLElement)?.classList.toggle('open');
        // A disclosure button that never updates aria-expanded reads as
        // permanently collapsed, whatever is on screen.
        el.setAttribute('aria-expanded', String(el.classList.contains('open')));
        break;
      case 'pool-card-toggle': {
        const pool = el.dataset.pool ?? '';
        // In bulk mode the card has no per-pool checkbox of its own; the
        // summary bar stands in for one, ticking every member it covers.
        if (window.__envvIsBulkMode?.()) {
          const members = poolsOf(st.vault).get(pool) ?? [];
          members.forEach((m) => {
            const i = st.vault.api_keys.indexOf(m);
            if (i >= 0) window.__envvBulkToggle?.(i);
          });
          break;
        }
        if (st.expandedPools.has(pool)) st.expandedPools.delete(pool);
        else st.expandedPools.add(pool);
        renderGrid();
        break;
      }
      case 'pool-card-copy':
        void copyPoolNext(el.dataset.pool ?? '');
        break;
      case 'bundle-toggle': {
        const bundleId = el.dataset.bundle ?? '';
        if (st.expandedBundles.has(bundleId)) st.expandedBundles.delete(bundleId);
        else st.expandedBundles.add(bundleId);
        saveViewState();
        render();
        break;
      }
      case 'bundle-primary': {
        const bundle = st.vault.api_keys.find(
          (entry) => entry.id === el.dataset.bundle && entry.secretType === 'bundle',
        );
        const member = st.vault.api_keys.find(
          (entry) => entry.id === el.dataset.member && entry.bundle_id === bundle?.id,
        );
        if (!bundle || !member) break;
        bundle.bundle_primary = member.id;
        void persist().then(() => render());
        break;
      }
      case 'bundle-slot-tab': {
        const bundleId = el.dataset.bundle ?? '';
        const member = st.vault.api_keys.find(
          (entry) => entry.id === el.dataset.member && entry.bundle_id === bundleId,
        );
        if (!member) break;
        st.bundleSlotTabs[bundleId] = member.id!;
        saveViewState();
        render();
        break;
      }
      case 'bundle-rename-slot': {
        const bundleId = el.dataset.bundle ?? '';
        const memberId = el.dataset.member ?? '';
        void (async () => {
          const bundle = st.vault.api_keys.find(
            (entry) => entry.id === bundleId && entry.secretType === 'bundle',
          );
          const member = st.vault.api_keys.find(
            (entry) => entry.id === memberId && entry.bundle_id === bundleId,
          );
          if (!bundle || !member) return;
          const next = (
            await showPrompt(`New slot name for ${member.bundle_slot || member.provider}`)
          )?.trim();
          if (!next || next === member.bundle_slot) return;
          if (!/^[A-Za-z0-9][A-Za-z0-9_-]{0,23}$/.test(next)) {
            showToast(
              'Slot names must start with a letter or digit and use only letters, digits, _ or - (max 24)',
              'err',
            );
            return;
          }
          if (
            st.vault.api_keys.some(
              (entry) =>
                entry.bundle_id === bundleId && entry.id !== memberId && entry.bundle_slot === next,
            ) ||
            bundle.extra_vars?.some((variable) => variable.key === next)
          ) {
            showToast('That slot name is already used in this bundle', 'err');
            return;
          }
          const previous = member.bundle_slot || member.provider;
          const refs = renameBundleSlotRefs(
            st.vault.api_keys,
            st.vault.projects,
            bundle,
            previous,
            next,
          );
          member.bundle_slot = next;
          await persist();
          render();
          if (refs)
            showToast(`Updated ${refs} bundle reference${refs === 1 ? '' : 's'}`, 'ok', 2500);
        })();
        break;
      }
      case 'bundle-remove-member': {
        const bundleId = el.dataset.bundle;
        const memberId = el.dataset.member;
        const bundle = st.vault.api_keys.find(
          (entry) => entry.id === bundleId && entry.secretType === 'bundle',
        );
        const member = st.vault.api_keys.find(
          (entry) => entry.id === memberId && entry.bundle_id === bundle?.id,
        );
        if (!bundle || !member) break;
        void (async () => {
          if (!(await confirmBundleMemberReferenceBreakage(member))) return;
          const currentBundle = st.vault.api_keys.find(
            (entry) => entry.id === bundleId && entry.secretType === 'bundle',
          );
          const currentMember = st.vault.api_keys.find(
            (entry) => entry.id === memberId && entry.bundle_id === bundleId,
          );
          if (!currentBundle || !currentMember) return;
          delete currentMember.bundle_id;
          delete currentMember.bundle_slot;
          delete currentMember.bundle_order;
          if (currentBundle.bundle_primary === currentMember.id) {
            currentBundle.bundle_primary =
              st.vault.api_keys.find((entry) => entry.bundle_id === currentBundle.id)?.id ?? null;
          }
          await persist();
          render();
        })();
        break;
      }
      case 'bundle-add-member': {
        const bundleId = el.dataset.bundle ?? '';
        void (async () => {
          const candidate = await showPrompt('Name of an unbundled entry to add');
          const matches = st.vault.api_keys.filter(
            (entry) =>
              entry.secretType !== 'bundle' &&
              !entry.bundle_id &&
              (entry.provider === candidate?.trim() || entry.label === candidate?.trim()),
          );
          const bundle = st.vault.api_keys.find(
            (entry) => entry.id === bundleId && entry.secretType === 'bundle',
          );
          if (matches.length !== 1 || !bundle) {
            showToast(
              matches.length > 1
                ? 'That name is ambiguous; choose a unique label'
                : 'No matching unbundled entry',
              'err',
            );
            return;
          }
          const member = matches[0];
          if (!member) {
            showToast('No matching unbundled entry', 'err');
            return;
          }
          const poolName = typeof member.pool === 'string' ? member.pool.trim() : '';
          const pool = poolName
            ? st.vault.api_keys.filter((entry) => entry.pool?.trim() === poolName)
            : [member];
          if (pool.some((entry) => entry.bundle_id && entry.bundle_id !== bundleId)) {
            showToast('All entries in a key pool must belong to the same bundle', 'err');
            return;
          }
          const additions = pool.filter((entry) => !entry.bundle_id);
          if (
            additions.length > 1 &&
            !(await showConfirm(`Add all ${additions.length} entries in pool "${poolName}"?`))
          )
            return;
          let order = Math.max(
            0,
            ...st.vault.api_keys
              .filter((entry) => entry.bundle_id === bundleId)
              .map((entry) => entry.bundle_order ?? 0),
          );
          const used = new Set(
            st.vault.api_keys
              .filter((entry) => entry.bundle_id === bundleId)
              .map((entry) => entry.bundle_slot),
          );
          for (const addition of additions) {
            const base = (addition.label || addition.provider)
              .trim()
              .replace(/[^A-Za-z0-9_-]+/g, '_')
              .slice(0, 24);
            let slot = /^[A-Za-z0-9]/.test(base)
              ? base
              : `member_${st.vault.api_keys.filter((entry) => entry.bundle_id === bundleId).length + 1}`;
            for (let suffix = 2; used.has(slot); suffix++) {
              const tail = `_${suffix}`;
              slot = `${base.slice(0, 24 - tail.length)}${tail}`;
            }
            used.add(slot);
            addition.bundle_id = bundleId;
            addition.bundle_slot = slot;
            addition.bundle_order = order += 10;
            bundle.bundle_primary ??= addition.id;
          }
          await persist();
          render();
        })();
        break;
      }
      case 'bundle-add-var': {
        const bundle = st.vault.api_keys.find(
          (entry) => entry.id === el.dataset.bundle && entry.secretType === 'bundle',
        );
        if (!bundle) break;
        void (async () => {
          const key = (await showPrompt('Variable name'))?.trim();
          if (!key) return;
          if (bundle.extra_vars?.some((variable) => variable.key === key)) {
            showToast('That variable already exists', 'err');
            return;
          }
          const value = await showPasswordPrompt(`Secret value for ${key}`);
          if (value === null) return;
          bundle.extra_vars ??= [];
          // Until this form exposes an explicit visibility control, new locals
          // fail closed and are masked rather than accidentally shown in a card.
          bundle.extra_vars.push({ key, value, secret: true });
          await persist();
          render();
        })();
        break;
      }
      case 'bundle-var-remove': {
        const bundle = st.vault.api_keys.find(
          (entry) => entry.id === el.dataset.bundle && entry.secretType === 'bundle',
        );
        const key = el.dataset.key;
        if (!bundle || !key) break;
        void (async () => {
          if (!(await showConfirm(`Remove bundle variable "${key}"?`))) return;
          bundle.extra_vars = (bundle.extra_vars ?? []).filter((variable) => variable.key !== key);
          await persist();
          render();
        })();
        break;
      }
      case 'bundle-add-project':
      case 'bundle-add-category':
      case 'bundle-add-tag': {
        const bundleId = el.dataset.bundle ?? '';
        const kind = action.slice('bundle-add-'.length);
        void (async () => {
          const bundle = st.vault.api_keys.find(
            (entry) => entry.id === bundleId && entry.secretType === 'bundle',
          );
          if (!bundle) return;
          const value = (await showPrompt(`Assign ${kind} to every member`))?.trim();
          if (!value) return;
          const members = st.vault.api_keys.filter((entry) => entry.bundle_id === bundleId);
          if (kind === 'project') {
            const project = st.vault.projects.find(
              (item) => item.id === value || item.name === value,
            );
            if (!project) {
              showToast('Choose an existing project name or ID', 'err');
              return;
            }
            for (const member of members) {
              if (!member.projectIds.includes(project.id)) member.projectIds.push(project.id);
            }
          } else if (kind === 'category') {
            if (!st.vault.user_categories.includes(value)) {
              showToast('Choose an existing category', 'err');
              return;
            }
            for (const member of members) {
              if (!member.categories.includes(value)) member.categories.push(value);
            }
          } else {
            for (const member of members) {
              member.tags ??= [];
              if (!member.tags.includes(value)) member.tags.push(value);
            }
          }
          await persist();
          render();
          showToast(
            `${kind[0].toUpperCase()}${kind.slice(1)} assigned to ${members.length} member${members.length === 1 ? '' : 's'}`,
            'ok',
          );
        })();
        break;
      }
      case 'bundle-order': {
        const bundleId = el.dataset.bundle ?? '';
        const members = st.vault.api_keys
          .filter((entry) => entry.bundle_id === bundleId)
          .sort((a, b) => (a.bundle_order ?? 0) - (b.bundle_order ?? 0));
        const at = members.findIndex((entry) => entry.id === el.dataset.member);
        const to = at + Number(el.dataset.direction ?? 0);
        if (at < 0 || to < 0 || to >= members.length) break;
        [members[at].bundle_order, members[to].bundle_order] = [
          members[to].bundle_order ?? (to + 1) * 10,
          members[at].bundle_order ?? (at + 1) * 10,
        ];
        void persist().then(() => render());
        break;
      }
      case 'bundle-dissolve': {
        const bundleId = el.dataset.bundle ?? '';
        const bundle = st.vault.api_keys.find(
          (entry) => entry.id === bundleId && entry.secretType === 'bundle',
        );
        if (!bundle) break;
        st.vault.api_keys.forEach((entry) => {
          if (entry.bundle_id === bundleId) {
            delete entry.bundle_id;
            delete entry.bundle_slot;
            delete entry.bundle_order;
          }
        });
        bundle.secretType = 'env_var';
        delete bundle.bundle_primary;
        void (async () => {
          await persist();
          render();
          showToast('Bundle dissolved; entries preserved', 'ok');
        })();
        break;
      }
      case 'bundle-delete-all': {
        const bundleId = el.dataset.bundle ?? '';
        const bundle = st.vault.api_keys.find(
          (entry) => entry.id === bundleId && entry.secretType === 'bundle',
        );
        if (!bundle) break;
        void (async () => {
          const doomed = st.vault.api_keys.filter(
            (entry) => entry.id === bundleId || entry.bundle_id === bundleId,
          );
          // Dissolve keeps every member; this destroys them, so it names the
          // count of entries (not cards) and goes through the undo stack.
          if (
            !(await showConfirm(
              `Delete bundle "${bundle.provider}" AND its ${doomed.length - 1} member entries? This removes secrets.`,
            ))
          )
            return;
          const positions = doomed.map((entry) => st.vault.api_keys.indexOf(entry));
          st.vault.api_keys = st.vault.api_keys.filter((entry) => !doomed.includes(entry));
          await persist();
          render();
          pushUndo(`Deleted bundle "${bundle.provider}" and ${doomed.length - 1} members`, () => {
            doomed.forEach((entry, i) =>
              st.vault.api_keys.splice(Math.min(positions[i], st.vault.api_keys.length), 0, entry),
            );
            void persist().then(() => render());
          });
        })();
        break;
      }
      case 'bundle-suggest-dismiss': {
        const provider = (el.dataset.provider ?? '').toLowerCase();
        const list = Settings.get('dismissedBundleSuggestions') ?? [];
        if (provider && !list.includes(provider))
          Settings.set('dismissedBundleSuggestions', [...list, provider]);
        render();
        break;
      }
      case 'bundle-suggest-accept': {
        const group = bundleSuggestions(st.vault.api_keys, []).find(
          (g) => g.provider.toLowerCase() === (el.dataset.provider ?? '').toLowerCase(),
        );
        if (!group) break;
        const bundle = buildBundle(group.entries, group.provider);
        st.vault.api_keys.push(bundle);
        void (async () => {
          await persist();
          render();
          showToast(`Bundled ${group.entries.length} entries`, 'ok');
        })();
        break;
      }
      case 'codes-use': {
        const entry = st.vault.api_keys[parseInt(el.dataset.idx ?? '-1', 10)] as
          VaultEntry | undefined;
        if (entry?.secretType !== 'recovery_codes') break;
        // Marking is explicit: showing a code never spends it. This is the
        // "the service accepted it" button.
        void (async () => {
          const code = nextCode(entry);
          if (!code) return;
          if (!(await showConfirm(`Mark the next recovery code as used for "${entry.provider}"?`)))
            return;
          const codes = entry.extra_vars?.find((v) => v.key === 'codes');
          if (!codes) return;
          try {
            codes.value = markUsed(entry, null, new Date().toISOString().slice(0, 10));
          } catch (err) {
            showToast(errorMessage(err), 'err');
            return;
          }
          await persist();
          render();
          showToast(`${codeStatus(entry).remaining} recovery codes left`, 'ok');
        })();
        break;
      }
      case 'bundle-export': {
        const bundleId = el.dataset.bundle ?? '';
        const bundle = st.vault.api_keys.find(
          (entry) => entry.id === bundleId && entry.secretType === 'bundle',
        );
        if (!bundle) break;
        const members = st.vault.api_keys
          .filter((entry) => entry.bundle_id === bundleId)
          .sort((a, b) => (a.bundle_order ?? 0) - (b.bundle_order ?? 0));
        const formats: [BundleExportFormat, string][] = [
          ['dotenv', '.env'],
          ['python', 'Python'],
          ['javascript', 'JavaScript'],
          ['typescript', 'TypeScript'],
          ['json', 'JSON'],
          ['yaml', 'YAML'],
          ['toml', 'TOML'],
          ['shell', 'Shell'],
        ];
        showContextMenu(
          (e as MouseEvent).clientX,
          (e as MouseEvent).clientY,
          formats.map(([format, label]) => ({
            label: `Copy all as ${label}`,
            fn: () => {
              try {
                void clipboardWrite(buildBundleExport(bundle, members, format)).then(() =>
                  showToast(`Bundle copied as ${label}`, 'ok'),
                );
              } catch (error) {
                showToast(`Export failed: ${String(error)}`, 'err');
              }
            },
          })),
        );
        break;
      }
    }
  };
  document.getElementById('card-grid')!.addEventListener('click', onGridClick);
  // The "bundle them?" banner sits above the grid, not inside it, so a listener on
  // the grid never saw its Accept and Dismiss buttons: both did nothing in the
  // real app (found by the Phase 32.2 probe). Delegated from the document
  // because the banner is created lazily by the first render that needs it.
  document.addEventListener('click', (e) => {
    if ((e.target as Element | null)?.closest?.('#bundle-suggest')) onGridClick(e);
  });

  // Card grid — double-click to edit
  document.getElementById('card-grid')!.addEventListener('dblclick', (e) => {
    const card = (e.target as HTMLElement).closest<HTMLElement>('[data-idx]');
    if (!card) return;
    const idx = parseInt(card.dataset.idx!);
    if (!isNaN(idx)) openEdit(e as MouseEvent, idx);
  });

  // Card grid — right-click context menu
  document.getElementById('card-grid')!.addEventListener('contextmenu', (e) => {
    const card = (e.target as HTMLElement).closest<HTMLElement>('[data-idx]');
    if (!card) return;
    e.preventDefault();
    const idx = parseInt(card.dataset.idx!);
    if (isNaN(idx)) return;
    const entry = st.vault.api_keys[idx];
    if (!entry) return;
    const _keyLabel = TYPE_CONFIG[entry.secretType || 'api_key']?.keyLabel || 'Key';
    const _items: (DropdownItem | '---')[] = [
      {
        label: `Copy Provider: ${entry.provider}`,
        fn: () => clipboardWrite(entry.provider).then(() => showToast('Copied ✓', 'ok', 1500)),
      },
      { label: `Copy ${_keyLabel}`, fn: () => copyField(e as MouseEvent, entry.api_key, card) },
    ];
    if (entry.api_secret)
      _items.push({
        label: 'Copy Secret',
        fn: () => copyField(e as MouseEvent, entry.api_secret!, card),
      });
    // Resolve the position again when the item is actually clicked. The menu
    // captures `idx` at open time, and anything that splices api_keys in
    // between (an undo restoring an entry, a peer's edit reloading the vault)
    // would otherwise point these at the wrong secret.
    const liveIdx = () => st.vault.api_keys.indexOf(entry);
    const onEntry = (fn: (i: number) => void) => () => {
      const i = liveIdx();
      if (i < 0) {
        showToast('That secret no longer exists', 'err');
        return;
      }
      fn(i);
    };
    _items.push(
      { label: 'Copy .env line', fn: onEntry((i) => doCopyEnv(e as MouseEvent, i)) },
      '---',
      { label: 'Edit', fn: onEntry((i) => openEdit(e as MouseEvent, i)) },
      { label: 'Duplicate', fn: onEntry((i) => duplicateKey(e as MouseEvent, i)) },
      '---',
      { label: 'Delete', fn: onEntry((i) => deleteKey(e as MouseEvent, i)) },
    );
    showContextMenu(e.clientX, e.clientY, _items);
  });

  // Misc
  document.getElementById('vault-switcher')!.addEventListener('click', (e) => {
    const isRemote = st.store instanceof RemoteVaultStore;
    const saved = Settings.get('remoteSaved') ?? [];
    const items: (DropdownItem | '---')[] = [
      {
        label: isRemote ? '  Local Vault' : '⬤ Local Vault',
        active: !isRemote,
        // Shared with the Remote panel's Disconnect button — it also clears
        // st.vault.projects (which this used to leave behind) and prompts for
        // the master password when the local vault is still locked.
        fn: () => {
          if (isRemote) void switchToLocalVault();
        },
      },
      '---',
    ];
    saved.forEach((cfg) => {
      const connected = st.activeRemoteId === cfg.id;
      items.push({
        label: `${connected ? '⬤' : '  '} ${cfg.name}`,
        active: connected,
        fn: () => {
          if (!connected) {
            switchPanel('remote');
            st.activeRemoteId = cfg.id;
            // Static import — remote-panel is already in this module's graph, so a
            // dynamic import here only produced a Vite chunking warning.
            renderRemotePanel();
          }
        },
      });
    });
    items.push('---');
    items.push({ label: '+ Add Remote Vault', active: false, fn: () => switchPanel('remote') });
    items.push({ label: 'Remote settings…', active: false, fn: () => openSettings() });
    showDropdown(e.currentTarget as HTMLElement, items);
  });
  document.getElementById('f-secret-type')?.addEventListener('change', (e) => {
    dynamicSecretFields();
    suggestExtraVarsForType((e.target as HTMLSelectElement).value as SecretType);
  });
  document.getElementById('f-key-generate')?.addEventListener('click', () => void quickGenerate());

  // ── Tauri unlock flow ──
  if (inTauri) {
    void (st.store as TauriVaultStore).vaultFilePath().then((p) => {
      const el = document.getElementById('lock-status');
      if (el && p) el.title = `Vault file: ${p}`;
    });
    document.getElementById('vault-name')!.textContent = 'Local Vault';
    const exists = await (st.store as TauriVaultStore).exists();
    showUnlockModal(!exists);
    return;
  }

  // Web path
  await finishInit();
}

// A boot that throws must not leave the shell hidden forever: `html.booting`
// is removed by whichever of `showUnlockModal()` / `finishInit()` runs, and a
// failure before either would otherwise present a blank window with no error.
init().catch((e) => {
  document.documentElement.classList.remove('booting');
  console.error('EnvVault failed to start', e);
  showToast('Failed to start — see the console', 'err', 6000);
});
